### ISSUE TITLE
Exception in callback _SelectorDatagramTransport._read_ready()

### ISSUE THREAD

**Issue by Yonny24** [rospogrigio/localtuya#1000]
HA version 2022.8.7

Updated number.py manually from https://github.com/rospogrigio/localtuya/pull/944/files

But still getting the same error after rebooting

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/localtuya/common.py:117
Integration: LocalTuya (documentation, issues)
First occurred: 9:18:30 PM (1042 occurrences)
Last logged: 9:24:43 PM

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
    self.device_found(decoded)
  File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
    self._callback(device)
  File "/config/custom_components/localtuya/__init__.py", line 105, in _device_discovered
    entry = async_config_entry_by_device_id(hass, device_id)
  File "/config/custom_components/localtuya/common.py", line 117, in async_config_entry_by_device_id
    if device_id in entry.data[CONF_DEVICES]:
KeyError: 'devices'
`

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/localtuya/__init__.py:242
Integration: LocalTuya (documentation, issues)
First occurred: 9:18:30 PM (1 occurrences)
Last logged: 9:18:30 PM

Error setting up entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 242, in async_setup_entry
    region = entry.data[CONF_REGION]
KeyError: 'region'
`

**Comment by Yonny24** [comment]
Thanks a lot - all fixed with the latest version you pushed!
