### ISSUE TITLE
New device is marked as "Unavailable" after adding it and can not be removed

### ISSUE THREAD

**Issue by Hugo-Persson** [rospogrigio/localtuya#1011]
# Descriptions
After adding a new Tuya light bulb the entity is marked as Unavailable. If I try to edit it and unchecking the ID to remove it I get an error with the following log

```
This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:237
Integration: LocalTuya (documentation, issues)
First occurred: August 31, 2022 at 9:19:03 AM (4 occurrences)
Last logged: 8:36:22 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 533, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 237, in validate_input
    data[CONF_DEVICE_ID],
KeyError: 'device_id'
```

I have tried removing the device from the home assistant menu and that works but when I add the device again the same problem persists. I add the device with the following config:
![Screenshot 2022-08-30 at 19 40 21](https://user-images.githubusercontent.com/47189713/188217673-2b9c7683-0bdd-400d-9cf3-1cbe6a2e06a5.png)

# Logs
Error when trying to delete:
```
This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:237
Integration: LocalTuya (documentation, issues)
First occurred: August 31, 2022 at 9:19:03 AM (4 occurrences)
Last logged: 8:36:22 PM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 533, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 237, in validate_input
    data[CONF_DEVICE_ID],
KeyError: 'device_id'
```
Other error:
```
This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya (documentation, issues)
First occurred: August 30, 2022 at 9:48:34 PM (3975 occurrences)
Last logged: 8:06:23 PM

[bf5...ukd] Connect to 192.168.0.183 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 160, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.183', 6668)
````

I have other devices that I set up long time ago and they are working fine but this new device is not working. Am I doing something wrong? Do anyone know how to fix this?

**Comment by steveharm** [comment]
for color you have dp 23 which I use for colour temp
Have you tried using dp 24 for colour and 25 for scene
To delete it restart HA then view the device... click on the 3 vertical dots and select delete.

**Comment by Hugo-Persson** [comment]
The following config made it possible to turn off the device but I can not control brightness or color or temperature.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/47189713/188716096-973857bb-31e4-4184-b9a7-45b178955ae9.png">

**Comment by steveharm** [comment]
Brightness - 22
Colour Temp - 23
Colour Mode - 21
Colour 24
Scene 25

**Comment by Hugo-Persson** [comment]
Wow that works, thank you 🤩
