### ISSUE TITLE
 Error: Failed to set DP 1 to False

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [rospogrigio/localtuya#1018]
## Environment

- Localtuya version:  
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version:  
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1.
2. 
3.

## Configuration `configuration.yaml` or `config_flow`

```yaml

```

## Provide Home Assistant taceback/logs

```txt

```
## Additional information

After update to V4.1.0 I get following error message:

This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:259
Integration: LocalTuya (documentation, issues)
First occurred: 19:39:20 (1 occurrences)
Last logged: 19:39:20

[482...820] Failed to set DP 1 to False
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 316, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 553, in set_dp
    return await self.exchange(SET, {str(dp_index): value})
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by DeerMaximum** [comment]
Have the same problem, the error is preceded by a connection failure.

```
Entity AC ECO (DP 8) - Restoring state: False
2022-09-14 05:56:53.156 ERROR (MainThread) [custom_components.localtuya.common] [bf9...4ei] Not connected to device AC
2022-09-14 05:56:53.158 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Heartbeat failed due to timeout, disconnecting
2022-09-14 05:56:53.660 DEBUG (MainThread) [custom_components.localtuya.common] [bf9...4ei] Connecting to 192.168.2.110
2022-09-14 05:56:53.689 DEBUG (MainThread) [custom_components.localtuya.common] [bf9...4ei] Retrieving initial state
2022-09-14 05:56:53.689 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Sending command status (device type: type_0a)
2022-09-14 05:56:53.689 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Send payload: b'{"gwId":"***","devId":"***"}'
2022-09-14 05:56:53.690 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Waiting for sequence number 0
2022-09-14 05:56:53.697 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Dispatching message TuyaMessage(seqno=0, cmd=10, retcode=0, payload=b'<\xf1\xefj\xc8SR`\x15\x07\xd2\x12\xd6\xf1\xf0\xe1\x96j\xd8\xcdM\xf3\xfc\xf1\xb4\x95\xa1\nq\xfb\xe7\xcb*#\xb1{\x88\xb31#\xfb-C\x9e\xa0\x00\x0f%\xf5\xad\x8f[\xae\xad}M\xd1:f\x1chj\xf0\x9b\xb39\x9e\xf6\xa9\x83\x99\xa6\r|h\xebod-K\xb0\x8a\x99x\xb18\xa9l\x8b\x98\x13\x94\x84\xd4\xfb\x08g*\x9ah(\x80\\/\xecZ\xcb\x98,\x17E\xbb\xb4\xc0\xee\xee#|\x98\x1d\xa8\xa8\xffX\xd0g.\xc7\x93\'\xb7\x1b\x0c\x08$q03\x12\xf9B\x19\xadbP\xf8\x15\xdd\xc3\x01f\x90\xc6{\x04\xe3\x9a\xf3\xea\xdd\x02j\xc9a\x98\x80\x81D~\x19\xc7\x9a\x91\x01~WXl\xf9\x14k\xff\xfd\xfe[\x0c\xf3\xa7\x14\xa1\x7f\x89\x94\x97\x92%\xec\x18r2\x10e\xd1\xc4\xe7@-\xc2\xbc\xe7\x19\xe1&k\x848%J\x03\xd75\xe4]\xe2\x0bA\x12%MY\xf1sRP|\x9c\xf5<\x02\xf1"G\x93a\x81G\x13\xfb;\xc1\xae\xea\x1d\x95\x97\\\xfdD\xf5\x87\x85\x02u\xea\x07\xcf"\t\xc7\xd1\xd2\x99', crc=3812145985)
2022-09-14 05:56:53.697 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Dispatching sequence number 0
2022-09-14 05:56:53.698 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Decrypted payload: {"dps":{"1":false,"2":320,"3":270,"4":"cold","5":"auto","8":false,"12":false,"13":true,"14":false,"19":"C","28":0,"33":false,"102":false,"103":false,"104":false,"105":false,"106":false,"107":0,"108":14,"109":false,"110":false,"111":0,"112":15,"114":false}}
2022-09-14 05:56:53.699 DEBUG (MainThread) [custom_components.localtuya.number] [bf9...4ei] Attempting to restore state for entity: AC Zieltemperatur Number
2022-09-14 05:56:53.699 DEBUG (MainThread) [custom_components.localtuya.number] [bf9...4ei] Entity AC Zieltemperatur Number (DP 2) - Restoring state: 320
2022-09-14 05:56:53.699 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Sending command set (device type: type_0a)
2022-09-14 05:56:53.699 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Send payload: b'{"devId":"***","uid":"***","t":"1663127813","dps":{"2":320}}'
2022-09-14 05:56:53.702 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Waiting for sequence number 1
2022-09-14 05:56:53.703 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Started heartbeat loop
2022-09-14 05:56:53.703 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Sending command heartbeat (device type: type_0a)
2022-09-14 05:56:53.703 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Send payload: b'{}'
2022-09-14 05:56:53.704 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Waiting for sequence number -100
2022-09-14 05:56:53.705 DEBUG (MainThread) [custom_components.localtuya.sensor] [bf9...4ei] Entity AC Aktuelle Temperatur - Additional attributes: {'raw_state': 27.0}
2022-09-14 05:56:53.706 DEBUG (MainThread) [custom_components.localtuya.number] [bf9...4ei] Entity AC Zieltemperatur Number - Additional attributes: {'raw_state': 320}
2022-09-14 05:56:53.706 DEBUG (MainThread) [custom_components.localtuya.select] [bf9...4ei] Entity AC Modus - Additional attributes: {'raw_state': 'cold'}
2022-09-14 05:56:53.706 DEBUG (MainThread) [custom_components.localtuya.select] [bf9...4ei] Entity AC Lüfterstärke - Additional attributes: {'raw_state': 'auto'}
2022-09-14 05:56:53.741 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x12Y\x9a\x00\x00\x00\x01Xc\xf7\x03\xfc\x96\x1e\x843-\x95e\x08\xff\xdb\x16\x10mU\xf7\x199.\xe5\xcb\xb4\x93\x0c\xb2\x9cZ\x17\xb2\n\x84J\x8d\x0f#t\x8f\xe0\x92\xe1l\xcf\xa6\x01', crc=793695705)
2022-09-14 05:56:53.741 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Got status update
2022-09-14 05:56:53.744 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Decrypted payload: {"dps":{"2":320},"type":query,"t":1663127812}
2022-09-14 05:56:53.744 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 868, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 437, in data_received
    self.dispatcher.add_data(data)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 298, in add_data
    self._dispatch(TuyaMessage(seqno, cmd, retcode, payload, crc))
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 328, in _dispatch
    self.listener(msg)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 394, in _status_update
    decoded_message = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 623, in _decode_payload
    return json.loads(payload)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 25 (char 24)
2022-09-14 05:56:53.752 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf9...4ei] Connection lost: Expecting value: line 1 column 25 (char 24)
2022-09-14 05:56:53.752 DEBUG (MainThread) [custom_components.localtuya.common] [bf9...4ei] Disconnected - waiting for discovery broadcast
2022-09-14 05:56:58.703 ERROR (MainThread) [custom_components.localtuya.common] [bf9...4ei] Failed to set DP 2 to 320
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 316, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 553, in set_dp
    return await self.exchange(SET, {str(dp_index): value})
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by dt3ft** [comment]
same here:
Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:259
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 19:00:49 (1 occurrences)
Last logged: 19:00:49

[002...8a1] Failed to set DP 1 to False
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 320, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 553, in set_dp
    return await self.exchange(SET, {str(dp_index): value})
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by dt3ft** [comment]
its a timeout, any debug flag to see the request ?

**Comment by sweetpants** [comment]
I'm seeing the same when switching on/off a Mini Smart Switch, but it happens some time after the switch is succefully switched on/off

2023-08-27 15:39:13.766 ERROR (MainThread) [custom_components.localtuya.common] [bf4...cbr] Failed to set DP 1 to False
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 321, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 842, in set_dp
    return await self.exchange(CONTROL, {str(dp_index): value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-08-27 15:40:23.046 ERROR (MainThread) [custom_components.localtuya.common] [bf4...cbr] Failed to set DP 1 to True
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 321, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 842, in set_dp
    return await self.exchange(CONTROL, {str(dp_index): value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
