### ISSUE TITLE
SmartDoorBell-IPBox: Datapoints not found

### ISSUE THREAD

**Issue by Bibyte** [rospogrigio/localtuya#1056]
I Try to add a new device and got error: "Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists." In both protocols 3.1 and 3.3
The Log:
`Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:618
Integration: LocalTuya integration (documentation, issues)
First occurred: 21:46:48 (2 occurrences)
Last logged: 21:46:48

[bfc...lgi] Failed to get status: Unexpected payload=b"\x8d_\xf6\xe2\x0eRS\xd3\x17\xa48\xc1\x0fuf\x960\x93\xb5\xb7'\xe7\x9c\x16\xe4l\x1f\x93\xd7\x8e\x0fV"
Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 574, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 507, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 492, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 618, in _decode_payload
    raise Exception(f"Unexpected payload={payload}")
Exception: Unexpected payload=b"\x8d_\xf6\xe2\x0eRS\xd3\x17\xa48\xc1\x0fuf\x960\x93\xb5\xb7'\xe7\x9c\x16\xe4l\x1f\x93\xd7\x8e\x0fV"
`

**Comment by Bibyte** [comment]
Can anybody help me?

**Comment by sinclairfr** [comment]
I have the exact same problem.

**Comment by Bibyte** [comment]
Anybody please help us!

**Comment by Murat40** [comment]
@Bibyte Idk if these are your private location and ip but if it is delete them...
