### ISSUE TITLE
Issues removing dead bulb

### ISSUE THREAD

**Issue by aidzer0** [rospogrigio/localtuya#1059]
Hello, recently I had a bulb die on me, I have been trying to remove it from HA with 0 success.

I have tried deleting the device through LocalTuya integration (Integrations > Configure > Edit device > Uncheck to delete device) thats when the error I pasted below shows. There are also log entries regarding LocalTuya not being able to connect to the bulb which is obvious since its dead.

I have also tried through HA (Devices and Services > navigate to the bulb > 3 dots > Delete)

I also tried to modify the .storage registry but I bombed my HA instance, I would prefer not to use that method again... (Thankfully I backup HA to my Google drive so recovery was an option)

Please help, I actually had a different bulb die and I was able to remove it no problem, this one on the other hand is being stubborn. Thanks!

What the HA logs show:
``` Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:247
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 09:24:31 (1 occurrences)
Last logged: 09:24:31

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 580, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 247, in validate_input
    data[CONF_DEVICE_ID],
KeyError: 'device_id'

**Comment by nvx** [comment]
I just ran into the same issue trying to remove a dead smart plug

**Comment by nvx** [comment]
https://github.com/rospogrigio/localtuya/issues/871#issuecomment-1156923434

Deleting via the three dots worked for me. Looks like it's just the config flow way that's broken.

**Comment by aidzer0** [comment]
If I do it that way, I deletes the entity and as soon as I refresh the webpage, the bulb comes back.

**Comment by AntoineGS** [comment]
Also encountering this, it seems most editing does not actually persist, like unchecking a dps does not remove it, and changing the csv for dps, while the csv persists, does not trigger the prompts to configure them.

**Comment by mizifih** [comment]
Same thing. And when I removed using Delete from the three dots, I am now getting a "_Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists._" error message when I try to add the device again. It actually came with all the options filled on the add form, secrets and IDs.

**Comment by grrraham** [comment]
Settings > Devices and services > Localtuya.    Click on 1_Device inside the integration box.  
Click on the pencil top right of the screen.
Disable the device.
Update

Beside Download Diagnostics click on the vertical ...
Delete the device.

**Comment by aidzer0** [comment]
> Settings > Devices and services > Localtuya. Click on 1_Device inside the integration box. Click on the pencil top right of the screen. Disable the device. Update
> 
> Beside Download Diagnostics click on the vertical ... Delete the device.

This worked!

Thank you so much! How did you figure that one out? Just Tried different options?

**Comment by grrraham** [comment]
You are welcome :)

Home assistant likes to put (hide) important menus / options top right.  Half the time when I cant immediately do something, its because I haven't explored options top right.

**Comment by neuronflow** [comment]
Hmm I don't see the dots :(

**Comment by neuronflow** [comment]
after disabling and reenabling and restarting HA the dots became visible! oO
