### ISSUE TITLE
Integration pings disabled device

### ISSUE THREAD

**Issue by MG-Sky** [rospogrigio/localtuya#1068]
## The problem

Hi,

I have disabled my smart bulb in integration - also reloaded the integration after that, but i'm still seeing the errors:
[063...264] Connect to xxx.xxx.xxx.xxx failed
OSError: [Errno 113] Connect call failed ('xxx.xxx.xxx.xxx', 6668)
it appears each minute.

did i miss anytinhg?

## Environment

- Localtuya version: 4.1.0 

- Last working localtuya version (if known and relevant): 
- Home Assistant Core version:  2022.09
- [] Are you using the Home Assistant Tuya Cloud component ? no
- [] Are you using the Tuya App in parallel ? no

## Steps to reproduce

1. disabled device from device page
2. reloaded integration

## Configuration `configuration.yaml` or `config_flow`

attached

```
[json.txt](https://github.com/rospogrigio/localtuya/files/9725829/json.txt)

## DP dump
<!-- 
  Paste here a DP dump, see https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump
  You can also try to qualify your device using the procedure described https://github.com/rospogrigio/localtuya/wiki/Qualifying-a-device
-->

## Provide Home Assistant taceback/logs
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 185, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 704, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('xxx', 6668)

**Comment by pcb1962** [comment]
Issue is still there, the integration attempts connection to disabled devices.

All these devices are disabled, the integration should not be trying to connect to them:
2026-06-30 09:40:23.373 WARNING (MainThread) [custom_components.localtuya.common] [bff...nmv] Failed to connect to 192.168.1.175: [Errno 113] Connect call failed ('192.168.1.175', 6668)
2026-06-30 09:40:23.374 WARNING (MainThread) [custom_components.localtuya.common] [bf8...nxs] Failed to connect to 192.168.1.176: [Errno 113] Connect call failed ('192.168.1.176', 6668)
2026-06-30 09:40:23.375 WARNING (MainThread) [custom_components.localtuya.common] [bf7...rsb] Failed to connect to 192.168.1.177: [Errno 113] Connect call failed ('192.168.1.177', 6668)
2026-06-30 09:40:23.375 WARNING (MainThread) [custom_components.localtuya.common] [bf7...x8q] Failed to connect to 192.168.1.178: [Errno 113] Connect call failed ('192.168.1.178', 6668)
