### ISSUE TITLE
Suggest to handle device offline gracefully

### ISSUE THREAD

**Issue by donburch888** [rospogrigio/localtuya#1073]
I have lately added more Wi-Fi power plugs and exceeded my Wi-Fi routers station list, so some devices temporarily drop off wi-fi.  
Also some of the power switches I use to monitor energy usage, only as required.  

A Tuya device being unavailable currently generates an error with traceback 

> This error originated from a custom integration.
> 
> Logger: custom_components.localtuya.common
> Source: custom_components/localtuya/pytuya/__init__.py:704
> Integration: LocalTuya (documentation, issues)
> First occurred: October 7, 2022, 9:53:25 AM (1741 occurrences)
> Last logged: 2:09:31 PM
> 
> [382...7d8] Connect to 192.168.1.160 failed
> [bfc...9ka] Connect to 192.168.1.106 failed
> [bf3...a5z] Connect to 192.168.1.108 failed
> Traceback (most recent call last):
>   File "/config/custom_components/localtuya/common.py", line 185, in _make_connection
>     self._interface = await pytuya.connect(
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 704, in connect
>     _, protocol = await loop.create_connection(
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
>     raise exceptions[0]
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
>     sock = await self._connect_sock(
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
>     await self.sock_connect(sock, address)
>   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
>     return await fut
>   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
>     raise OSError(err, f'Connect call failed {address}')
> ConnectionResetError: [Errno 104] Connect call failed ('192.168.1.160', 6668)

The official answer is probably to delete any currently-unused devices from HA to stop LocalTuya from attempting to contact them - but I would prefer not to have to re-add them when i want to use next time. 

I suggest that device offline condition should be anticipated by LocalTuya gracefully, so that it still logs an error but without traceback.  

For that matter, I am not sure whether a device being offline is an error or a warning - possibly depends on the individual situation.

**Comment by remlei** [comment]
>The official answer is probably to delete any currently-unused devices from HA to stop LocalTuya from attempting to contact them - but I would prefer not to have to re-add them when i want to use next time.

localtuya is smart enough to stop reconnection attempts if the device is unavailable, specially if that device is not powered on or not connected to wifi. localtuya will just wait for the UDP broadcast of that tuya device to appear again to the network and then reattempt the connection again.

>Wi-Fi power plugs and exceeded my Wi-Fi routers station list, so some devices temporarily drop off wi-fi.
Also some of the power switches I use to monitor energy usage, only as required.

I also have this issue in the past but there's a thread somewhere in spanish group actually recommends getting a mediatek based AP and use that dedicated for tuya devices, and this actually solves my issue.

from a 10 times or more unavailable events on that tuya device to, 0-1 unavailable events per week after I used a mediatek based access point.

**Comment by donburch888** [comment]
> recommends getting a mediatek based AP

This is the information I have been searching a month for, trying to find out which AP supports more IoT concurrent devices.  Aaghhh ! But now I am awaiting delivery of a new wi-fi router !!!

**Comment by donburch888** [comment]
> localtuya is smart enough to stop reconnection attempts if the device is unavailable, specially if that device is not powered on 

That is what I had expected, but sadly once per minute I am getting:
```
2022-10-16 12:40:57.868 ERROR (MainThread) [custom_components.localtuya.common] [bfe...ndf] Connect to 192.168.1.105 failed
Traceback (most recent call last):
File "/config/custom_components/localtuya/common.py", line 186, in _make_connection
self._interface = await pytuya.connect(
File "/config/custom_components/localtuya/pytuya/__init__.py", line 704, in connect
_, protocol = await loop.create_connection(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
return await fut
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.105', 6668)
```
This particular device is disabled and not powered on. 
![image](https://user-images.githubusercontent.com/60803198/196017124-d4339fd2-a894-4863-9c4b-036163e55ee1.png)

**Comment by purcell-lab** [comment]
Agree,

I have a device which is disconnected, but localtuya continues to attempt connection and logs an error message, this error should be downgraded to a warning as devices come and go all the time.  Perhaps some error handling around ConnectionRefusedError.

```
2022-11-04 09:07:01.905 ERROR (MainThread) [custom_components.localtuya.common] [bf0...1jh] Connect to 192.168.86.41 failed
Traceback (most recent call last):
File "/config/custom_components/localtuya/common.py", line 186, in _make_connection
self._interface = await pytuya.connect(
File "/config/custom_components/localtuya/pytuya/__init__.py", line 704, in connect
_, protocol = await loop.create_connection(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
return await fut
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.86.41', 6668)
```

**Comment by seanmccabe** [comment]
Get the same issue, I've got 2 devies I've marked as disabled, as they are are smart switches only used for Xmas lights.
Every minute getting entries to the log that LocalTuya is unable to connect to these devices.

> localtuya is smart enough to stop reconnection attempts if the device is unavailable, specially if that device is not powered on or not connected to wifi. localtuya will just wait for the UDP broadcast of that tuya device to appear again to the network and then reattempt the connection again.

The logs and comments from multiple plugs and people seem to fly in the face of the comment by @remlei 

Any word on an update and fix for this?
