### ISSUE TITLE
All localtuya device down since 4.1.0

### ISSUE THREAD

**Issue by jmcollin78** [rospogrigio/localtuya#1076]
Since the installation of 4.1.0 I've got all my tuya devices down.
In the logs, I've got various error messages:

```
2022-10-10 20:12:49.920 ERROR (MainThread) [custom_components.localtuya.common] [322...29d] Connect to 192.168.1.39 failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 202, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 507, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 216, in _make_connection
    await self._interface.reset(self._default_reset_dpids)
AttributeError: 'NoneType' object has no attribute 'reset'
```

## Environment
- Localtuya version: 4.1.0
- Last working localtuya version (if known and relevant): 4.0.2
- Home Assistant Core version: 
Home Assistant 2022.10.1
Supervisor 2022.10.0
Operating System 9.0
Interface utilisateur : 20221006.0 - latest

- [x] Are you using the Home Assistant Tuya Cloud component ? 
- [x] Are you using the Tuya App in parallel ? 

## Steps to reproduce
restart and look logs

## Configuration `configuration.yaml` or `config_flow`
```yaml
not relevant
```

## Provide Home Assistant taceback/logs
```txt
2022-10-10 20:12:49.920 ERROR (MainThread) [custom_components.localtuya.common] [322...29d] Connect to 192.168.1.39 failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 202, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 507, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 216, in _make_connection
    await self._interface.reset(self._default_reset_dpids)
AttributeError: 'NoneType' object has no attribute 'reset'
```
## Additional information
Will try to restore the 4.0.2 release

**Comment by jmcollin78** [comment]
This is a very annoying issue since nothing works anymore...

**Comment by jmcollin78** [comment]
After some investigations it appears that many of my Tuya device where no more paired to my Tuya cloud account. Their apikey have changed and then LocalTuya don't know it anymore.
Very strange which certainly have nothing to do with LocalTuya 4.1.0. Just a coincidence certainly.
