### ISSUE TITLE
Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()

### ISSUE THREAD

**Issue by madjoe1976** [rospogrigio/localtuya#1095]
Localtuya: 4.1.1
Home Assistant 2022.10.5

Logger: homeassistant
Source: custom_components/localtuya/common.py:125
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 12:44:35 AM (1571 occurrences)
Last logged: 1:01:02 AM
Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
    self.device_found(decoded)
  File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
    self._callback(device)
  File "/config/custom_components/localtuya/__init__.py", line 105, in _device_discovered
    entry = async_config_entry_by_device_id(hass, device_id)
  File "/config/custom_components/localtuya/common.py", line 125, in async_config_entry_by_device_id
    if device_id in entry.data[CONF_DEVICES]:
KeyError: 'devices'

**Comment by tefracky** [comment]
I have the same issue, which occures every second (?) an error. Is this really an error or just cosmetics?

**Comment by CanberraTinkerer** [comment]
I'm also having this same problem

**Comment by broyuken** [comment]
I have the same error in my logs, and all of my lights work fine, but this fills my logs every second or two.

**Comment by findel** [comment]
I'm getting this too. Any fix other than reinstalling and setting everything up from scratch?

**Comment by findel** [comment]
Looks to me like this is a duplicate of #869

So are #887 and #930

I'm going to repost my comment in #869. 

I suggest everyone else who is experiencing this error also uses #869
