### ISSUE TITLE
unable to add any devices to local tuya

### ISSUE THREAD

**Issue by fire943** [rospogrigio/localtuya#1098]
## Environment

- Localtuya version:  
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version:  
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1.
2. 
3.

## Configuration `configuration.yaml` or `config_flow`

```yaml

```

## Provide Home Assistant taceback/logs

```txt

```

**Comment by HSB-collab** [comment]
I have the same issue trying to add devices to localtuya. This used to work.

Environment
Localtuya version: 4.1.1
Last working localtuya version (if known and relevant):
Home Assistant Core version: Home Assistant 2022.10.5
[] Are you using the Home Assistant Tuya Cloud component ? yes
[] Are you using the Tuya App in parallel ? yes

This error originated from a custom integration.

Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:621
Integration: LocalTuya integration (documentation, issues)
First occurred: 14:51:15 (4 occurrences)
Last logged: 16:34:26

[387...2fa] Failed to get status: 'utf-8' codec can't decode byte 0xaa in position 2: invalid start byte
Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 574, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 507, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 492, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 621, in _decode_payload
    payload = payload.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 2: invalid start byte

**Comment by gg1971** [comment]
Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:704
Integration: LocalTuya integration (documentation, issues)
First occurred: 15:50:09 (2 occurrences)
Last logged: 15:50:54

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 580, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 245, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 704, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.3.9', 6668)

**Comment by HSB-collab** [comment]
@gg1971 you have included your local device key here. I suggest that you change it by resetting it.
Your problem is similar to mine. I made some progress by experimenting with the manual DPs but the issue is not solved for me. I have 3 identical devices 2 of which work (but not consistently) and 1 of which does not work at all even though I can see it is connected to the same WiFi network. I am stuck at that point.
