### ISSUE TITLE
Can't add one bulb out of a set of four, no datapoints found

### ISSUE THREAD

**Issue by chicknlil** [rospogrigio/localtuya#1138]
## The problem

One of four identical bulbs is failing to add (previous to this, it kept dropping as unavailable, only becoming available - briefly - when I would turn it on and off via the Smart Life app).  Bulbs are: DAYBETTER Tuya Smart Light Bulbs, RGBCW Wi-Fi Color Changing Led Bulbs Compatible with Alexa & Google Home Assistant, A19 E26 9W 800LM Multicolor Led Light Bulb

## Environment

- Localtuya version:   4.1.1
- Last working localtuya version (if known and relevant):  n/a
- Home Assistant Core version:   Home Assistant 2022.11.4
- [] Are you using the Home Assistant Tuya Cloud component ?  If you mean the Tuya integration, I removed it.  If you mean the cloud component of your integration, YES, I'm using that.
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Goto Integrations and Config LocalTuya
2.  Select Add New Device (it prefills with the only device not already connected, my "upstairs bathroom left light".
3. Hit Submit, and again.

## Configuration `configuration.yaml` or `config_flow`

```yaml

```
I'm not sure what this is or where to find it. My understanding was that ability to mess with the yaml was removed from this integration.

## DP dump

This errored out when I tried to do it, even after force closing the app on my Android phone.

## Provide Home Assistant taceback/logs

```Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:621
Integration: LocalTuya (documentation, issues)
First occurred: 9:57:24 PM (3 occurrences)
Last logged: 9:57:29 PM

[eb3...obi] Failed to get status: 'utf-8' codec can't decode byte 0xbb in position 5: invalid start byte
Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 574, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 507, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 492, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 621, in _decode_payload
    payload = payload.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 5: invalid start byte
```

**Comment by IceBotYT** [comment]
I am also having this issue. Are you still getting this issue?

**Comment by chicknlil** [comment]
> I am also having this issue. Are you still getting this issue?

I gave up on localtuya in part because of this issue (and the lack of response to it), and because other devices weren't working as they did under "regular" Tuya (a gas sensor, for example).

**Comment by IceBotYT** [comment]
Thank you for the swift response. This was not the response I was hoping for :(
I will continue on trying to fix this. Seems like downgrading to 3.X.X is the only solution atm.

**Comment by IceBotYT** [comment]
I found the solution! Apparently the issue was the lights involved with the issues had bad connection, so I did the following:

1. Go to the offending device.
2. Click the edit icon in the top right corner
3. Scroll down and click "remove device"
4. Choose "disconnect & wipe data"
5. Choose confirm
6. Set up the light as new but with a different Wi-Fi network
