### ISSUE TITLE
Can't add Antela socket - other Tuya/Smart Life sockets working fine

### ISSUE THREAD

**Issue by ant-thomas** [rospogrigio/localtuya#1140]
I’ve got two different types of smart/energy monitoring sockets that work with the Tuya/Smart Life app - 4 of each.

All 8 work with the standard Tuya integration but I’d like to use them with LocalTuya.

4 of them work fine and I’m using them via LocalTuya rather than the standard Tuya integration.
4 of them won’t add

The 4 I have an issue with show up as different types of sockets to the working 4 in the Smart Life app. They appear as “Antela” sockets. I’ve got the Local Keys and Device IDs, LocalTuya can see them, just can’t add them.

Any ideas how to get the “Antela” sockets added to LocalTuya?

I get the following errors in the log

```
2022-11-20 20:11:02.579 ERROR (MainThread) [custom_components.localtuya.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 580, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 245, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 704, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.156', 6668)
```

And the following in the UI

![image](https://user-images.githubusercontent.com/1029851/203440641-1b7d97e9-f2ca-461d-9f0d-e0aabf7edd41.png)

**Comment by ant-thomas** [comment]
24 hours turned off seems to have fixed this. 
Sockets added first time when powered up again.

**Comment by fuchsi3010** [comment]
thank you! 
i've had the same in my logs ( `OSError: [Errno 113] Connect call failed` ) and after doing as you suggested i successfully connected to local tuya.
