### ISSUE TITLE
Hello i have this problem

### ISSUE THREAD

**Issue by oomichalekoo** [rospogrigio/localtuya#1149]
`This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya integration (documentation, issues)
First occurred: 23:12:30 (15 occurrences)
Last logged: 23:26:30

[340...cd3] Connect to 192.168.1.180 failed
Traceback (most recent call last):
  File "/data/data/pl.sviete.dom/files/home/AIS/custom_components/localtuya/common.py", line 145, in _make_connection
    self._interface = await pytuya.connect(
  File "/data/data/pl.sviete.dom/files/home/AIS/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/data/data/pl.sviete.dom/files/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/data/data/pl.sviete.dom/files/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/data/data/pl.sviete.dom/files/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/data/data/pl.sviete.dom/files/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/data/data/pl.sviete.dom/files/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.180', 6668)
   `

**Comment by NeoFax75** [comment]
I have the same problem:

`This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:704
Integration: LocalTuya (documentation, issues)
First occurred: 09:39:15 (5 occurrences)
Last logged: 09:43:15

[eb2...hbz] Connect to 192.168.1.173 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 186, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 704, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.173', 6668)
`

**Comment by tbialy2** [comment]
Hi,
I have the same problem. I had to add a new integration configuration (with different api_key etc) inside "LocalTuya integration" and now I have a problem with the stability of both. Randomly, devices from one pool or the other are unavailable. When I do "Read configuration again", in the integration definition tab, everything works fine but not for long.
In the case of one integration under "LocalTuya integration" there were no problems. Now I have a mistake like colleagues, that is

```
"...
 File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
      raise OSError(err, f'Connect call failed {address}')
 OSError: [Errno 113] Connect call failed ('192.168.2.130', 6668)" .
 
```

I think it might be a problem reading current connection (integration) context information for devices.

**Comment by tivoo** [comment]
Same issue here on Home Assistant 2023.3.3
