### ISSUE TITLE
Cannot add smart bulb Topstar-KJDS-A60-RGBCW-01

### ISSUE THREAD

**Issue by archit3kt** [rospogrigio/localtuya#1159]
Hello,

first thank you for the amazing extension, it works great with my konyks plug and gosund smart power strip p1 !

I bought some e27 smart bulb from topstar working great on tuya smart, trying to integrate them to HA

I've got this error message while trying to add these : 

> Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists.

I had this error before for Konyks and gosund, had to close th Tuya smart app to get through these, but this time it seems it didn't do the trick

Here are the debug logs

`2022-12-01 12:02:55.293 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Waiting for sequence number -100
2022-12-01 12:02:55.298 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:02:55.299 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got heartbeat response
2022-12-01 12:02:55.299 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {}
2022-12-01 12:02:55.731 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00^\x12\x00\x00\x00\x01\xf4\x1d\xc2R\x15\xe3\x84wX\xc6\x1d"\xd2\xe0WF\xf9\xe8\xcf\xd2\xea\x94\xd52\x11\xde\xc9*x\x0e\xa7\xa5\xcbfmX\xd9\xef\xc3\xd1\x95\x07Y\x0eI\x8c\xe8:\xa6\xd6\x1bb\x11s\xbe\x88m\x92\x0fa\xdcXQ\xc9\xcf?1k\x9a\xd0\x82T2\x9f\xa9\xac\x80Bn[', crc=1877609021)
2022-12-01 12:02:55.731 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got status update
2022-12-01 12:02:55.731 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {"devId":"075060364855195e362c","dps":{"18":145,"19":322},"t":1669892574}
2022-12-01 12:02:56.495 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00V\xb6\x00\x00\x00\x01\x19\xc3\xd0\xc9\x93g\xe6\xba[\xa39\x88\x84\xbb\xfa\xb4\x06\x19\xf9r\xe1\xf4,\xf9\xb0\xbc\xd5\xc1N\x8e\xf8\x1eBsw}sg\xfa\xcdj\x05\xacZ\x15\xc2\x94\xc8l\xfa(\x12}\x80#\x04\x9f\xff\x00\x969\x9ai\xb4Q\x15\x03\tAH~\x848\xa0\xc8\xe2"4\xda>', crc=1355259460)
2022-12-01 12:02:56.495 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Got status update
2022-12-01 12:02:56.496 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Decrypted payload: {"devId":"075060364855195e38b3","dps":{"19":190},"t":1669892576}
2022-12-01 12:02:57.095 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf4...f6h] Sending command status (device type: type_0a)
2022-12-01 12:02:57.096 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf4...f6h] Send payload: b'{"gwId":"bf4a518d2523079f83sf6h","devId":"bf4a518d2523079f83sf6h"}'
2022-12-01 12:02:57.098 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf4...f6h] Waiting for sequence number 0
2022-12-01 12:02:57.203 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf4...f6h] Connection lost: None
2022-12-01 12:03:01.563 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:01.563 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Send payload: b'{}'
2022-12-01 12:03:01.565 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Waiting for sequence number -100
2022-12-01 12:03:01.613 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:01.613 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Got heartbeat response
2022-12-01 12:03:01.615 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Decrypted payload: {}
2022-12-01 12:03:01.775 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00^\x13\x00\x00\x00\x01\xf4\x1d\xc2R\x15\xe3\x84wX\xc6\x1d"\xd2\xe0WF\xf9\xe8\xcf\xd2\xea\x94\xd52\x11\xde\xc9*x\x0e\xa7\xa5+\xcb\x8b!.\xe4\x8el\x1aQ\x92\x15A(\x7f\xdaR}l\rM\x1a\x89]\x88\xda\x03\xe3wG\x06\x05\xbc\xb3\xd8\x12\x9f\x8e\xedPC\xdaA\xa2\xf9\x99\xaeZ\xc0h\xb5g\xf9\x1a\x90\xe3@\xe9z+\x1di\xa95', crc=283469624)
2022-12-01 12:03:01.775 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got status update
2022-12-01 12:03:01.777 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {"devId":"075060364855195e362c","dps":{"18":201,"19":448,"20":2218},"t":1669892581}
2022-12-01 12:03:02.100 ERROR (MainThread) [custom_components.localtuya.pytuya] [bf4...f6h] Failed to get status: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 574, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 507, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2022-12-01 12:03:02.105 DEBUG (MainThread) [custom_components.localtuya.config_flow] Initial state update failed, trying reset command
2022-12-01 12:03:02.105 DEBUG (MainThread) [custom_components.localtuya.config_flow] No DPS able to be detected
2022-12-01 12:03:02.105 DEBUG (MainThread) [custom_components.localtuya.config_flow] Detected DPS: {}
2022-12-01 12:03:02.106 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf4...f6h] Closing connection
2022-12-01 12:03:02.527 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00V\xb7\x00\x00\x00\x01\x19\xc3\xd0\xc9\x93g\xe6\xba[\xa39\x88\x84\xbb\xfa\xb4\x06\x19\xf9r\xe1\xf4,\xf9\xb0\xbc\xd5\xc1N\x8e\xf8\x1e4`\xfa\xe9\x9e$q\x98\xf9\x8cl\x19\xa6\xa5W\x16\xde\x0c\x97\x07\x9a\xb4\xf0V\xc9\x95w\xff\xfc\x80\x8c\xb4\x9e\x05yC\xf0\x91k\x8c\xcds(^\xdf\xe0\xb8\xde\xa3\xf4\x0c\xb4\xe8,HZA\x9dH\xe7m\x85\xc6\xa1', crc=3900386951)
2022-12-01 12:03:02.528 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Got status update
2022-12-01 12:03:02.530 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Decrypted payload: {"devId":"075060364855195e38b3","dps":{"18":83,"19":186,"20":2220},"t":1669892582}
2022-12-01 12:03:04.686 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:04.686 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Send payload: b'{}'
2022-12-01 12:03:04.687 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Waiting for sequence number -100
2022-12-01 12:03:04.694 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:04.694 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Got heartbeat response
2022-12-01 12:03:04.694 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Decrypted payload: {}
2022-12-01 12:03:05.301 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:05.301 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Send payload: b'{}'
2022-12-01 12:03:05.303 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Waiting for sequence number -100
2022-12-01 12:03:05.309 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:05.309 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got heartbeat response
2022-12-01 12:03:05.309 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {}
2022-12-01 12:03:07.811 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00^\x14\x00\x00\x00\x01\xf4\x1d\xc2R\x15\xe3\x84wX\xc6\x1d"\xd2\xe0WF\xf9\xe8\xcf\xd2\xea\x94\xd52\x11\xde\xc9*x\x0e\xa7\xa5\xfb,m\xc1&\xfd\xa0\x13u\xdaC&\xd9\x11\xf4\xf4V\xaf\xa6\x9a\xbe\x0b\x90y\x08\xe2kA?\xbfu\xd5\x10a\xa7\x80\xbd{\xb6^;.cnkg\x03\t\x1b\xfd\x01c\x85\x00r\x81\x9c\x93x\xe8U\xa8\xa6q', crc=1577673159)
2022-12-01 12:03:07.811 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got status update
2022-12-01 12:03:07.813 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {"devId":"075060364855195e362c","dps":{"18":146,"19":323,"20":2211},"t":1669892587}
2022-12-01 12:03:08.568 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b"3.3\x00\x00\x00\x00\x00\x00V\xb8\x00\x00\x00\x01\x19\xc3\xd0\xc9\x93g\xe6\xba[\xa39\x88\x84\xbb\xfa\xb4\x06\x19\xf9r\xe1\xf4,\xf9\xb0\xbc\xd5\xc1N\x8e\xf8\x1e\xcb}\x1fR\xb3\xd8\xfd\x16&\xfc\x93!\x8b\xf2\x91\xdd\n \xda\xf7\xdb\xbb]\x02\x1bB/\xf9\x02\xd5\x9e9\xfaCg\xc0UM\xff\xc9\xee\xe9\x8b\xef\x15'\x9d>\x99V\xbc\xba \xba\x17\xac\x7f\x9a\xf9\x02c\x8b\x83\x13", crc=1560040080)
2022-12-01 12:03:08.568 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Got status update
2022-12-01 12:03:08.571 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Decrypted payload: {"devId":"075060364855195e38b3","dps":{"18":85,"19":190,"20":2213},"t":1669892588}
2022-12-01 12:03:11.616 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:11.617 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Send payload: b'{}'
2022-12-01 12:03:11.619 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Waiting for sequence number -100
2022-12-01 12:03:11.633 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:11.633 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Got heartbeat response
2022-12-01 12:03:11.634 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Decrypted payload: {}
2022-12-01 12:03:13.851 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00^\x15\x00\x00\x00\x01\xf4\x1d\xc2R\x15\xe3\x84wX\xc6\x1d"\xd2\xe0WF\xf9\xe8\xcf\xd2\xea\x94\xd52\x11\xde\xc9*x\x0e\xa7\xa5\xcbfmX\xd9\xef\xc3\xd1\x95\x07Y\x0eI\x8c\xe8:}`\xe1QI\xac\x12\x81?|\x07\x85\xc0\x17\xa3\xf0\xbc\xb3\xd8\x12\x9f\x8e\xedPC\xdaA\xa2\xf9\x99\xaeZ\xe8R\xbd%x\xa0\xeb\xb7\xaf\xa3E\x0c\xd2\xb3=\x9f', crc=610879108)
2022-12-01 12:03:13.852 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got status update
2022-12-01 12:03:13.853 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {"devId":"075060364855195e362c","dps":{"18":145,"19":322,"20":2218},"t":1669892593}
2022-12-01 12:03:14.607 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00V\xb9\x00\x00\x00\x01\x19\xc3\xd0\xc9\x93g\xe6\xba[\xa39\x88\x84\xbb\xfa\xb4\x06\x19\xf9r\xe1\xf4,\xf9\xb0\xbc\xd5\xc1N\x8e\xf8\x1eF\x06"\x0f\xdfh\xc0[\xc4\xd4\xd7\xf1\xb0\xf5bm\xed\x95\xa4\x97\x0c\xb0\xd2P\xd3@\xd3RWP\xc9\x98\xc4\x89~\x98\x1bN\x1b\xbd\x02\tl\xa6F8\x8f}', crc=1922461893)
2022-12-01 12:03:14.607 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Got status update
2022-12-01 12:03:14.608 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Decrypted payload: {"devId":"075060364855195e38b3","dps":{"20":2220},"t":1669892594}
2022-12-01 12:03:14.696 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:14.696 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Send payload: b'{}'
2022-12-01 12:03:14.699 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Waiting for sequence number -100
2022-12-01 12:03:14.707 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:14.707 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Got heartbeat response
2022-12-01 12:03:14.707 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Decrypted payload: {}
2022-12-01 12:03:15.311 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:15.311 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Send payload: b'{}'
2022-12-01 12:03:15.313 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Waiting for sequence number -100
2022-12-01 12:03:15.320 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:15.320 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got heartbeat response
2022-12-01 12:03:15.320 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {}
2022-12-01 12:03:19.891 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00^\x16\x00\x00\x00\x01\xf4\x1d\xc2R\x15\xe3\x84wX\xc6\x1d"\xd2\xe0WF\xf9\xe8\xcf\xd2\xea\x94\xd52\x11\xde\xc9*x\x0e\xa7\xa5\xfb,m\xc1&\xfd\xa0\x13u\xdaC&\xd9\x11\xf4\xf4\x06\xce\xe90\x18\xd2\x08\x9d\x85\x0c\xbd\x8c\xeb\x9cJ7\x10a\xa7\x80\xbd{\xb6^;.cnkg\x03\t%Yz\xab\xbe\x11o\x13\xacG\x07\xddO\xac\xe8m', crc=3435136111)
2022-12-01 12:03:19.891 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got status update
2022-12-01 12:03:19.893 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {"devId":"075060364855195e362c","dps":{"18":146,"19":324,"20":2211},"t":1669892599}
2022-12-01 12:03:20.647 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00V\xba\x00\x00\x00\x01\x19\xc3\xd0\xc9\x93g\xe6\xba[\xa39\x88\x84\xbb\xfa\xb4\x06\x19\xf9r\xe1\xf4,\xf9\xb0\xbc\xd5\xc1N\x8e\xf8\x1e\xa4^,\x0f18I\xf8T.\xeeJ+$\x00\xe5\xf4T\xdd\x1cT\x01\xefJ.\xd5\x03*\x80\xe8\xb572\xa2\r\xb6\x83j\xb9\xed\x93r\x11\xa4\xc9\xd2\x82}', crc=617924439)
2022-12-01 12:03:20.647 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Got status update
2022-12-01 12:03:20.648 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Decrypted payload: {"devId":"075060364855195e38b3","dps":{"19":188,"20":2211},"t":1669892600}
2022-12-01 12:03:21.635 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:21.636 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Send payload: b'{}'
2022-12-01 12:03:21.640 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Waiting for sequence number -100
2022-12-01 12:03:21.668 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:21.668 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Got heartbeat response
2022-12-01 12:03:21.668 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Decrypted payload: {}
2022-12-01 12:03:24.709 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:24.710 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Send payload: b'{}'
2022-12-01 12:03:24.711 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Waiting for sequence number -100
2022-12-01 12:03:24.717 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:24.718 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Got heartbeat response
2022-12-01 12:03:24.718 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Decrypted payload: {}
2022-12-01 12:03:25.322 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:25.322 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Send payload: b'{}'
2022-12-01 12:03:25.325 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Waiting for sequence number -100
2022-12-01 12:03:25.330 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:25.330 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got heartbeat response
2022-12-01 12:03:25.331 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {}
2022-12-01 12:03:25.930 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00^\x17\x00\x00\x00\x01\xf4\x1d\xc2R\x15\xe3\x84wX\xc6\x1d"\xd2\xe0WF\xf9\xe8\xcf\xd2\xea\x94\xd52\x11\xde\xc9*x\x0e\xa7\xa5\x04Y\xbd\xeb\x0ex\xe5\x820\x90$Tt\x94\x91\x07u\x88v\xed\x8c\xb4\xbc\x17\x0b\xec\xd6\x0f\xa4\xca5\xb2\x8f\xa8\x91\x9d\xb1\x1aT2\xfdSs\xf87\xcf\x0c+){\x85\xeb\xc8\x1a\xbd\xa2\xc4\xac[7\xd6\xa9\xf0\x1f', crc=276171969)
2022-12-01 12:03:25.931 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got status update
2022-12-01 12:03:25.932 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {"devId":"075060364855195e362c","dps":{"18":143,"19":319,"20":2220},"t":1669892605}
2022-12-01 12:03:26.687 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00V\xbb\x00\x00\x00\x01\x19\xc3\xd0\xc9\x93g\xe6\xba[\xa39\x88\x84\xbb\xfa\xb4\x06\x19\xf9r\xe1\xf4,\xf9\xb0\xbc\xd5\xc1N\x8e\xf8\x1e\xf6x\x9c\xb1\x0bNk\x0bv\xcf\n\xc1\xdd\xa04&YA\x81\xc1\x17\x84\xdc\x084\xb9\x81\x1f\x10\xe3pX\xcb\xbf\xa1_(\xf9\x15\x87\xea\xa8wk\xcfb5\xd8', crc=3601215052)
2022-12-01 12:03:26.688 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Got status update
2022-12-01 12:03:26.689 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Decrypted payload: {"devId":"075060364855195e38b3","dps":{"19":190,"20":2223},"t":1669892606}
2022-12-01 12:03:31.669 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:31.669 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Send payload: b'{}'
2022-12-01 12:03:31.672 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Waiting for sequence number -100
2022-12-01 12:03:31.708 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:31.708 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Got heartbeat response
2022-12-01 12:03:31.709 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf7...aor] Decrypted payload: {}
2022-12-01 12:03:31.975 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00^\x18\x00\x00\x00\x01\xf4\x1d\xc2R\x15\xe3\x84wX\xc6\x1d"\xd2\xe0WF\xf9\xe8\xcf\xd2\xea\x94\xd52\x11\xde\xc9*x\x0e\xa7\xa5A\xe6\xcb*<\x05\xd3K(\xe6\xf3\x1c5\x8e\xd1qb\x00~\xebh\x0f8\xd3\xab3W\xf7\x04\x80\xca\xb0T\xa5?\x18\x02\x86\x12\x8f\x1dH\xc9;(\xcb}\xba>\x99Wu\x82[AG"\x0b\xdcE21M1', crc=2825995321)
2022-12-01 12:03:31.975 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got status update
2022-12-01 12:03:31.977 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {"devId":"075060364855195e362c","dps":{"18":142,"19":318,"20":2225},"t":1669892611}
2022-12-01 12:03:32.727 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00V\xbc\x00\x00\x00\x01\x19\xc3\xd0\xc9\x93g\xe6\xba[\xa39\x88\x84\xbb\xfa\xb4\x06\x19\xf9r\xe1\xf4,\xf9\xb0\xbc\xd5\xc1N\x8e\xf8\x1e\x1c\xc2xC\xe9\xc9Rj\xeb\x86\x86\xae\x13\x9d~J\xcf\x86X\x19\x143\xa6v?\x15\xd3\xc4.h\xb4\x01j,\xdc/\xbf\\V\xbd\xd8c\x7f\x9e\xd6\xcd\xce\xa4', crc=1365280516)
2022-12-01 12:03:32.727 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Got status update
2022-12-01 12:03:32.729 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Decrypted payload: {"devId":"075060364855195e38b3","dps":{"19":191,"20":2225},"t":1669892612}
2022-12-01 12:03:34.720 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:34.720 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Send payload: b'{}'
2022-12-01 12:03:34.723 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Waiting for sequence number -100
2022-12-01 12:03:34.729 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:34.730 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Got heartbeat response
2022-12-01 12:03:34.730 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...8b3] Decrypted payload: {}
2022-12-01 12:03:35.333 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Sending command heartbeat (device type: type_0a)
2022-12-01 12:03:35.334 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Send payload: b'{}'
2022-12-01 12:03:35.335 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Waiting for sequence number -100
2022-12-01 12:03:35.495 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2022-12-01 12:03:35.495 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got heartbeat response
2022-12-01 12:03:35.496 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Decrypted payload: {}
2022-12-01 12:03:38.015 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00^\x19\x00\x00\x00\x01\xf4\x1d\xc2R\x15\xe3\x84wX\xc6\x1d"\xd2\xe0WF\xf9\xe8\xcf\xd2\xea\x94\xd52\x11\xde\xc9*x\x0e\xa7\xa5\xb1\x1f\xc0\x19QC\xdc\x8b\xfd@\'\xf8n #\xfef\xc9G\xbe\xe5\x9f\xb9\x15\xf2[\xb2g/E\xcf\x88\xf3\xc9o\x90\x904\xbe$\xab\x05\xf4TGK\xc1\xb3\x06\x9cn\x88N\xefO\xf0\x80lzSZ\xb0\xe2A', crc=3270447265)
2022-12-01 12:03:38.016 DEBUG (MainThread) [custom_components.localtuya.pytuya] [075...62c] Got status update
`

Thank you for your help !

**Comment by 3DVN** [comment]
Having the same issue with a new pack of SmartLife-branded E12 bulbs.
