### ISSUE TITLE
Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists.

### ISSUE THREAD

**Issue by zhuguoqing123** [rospogrigio/localtuya#1161]
![微信截图_20221205225427](https://user-images.githubusercontent.com/96900868/205678000-6e994010-9eb7-42e9-84e6-4707286fe7be.png)

**Comment by SectorHA** [comment]
+1

**Comment by xLOG-DOGx** [comment]
+1

**Comment by Koubi4cK** [comment]
+1

**Comment by strk90** [comment]
![Bug](https://user-images.githubusercontent.com/119970190/206152639-f2030c8e-aac3-4098-bd6e-6225cf9cfbe4.PNG)
Who can help?

**Comment by Koubi4cK** [comment]
I was able to make my switch to work again by using the fork mentionned in [#1065 ](https://github.com/rospogrigio/localtuya/issues/1065#issuecomment-1304829471) and using protocol 3.4

**Comment by tk627** [comment]
I have the same issue with Countdown Fans
This error originated from a custom integration.

Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:259
Integration: LocalTuya (documentation, issues)
First occurred: 5:15:21 PM (2 occurrences)
Last logged: 5:15:57 PM

[ebd...nid] Failed to get status:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 574, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 507, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by tk627** [comment]
I tried with both 3.1 and 3.3

**Comment by strk90** [comment]
> I was able to make my switch to work again by using the fork mentionned in [#1065 ](https://github.com/rospogrigio/localtuya/issues/1065#issuecomment-1304829471) and using protocol 3.4

Thanks, this works for me too.

**Comment by plandregan** [comment]
Protocol 3.4 needed for many devices now

**Comment by Morpheus2018** [comment]
> I was able to make my switch to work again by using the fork mentionned in [#1065 ](https://github.com/rospogrigio/localtuya/issues/1065#issuecomment-1304829471) and using protocol 3.4

It doesn't work with 3.4 either.
![Pi-Firmware-3 4](https://user-images.githubusercontent.com/37088587/207841429-e6eb0eaa-ad36-4597-9fc9-20ded3ab2f11.png)

With my old system, everything remained in order.
![pc-Firmware-3 3](https://user-images.githubusercontent.com/37088587/207842640-ec82aa9f-937c-4eb3-9eb4-eedde1387c52.png)

New installation + backup on a raspberrypi3+ no longer works.
![Pi-Firmware-3 3](https://user-images.githubusercontent.com/37088587/207842884-56a97dd2-a558-4f89-8b55-c9c19ad83c6e.png)

**Comment by sezlony** [comment]
facing the same issue, can't configure tuya device because of this "no datapoints found" error 😢

**Comment by Morpheus2018** [comment]
> With my old system, everything remained in order. 

@https://github.com/rospogrigio/localtuya/issues/1065#issuecomment-1356244959

**Comment by sezlony** [comment]
> > facing the same issue, can't configure tuya device because of this "no datapoints found" error cry
> 
> Maybe this helps!? @[#1065 (comment)](https://github.com/rospogrigio/localtuya/issues/1065#issuecomment-1356244959)

don't understand a word of that...

either they update this integration to handle 3.4 or tuya is a bummer for me

**Comment by donburch888** [comment]
+1 for original post. 

This is a device which has previously been working correctly.  I relocated it at did the factory reset to attach it via a different Wi-Fi network.  It is showing on my LAN, and can operate it in the Arlec/Grid Connect version of Tuya app.  I have not tried to update the device's firmware (I believe it is latest anyway). 

In Home Assistant I have deleted the old device, restarted the LocalTuya integration and rebooted the HA machine.

When adding as a new device I am only given options for 3.1 and 3.3 - and still get this error.

**Comment by donburch888** [comment]
Nope :-(

Reset everything, added the PC191HA to Tuya app (not the grid Connect version), still wont add in LocalTuya. 

Inspiration ... back to Tuya website and, yes, _**the local_key has changed**_.  Using the new local_key it works smoothly.  No idea at which point the local_key was changed.

**Comment by plandregan** [comment]
The local key changes each time its re paired
