### ISSUE TITLE
Issue adding Smart On/Off CB2S Switch

### ISSUE THREAD

**Issue by nordpol18** [rospogrigio/localtuya#1180]
Error "Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists." while trying to add Smart On/Off CB2S Switch.

`2022-12-16 16:55:47.535 ERROR (MainThread) [custom_components.localtuya.pytuya] [bfd...pbr] Failed to get status: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 574, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 507, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2022-12-16 16:57:13.953 ERROR (MainThread) [custom_components.localtuya.pytuya] [bfd...pbr] Failed to get status: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 574, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 507, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2022-12-16 16:58:03.187 ERROR (MainThread) [custom_components.localtuya.pytuya] [bfd...pbr] Failed to get status: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 574, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 507, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2022-12-16 17:00:15.082 ERROR (MainThread) [custom_components.localtuya.pytuya] [bff...048] Failed to get status: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 574, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 507, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError`

**Comment by villar3** [comment]
hi,

I have the same issue with an other "smart switch".

an extract of json file:
`"updated_at": "1667532703690",
    "cloud_devices": {
      "bffe384f704f790d6ermp7": {
        "active_time": 1671737532,
        "biz_type": 18,
        "category": "tdq",
        "create_time": 1671737532,
        "icon": "smart/icon/ay1531122507771gALCb/1652666052356fa71002b.png",
        "id": "bffe384f704f790d6ermp7",
        "ip": "86.194.137.60",
        "lat": "44.3273",
        "local_key": "d0f...2dd",
        "lon": "4.6165",
        "model": "CB2S",
        "name": "Smart Swith",
        "online": true,
        "owner_id": "60110200",
        "product_id": "q5f6ge6b7w9katle",
        "product_name": "Smart Swith",
        "status": [
          {
            "code": "switch_1",
            "value": false
          },
          {
            "code": "countdown_1",
            "value": 0
          },
          {
            "code": "relay_status",
            "value": "2"
          },
          {
            "code": "random_time",
            "value": ""
          },
          {
            "code": "cycle_time",
            "value": ""
          },
          {
            "code": "switch_inching",
            "value": "AAAC"
          }
        ],
        "sub": false,
        "time_zone": "+01:00",
        "uid": "eu16565183116714IZHg",
        "update_time": 1671737534,
        "uuid": "3767d720d3553f43"
      },
`
