### ISSUE TITLE
After upgrade to HA 2022.12 integration appears to have broken

### ISSUE THREAD

**Issue by bwims** [rospogrigio/localtuya#1214]
## The problem

I had an immersion heater configured and working on Local Tuya under HA 2022.10 .   Today I updated to 2022.12 to enable an upgrade to a different package, after which the Local Tuya integration lost all references to device and the "CONFIGURE" button disappeared (see screenshots)

![image](https://user-images.githubusercontent.com/18516073/210578035-08cbd545-5bf2-42b6-9855-d53ba4650586.png)
![image](https://user-images.githubusercontent.com/18516073/210578126-c22b82c7-71c4-4c85-8aad-9ecd01a94086.png)

## Environment

- Localtuya version:   4.1.1
- Last working localtuya version (if known and relevant):  4.1.1
- Home Assistant Core version:   2022.12.9
- [x] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Stop HA 2022.10 in docker
2. Edit Docker config to load version 2022.12
3. Restart HA container

## Configuration `configuration.yaml` or `config_flow`

```yaml

I'm sorry, I need some help finding this.  There is nothing in configuration.yaml about the device in question, and the only config_flow file I could find was a .py file.
```

## DP dump

I don't really understand any of this, and will need some help decoding it.

## Provide Home Assistant taceback/logs

```txt
2023-01-04 14:23:40.776 DEBUG (SyncWorker_1) [tuya_iot] Request: method = POST, url = https://openapi.tuyaeu.com/v1.0/iot-01/associated-users/actions/authorized-login, params = None, body = {'username': 'br.wims@gmail.com', 'password': '***', 'country_code': '44', 'schema': 'tuyaSmart'}, t = 1672842220776
2023-01-04 14:23:41.035 DEBUG (SyncWorker_1) [tuya_iot] Response: {
"result": {
"access_token": "***",
"expire_time": 7200,
"platform_url": "https://openapi.tuyaeu.com",
"refresh_token": "***",
"uid": "***"
},
"success": true,
"t": 1672842220468,
"tid": "629fb03e8c3b11ed817f5a5f1d3b12c7"
}
2023-01-04 14:23:41.068 DEBUG (MainThread) [tuya_iot] start
2023-01-04 14:23:41.070 DEBUG (Thread-4) [tuya_iot] Request: method = POST, url = https://openapi.tuyaeu.com/v1.0/open-hub/access/config, params = None, body = {'uid': '***', 'link_id': '***', 'link_type': 'mqtt', 'topics': 'device', 'msg_encrypted_version': '1.0'}, t = 1672842221070
2023-01-04 14:23:41.072 DEBUG (SyncWorker_10) [tuya_iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/users/eu16694629976658GiOX/devices, params = None, body = None, t = 1672842221072
2023-01-04 14:23:41.145 DEBUG (Thread-4) [tuya_iot] Response: {
"code": 28841002,
"msg": "No permissions. Your subscription to cloud development plan has expired.",
"success": false,
"t": 1672842220579,
"tid": "62b914c78c3b11ed84f4f6d732894979"
}
2023-01-04 14:23:41.146 ERROR (Thread-4) [tuya_iot] error while get mqtt config
2023-01-04 14:23:41.154 ERROR (Thread-4) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 161, in run
time.sleep(self.mq_config.expire_time - 60)
AttributeError: 'NoneType' object has no attribute 'expire_time'
2023-01-04 14:23:41.261 DEBUG (SyncWorker_10) [tuya_iot] Response: {
"code": 28841002,
"msg": "No permissions. Your subscription to cloud development plan has expired.",
"success": false,
"t": 1672842220691,
"tid": "62c9955a8c3b11ed9155f6a8c25a9394"
}
2023-01-04 14:23:41.393 DEBUG (SyncWorker_6) [tuya_iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/users/eu16694629976658GiOX/homes, params = None, body = None, t = 1672842221393
2023-01-04 14:23:41.464 DEBUG (SyncWorker_6) [tuya_iot] Response: {
"code": 28841002,
"msg": "No permissions. Your subscription to cloud development plan has expired.",
"success": false,
"t": 1672842220891,
"tid": "62e8c6108c3b11ed84f4f6d732894979"
}
```
## Additional information
I see after adding the debug information that my cloud development plan has expired!

Why should this be?  I'm sure I followed all the necessary instructions.  Also it was working up until I upgraded Home Assistant.
I have increased the trial period, but it is currently "under review".

However, I have rebooted and am no longer seeing the above debug code, yet the device has not reappeared, so I am at a loss!

Thanks!

**Comment by bwims** [comment]
Also found the following in logs

```
2023-01-04 15:08:41.733 ERROR (Thread-4) [tuya_iot] error while get mqtt config
2023-01-04 15:08:41.758 ERROR (Thread-4) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 161, in run
time.sleep(self.mq_config.expire_time - 60)
AttributeError: 'NoneType' object has no attribute 'expire_time'
```

**Comment by bwims** [comment]
Sorry to have raised this.   I think whoever is in charge of the Tuya documentation for HA should raise awareness, in **_big bold letters_** that IoT Core Trial subscriptions expire without any warning, so calendar warnings should be set up by the user.

I have extended my trial by 6 months.   Tuya engineers sent the following screenshots, FYI.

![image](https://user-images.githubusercontent.com/18516073/210764468-262d0c2a-c661-4b62-831a-c53cd67c905c.png)

![image](https://user-images.githubusercontent.com/18516073/210764505-f6e4d3fa-4ad2-4c63-b49c-31f8c1a93280.png)

![image](https://user-images.githubusercontent.com/18516073/210764537-20e370d0-ae1a-4520-97bf-8c909eea1cc3.png)
