### ISSUE TITLE
Unknown error adding new device

### ISSUE THREAD

**Issue by kevvar** [rospogrigio/localtuya#1242]
Hello!

I was trying to connect [this device](https://www.amazon.com/dp/B08R1G1Y8N/ref=twister_B09H5HRXKV?_encoding=UTF8&th=1), but the addon show me the next issue, does anyone know what is happening?

```
Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:1163
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 3:56:18 p. m. (1 occurrences)
Last logged: 3:56:18 p. m.

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 581, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 240, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1163, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.3.209', 6668)
```
![image](https://user-images.githubusercontent.com/70792969/212498944-313af0b4-44f5-4e86-820b-0e571d2576da.png)

**Comment by orandaadnaro** [comment]
I'm new to adding devices and I've the same issue. Can you explain how you went about activating the debug logs

**Comment by kevvar** [comment]
> I'm new to adding devices and I've the same issue. Can you explain how you went about activating the debug logs

When you are looking for your devices check the box bellow the protocol selection, and add the code from the documentation to your config.yaml

**Comment by orandaadnaro** [comment]
Thanks. I did that, sofas not change, although my three sensors which were listed before, disappeared from the add device list. When I added one device and after it failed it was in the device list.

I'll keep trying. Perhaps like in 'The IT Office' a switch off and on reboot might fix it :-)

**Comment by kunegun** [comment]
I have the same problem, I can´t add any device

**Comment by Zodiac-69** [comment]
I no longer have access to any of my Tuya devices after upgrade.
All devices are "Gray".
This happened after i added a new device, 3.4 protocol, and i now have the same "Fail to set up.
The new device shows the product ID, but indicate that this device has no entities after TuyaLocal indicated that device, RGBCW lamp was added successfully. 

`Logger: homeassistant
Source: custom_components/localtuya/common.py:126
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 19:15:18 (413 occurrences)
Last logged: 19:26:44
Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
    self.device_found(decoded)
  File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
    self._callback(device)
  File "/config/custom_components/localtuya/__init__.py", line 105, in _device_discovered
    entry = async_config_entry_by_device_id(hass, device_id)
  File "/config/custom_components/localtuya/common.py", line 126, in async_config_entry_by_device_id
    if device_id in entry.data[CONF_DEVICES]:
KeyError: 'devices'`

**Comment by Zodiac-69** [comment]
I rolled back my HA to a backup i made before upgrading, and all my devices are now back online and no errors.

**Comment by granthamana** [comment]
I had this error -  @ladykira2022's solution fixed it for me:

https://github.com/rospogrigio/localtuya/issues/974#issuecomment-1356723916
