### ISSUE TITLE
Feature request - Disable Entitie

### ISSUE THREAD

**Issue by marc3k18** [rospogrigio/localtuya#1250]
Add option to disable an entitie.

Ex: Christmas Light

Because the system generate error log when it cant connect to a device

**Comment by marc3k18** [comment]
Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:1163
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: January 17, 2023 at 10:01:49 PM (3666 occurrences)
Last logged: 8:12:02 AM

[ebc...x39] Connect to 10.18.0.114 failed
[eb4...g6y] Connect to 10.18.0.115 failed
[eba...iym] Connect to 10.18.0.154 failed
[eb6...tbe] Connect to 10.18.0.130 failed
[eb2...woy] Connect to 10.18.0.193 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 187, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1163, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.18.0.128', 6668)

**Comment by ALERTua** [comment]
Please add this feature. This will be helpful for me also. I disable my air conditioner in winter and floor heater in summer.
Thank you

**Comment by donburch888** [comment]
This has been answered before.  It really is not obvious :-( 

In Settings >  LocalTuya devices, select the device you want to disable. 
Under the "Device Info" heading should be a link to "Download Diagnostics" and a menu button (3 vertical dots). You expect this menu to contain the disable option, but instead it only contains "Delete".  This is not the menu you're looking for. 

Instead, click on "Edit Settings" (the pencil icon in top right of the screen).  This lets you change the name for the device, the Area it is in, and to Enable/disable this device.  This is the switch you're looking for, 
![Screenshot from 2023-02-04 20-38-56](https://user-images.githubusercontent.com/60803198/216760532-fa21cb47-4d3c-4202-a15a-df78db6fa22f.png)
