### ISSUE TITLE
Send updatedps command

### ISSUE THREAD

**Issue by tommicarraro** [rospogrigio/localtuya#1255]
Is there a way to send custom updatedps commands each time that the device status are being updated?

In am in an offline environment, I’m able to switch my plug, but I’m not able to get the attributes to update.

if I run the following code in Python with TinyTuya, also the attributes of the device in LocalTuya and Home Assistant are updated.

``` 
d=tinytuya.OutletDevice(…,…,…)
d.set_version(3.3)
while True:
    d.updatedps([18,19,20])
    sleep(10)
```
    
The code is taken from here: [https://github.com/jasonacox/tinytuya/issues/8](https://github.com/jasonacox/tinytuya/issues/8)

I’m running LocalTuya v.5.0.0 and Home Assistant Core version: 2023.1.5

**Comment by remlei** [comment]
tuya devices are poll based, so you need to pool the device to get updated values on the entity. Also, localtuya can already do this update every X seconds by setting the "Scan Interval" when adding/editing the device, I had a smartplug with power monitoring set to 30 seconds scan interval and that makes it update the Volt, Amp and Voltage values every 30 seconds.

**Comment by tommicarraro** [comment]
This is not working, when I set the "Scan Interval" to whatever value, the device stops responding both if it's connected to internet and also if it's offline, going to a "Not available" status.
I've tried to delete the value in the "Scan Interval" field, but I'm getting an error:
```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
result = await component.async_unload_entry(hass, self)
File "/config/custom_components/localtuya/__init__.py", line 311, in async_unload_entry
await device.close()
File "/config/custom_components/localtuya/common.py", line 308, in close
await self._connect_task
File "/config/custom_components/localtuya/common.py", line 273, in _make_connection
and self._dev_config_entry[CONF_SCAN_INTERVAL] > 0
TypeError: '>' not supported between instances of 'str' and 'int'
```

Here ther's the output from the log in HA of localtuya when I setted the "Scan Interval" to 60 and reloaded LocalTuya:
```
2023-01-24 11:28:14.938 INFO (MainThread) [custom_components.localtuya] Service localtuya.reload called: reloading integration
2023-01-24 11:28:14.957 INFO (MainThread) [custom_components.localtuya] Cloud API account not configured.
2023-01-24 11:28:15.960 DEBUG (MainThread) [custom_components.localtuya.switch] Initialized switch [Sistema]
2023-01-24 11:28:15.961 DEBUG (MainThread) [custom_components.localtuya.switch] Initialized switch [Server]
2023-01-24 11:28:16.187 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Sending command 10 (device type: type_0a)
2023-01-24 11:28:16.188 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Sending payload: b'{"gwId”:”****”,”devId”:”****”,”uid”:”****”,”t”:”1674559696"}'
2023-01-24 11:28:16.193 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Command 10 waiting for sequence number 1
2023-01-24 11:28:16.199 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Dispatching message CMD 10 TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b’****’, crc=2903938890, crc_good=True)
2023-01-24 11:28:16.202 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Deciphered data = '{"dps":{"1":true,"9":0,"17":26,"18":375,"19":565,"20":2265,"21":1,"22":591,"23":31437,"24":18117,"25":1152,"26":0}}'
2023-01-24 11:28:16.203 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Started heartbeat loop
2023-01-24 11:28:16.204 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Sending command 9 (device type: type_0a)
2023-01-24 11:28:16.204 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Sending payload: b'{"gwId”:”***”,”devId”:”***”}’
2023-01-24 11:28:16.206 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Command 9 waiting for sequence number -100
2023-01-24 11:28:16.237 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Dispatching message CMD 9 TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211, crc_good=True)
2023-01-24 11:28:16.237 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Got heartbeat response
2023-01-24 11:28:16.256 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] ACK received for command 9: ignoring it
2023-01-24 11:28:26.257 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Sending command 9 (device type: type_0a)
2023-01-24 11:28:26.258 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Sending payload: b'{"gwId”:”****”,”devId”:”****”}’
2023-01-24 11:28:26.259 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Command 9 waiting for sequence number -100
2023-01-24 11:28:26.294 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Dispatching message CMD 9 TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211, crc_good=True)
2023-01-24 11:28:26.295 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Got heartbeat response
2023-01-24 11:28:26.299 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] ACK received for command 9: ignoring it
2023-01-24 11:28:36.300 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Sending command 9 (device type: type_0a)
2023-01-24 11:28:36.300 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Sending payload: b'{"gwId”:”***”,”devId”:”**”}’
2023-01-24 11:28:36.303 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Command 9 waiting for sequence number -100
2023-01-24 11:28:36.327 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Dispatching message CMD 9 TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211, crc_good=True)
2023-01-24 11:28:36.327 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Got heartbeat response
2023-01-24 11:28:36.328 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] ACK received for command 9: ignoring it
2023-01-24 11:28:46.329 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Sending command 9 (device type: type_0a)
2023-01-24 11:28:46.330 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Sending payload: b'{"gwId”:”****”,”devId”:”***”}’
2023-01-24 11:28:46.334 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Command 9 waiting for sequence number -100
2023-01-24 11:28:46.494 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Dispatching message CMD 8 TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b’3.3\x****’, crc=3106027298, crc_good=True)
2023-01-24 11:28:46.495 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Got status update
2023-01-24 11:28:46.496 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Deciphered data = '{"dps":{"20":2269,"18":419,"19":566},"t":1674559725}'
2023-01-24 11:28:51.336 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Heartbeat failed due to timeout, disconnecting
2023-01-24 11:28:51.339 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bff...lee] Connection lost: None
```

From tinytuya I'm able to get all the informations, and from LocalTuya seems to get only a small part of them:
<img width="952" alt="Schermata 2023-01-24 alle 12 02 57" src="https://user-images.githubusercontent.com/29754175/214275466-c76f7265-4847-4df5-89d5-4e12816352d3.png">

**Comment by sibowler** [comment]
Can you try PR #1273 and see if that assists with this? You will also need to specify all the DPIDs that you want to send in the updatedps (aka RESET) command in the _DPIDs to send in RESET command_ device config.

**Comment by tommicarraro** [comment]
That's is working

**Comment by tommicarraro** [comment]
Closing
