### ISSUE TITLE
Device only works once after restart

### ISSUE THREAD

**Issue by Gonzalo933** [rospogrigio/localtuya#1279]
I have a bunch of wifi thermometers around the house. All of them are TH06WB3S and running Tuya protocol 3.4.

I bought a new device, this one is a TH08CBU it's newer than the other ones and runs on batteries. This one connects using protocol 3.4.

I was able to configure the device properly and it "kinda works". The thermometer sends measurements and are read fine by localtuya. The problem is that it only receives a single measurement and the becomes unavailable until I call the "restart localtuya" service. Once I do that, localtuya receives a single measurement again. So it seems that the first connection after restart works but not subsequent connections attempts.

## Environment

- Localtuya version: 5.0.0
- Home Assistant Core version: 2022.12.8
- [X] Does the device work using the Home Assistant Tuya Cloud component ?
- [?] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? It works if I restart the device
- [] Was the device working with earlier versions of localtuya ? It's a new device.
- [] Are you using the Tuya/SmartLife App in parallel ? App is installed in my phone but closed

**Comment by Gonzalo933** [comment]
I am not able to ping the device from my terminal. The device can only be ping/discovered by tintuya if I restart it by removing the batteries.

**Comment by Gonzalo933** [comment]
Relevant log here:

> 
> ERROR (MainThread) [custom_components.localtuya.common] [eb3...1na] Connect to 192.168.1.15 failed
> Traceback (most recent call last):
>   File "/config/custom_components/localtuya/common.py", line 187, in _make_connection
>     self._interface = await pytuya.connect(
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 1163, in connect
>     _, protocol = await loop.create_connection(
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
>     raise exceptions[0]
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
>     sock = await self._connect_sock(
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
>     await self.sock_connect(sock, address)
>   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
>     return await fut
>   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
>     raise OSError(err, f'Connect call failed {address}')
> OSError: [Errno 113] Connect call failed ('192.168.1.15', 6668)
>

**Comment by Gonzalo933** [comment]
I tried blocking the device from accessing the internet from my router. But there is no way in my router to also block DNS request to 192.168.1.1

**Comment by sibowler** [comment]
Have you tried setting the _Scan Interval_ in the device config? If not, try with something like 30 secs to start off with.

**Comment by SgtJalau** [comment]
Hey, this might be the same issue we are facing with other products becoming unavailable as well. Here is what I did to fix my issue with smart plugs: https://github.com/rospogrigio/localtuya/issues/1116#issuecomment-1427047385
Please confirm whether downgrading helps and for example some settings in the config seem to be off, like scan_interval set to a string.

**Comment by Gonzalo933** [comment]
@sibowler  Yes, I have tried changing the scan interval. Interestingly enough, when I change the scan interval, the device status updates immediately but that's the only update that happens.

@SgtJalau I tried your method, but that localtuya version does not support the 3.4 protocol (that my device uses)

**Comment by Gonzalo933** [comment]
I tired editing the `core.config_entries` file manually and changing the scan_interval from string to int. We will see if it helps
