### ISSUE TITLE
Holgate WX1 - Failed to get DPs

### ISSUE THREAD

**Issue by CloCkWeRX** [rospogrigio/localtuya#1300]
Product:
https://www.holmanindustries.com.au/product/wx1-tap-timer-and-wifi-hub/

I might need to have a bit of a play with other branches implementing sub devices; ie https://github.com/rospogrigio/localtuya/pull/318/commits

## The problem
On adding the device:

```
2023-02-26 15:37:04.291 ERROR (MainThread) [custom_components.localtuya.pytuya] [bff...4qi] Failed to get status: could not decrypt data: wrong local_key?
Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 946, in _decode_payload
    json_payload = json.loads(payload)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 863, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 795, in status
    status = await self.exchange(DP_QUERY)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 780, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 948, in _decode_payload
    raise DecodeError("could not decrypt data: wrong local_key?")
custom_components.localtuya.pytuya.DecodeError: could not decrypt data: wrong local_key?
```

## Environment

- Localtuya version:  
- Home Assistant Core version:  
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

1. Add device via config flow
2. View logs

## Provide Home Assistant traceback/logs

```
put your log output between these markers
```

**Comment by CloCkWeRX** [comment]
Well, it turns out the cloud API doesn't even have labels for these so discovery is not easy.

Tuya cli will discover this by connecting to the device.

For anyone else with this product or an oveseas variant, https://github.com/funtastix/localtuya/pull/1/files is probably of interest
