### ISSUE TITLE
Protocol 3.4 light switch stopped responding

### ISSUE THREAD

**Issue by ScottWoolven5** [rospogrigio/localtuya#1302]
## The problem
I've had two MoesGo light switches installed, one is on protocol 3.3 and the other is on protocol 3.4. Since release 5.0.0 I've been using Local Tuya for both switches and everything has been working normally. I recently added another switch to the network and around the same time, the switch on protocol 3.4 has stopped responding. 

I can still control the light switches via the SmartLife and Alexa apps however if I ask Alexa to turn on the lights, it states that it's unresponsive. 

I've just updated to 5.1.0-beta0 and the problem still exists. 

## Environment
  Running Hassio on a Raspberry Pi 3. 

- Localtuya version: v5.1.0-beta0
- Home Assistant Core version:  Home Assistant 2023.2.5 
                                                   Supervisor 2023.01.1 
                                                   Operating System 9.5 
                                                   Frontend 20230202.0 - latest 
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
 After adding the Tuya Cloud integration, no devices are shown. 
- [?] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [x] Are you using the Tuya/SmartLife App in parallel ? 

## DP dump
I tried to get the DP dump but ran into the following error in cmd: 
```
Traceback (most recent call last):
  File "C:\Users\scott\Desktop\tuyadebug\test.py", line 13, in <module>
    import localtuya
  File "C:\Users\scott\Desktop\tuyadebug\localtuya\__init__.py", line 41, in <module>
    from cryptography.hazmat.backends import default_backend
ModuleNotFoundError: No module named 'cryptography'
```

## Provide Home Assistant traceback/logs

I get a number of local tuya errors and warnings in the logs, pasted in time order. [bfa...k4k] is the switch that is not responding.

```
This error originated from a custom integration.

Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:647
Integration: LocalTuya integration (documentation, issues)
First occurred: 13:05:42 (2 occurrences)
Last logged: 13:05:42

[bf4...n6r] Command 9 timed out waiting for sequence number -100
[bf9...9nw] Command 9 timed out waiting for sequence number -100
```
```
This error originated from a custom integration.

Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:795
Integration: LocalTuya integration (documentation, issues)
First occurred: 12:38:52 (15 occurrences)
Last logged: 13:09:52

[bfa...k4k] Command 3 timed out waiting for sequence number -102
[bfa...k4k] Command 16 timed out waiting for sequence number 2
```

```
This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:259
Integration: LocalTuya integration (documentation, issues)
First occurred: 12:39:07 (5 occurrences)
Last logged: 13:09:52

[bfa...k4k] Initial state update failed, giving up: TimeoutError()
```
```
This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:677
Integration: LocalTuya integration (documentation, issues)
First occurred: 12:38:46 (405 occurrences)
Last logged: 13:11:37

[bfa...k4k] Disconnected - waiting for discovery broadcast
[bf4...n6r] Disconnected - waiting for discovery broadcast
[bf9...9nw] Disconnected - waiting for discovery broadcast
```

**Comment by ScottWoolven5** [comment]
I removed the device and tried re-adding however I am. Ow getting the following error:
`Connection to device succeeded but no datapoints found, please try again. `

**Comment by ScottWoolven5** [comment]
I removed the device from my SmartLife app, reset to factory settings and re-added it. The device ID and local key had changed but after adding it back to Local Tuya, it's now responsive.
