### ISSUE TITLE
Connect to 192.168.31.95 failed

### ISSUE THREAD

**Issue by khaisilk1910** [rospogrigio/localtuya#1318]
I have an outlet and am unavailable on Home Assistant. Although on Tuya application this socket can still be controlled normally.

This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:1163
Integration: LocalTuya (documentation, issues)
First occurred: March 5, 2023 at 10:19:58 AM (1199 occurrences)
Last logged: 6:16:55 AM

[eb6...sok] Connect to 192.168.31.95 failed
[172...78d] Connect to 192.168.31.174 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 187, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1163, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.31.95', 6668)

**Comment by ChaoticBD** [comment]
The same truble when device rejoining wifi or reconnecting from 1 mash router to another. And i still can controll my devices via tuya app

**Comment by krokenn** [comment]
Same error on 3 tuya smart plugs..

**Comment by mkaatman** [comment]
Mine started working after I was doing unrelated work and cycled all my breakers. I had restarted home assistant but I hadn't though to restart the bulbs. Oddly, they're working fine now.
