### ISSUE TITLE
Unexpected exception adding new device

### ISSUE THREAD

**Issue by maxwell-01** [rospogrigio/localtuya#1335]
## The problem
Unable to add a new TUYA device - see error log for details:

```
OSError: [Errno 113] Connect call failed ('192.168.1.102', 6668)
2023-03-19 15:25:01.614 WARNING (event_thread_0) [sucks] Ping did not reach VacBot. Will retry.
2023-03-19 15:25:24.830 ERROR (MainThread) [custom_components.localtuya.common] [bfd...dle] Connect to 192.168.1.33 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 187, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1163, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
```

## Environment

- Localtuya version: v5.1.0
- Home Assistant Core version: Home Assistant 2023.3.5 Supervisor 2023.03.1 Operating System 9.5 Frontend 20230309.1 - latest
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

1.  Configure -> Add new device -> Submit -> (device shows up in the list) Submit again
2. Check through name, host etc, all correct
3. Click submit -> times out and errors in logs

## Provide Home Assistant traceback/logs

```
put your log output between these markers
```

## Additional information

Purchased from Ali Express: https://www.aliexpress.com/item/1005004533636708.html?spm=a2g0o.order_list.order_list_main.11.440e1802jZ6kai

**Comment by maxwell-01** [comment]
Unfortunately not yet - I have resided to using the online integration for these devices.
