### ISSUE TITLE
Integration initializes, but all devices are unavailable. Error cannot import name 'KeyDerivationFunction' from 'cryptography.hazmat.primitives.kdf'

### ISSUE THREAD

**Issue by LeoSko** [rospogrigio/localtuya#1336]
## The problem

The integration starts with success, but all devices appear unavailable with the following error appearing in the logs regularly (see below).

## Environment

- Localtuya version: 5.1.0
- Home Assistant Core version: 2023.3.5
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [x] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [x] Was the device working with earlier versions of localtuya ? Which one? 
- [] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

1. Start the integration

## Provide Home Assistant traceback/logs

```
Logger: homeassistant
Source: custom_components/localtuya/discovery.py:67
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 8:07:42 PM (335 occurrences)
Last logged: 8:13:14 PM

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
  File "/config/custom_components/localtuya/discovery.py", line 28, in decrypt_udp
    cipher = Cipher(algorithms.AES(UDP_KEY), modes.ECB(), default_backend())
  File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/backends/__init__.py", line 8, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 114, in <module>
    from cryptography.hazmat.primitives.kdf import scrypt
  File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/primitives/kdf/scrypt.py", line 16, in <module>
    from cryptography.hazmat.primitives.kdf import KeyDerivationFunction
ImportError: cannot import name 'KeyDerivationFunction' from 'cryptography.hazmat.primitives.kdf' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1035, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 0: invalid start byte
```

**Comment by LeoSko** [comment]
Issue fixed itself a while ago, I guess with yet another update of HAOS but not sure now.
