### ISSUE TITLE
"KeyError: 'region'" on startup causes Local Tuya to crash

### ISSUE THREAD

**Issue by drew-hill** [rospogrigio/localtuya#1337]
## The problem
Local Tuya module will not start. I receive the following error:

```
KeyError: 'region'
```

## Environment
- Localtuya version: 5.5.0 & 5.1.0
- Home Assistant Core version: 2023.3.5
- [x] Does the device work using the Home Assistant Tuya Cloud component ? 
- [x] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [x unsure which version, but likely 5.5.0] Was the device working with earlier versions of localtuya ? Which one? 
- [x] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce
I am unsure how to reproduce, but I believe it is related to adding "Firmware 3.4" devices to a setup with existing "Firmware 3.3" devices.

I have had this issue twice twice now since adding Firmware 3.4 devices, and the first time was resolved by wiping and manually re-setting up the LocalTuya module and manually re-entering every device via Home Assistant GUI.

## DP dump -- for a 3.3 device

**** deviceInfo returned OK ****

TuyaDebug (Tuya DPs dump) [1.0.0]

Device <DEVID> at <IP ADDRESS> key <KEY> protocol 3.3 dev_type type_0a:
    DPS [20] VALUE [False] 
    DPS [21] VALUE [colour] 
    DPS [22] VALUE [1000] 
    DPS [24] VALUE [001c029400df] 
    DPS [25] VALUE [04323201000003e803e800000000323201007803e803e800000000] 
    DPS [26] VALUE [0] 

## DP dump -- for a 3.4 device

**** deviceInfo returned OK ****

TuyaDebug (Tuya DPs dump) [1.0.0]

Device <devid> at <devip> key <key> protocol 3.4 dev_type v3.4:
    DPS [1] VALUE [False] 
    DPS [7] VALUE [0] 
    DPS [101] VALUE [300] 
    DPS [102] VALUE [600] 
    DPS [103] VALUE [1800] 
    DPS [104] VALUE [3600] 
    DPS [105] VALUE [7200] 
    DPS [106] VALUE [14400] 
    DPS [107] VALUE [50] 
    DPS [108] VALUE [3] 
    DPS [109] VALUE [flicker] 
    DPS [110] VALUE [flicker] 
    DPS [111] VALUE [False] 

## Provide Home Assistant traceback/logs

```
Logger: homeassistant.config_entries
Source: custom_components/localtuya/__init__.py:242 
Integration: LocalTuya (documentation, issues) 
First occurred: March 19, 2023 at 8:58:35 AM (2 occurrences) 
Last logged: March 19, 2023 at 9:33:51 AM

Error setting up entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 242, in async_setup_entry
    region = entry.data[CONF_REGION]
```

**Comment by drew-hill** [comment]
This may be related to:

- https://github.com/rospogrigio/localtuya/issues/921
- https://github.com/rospogrigio/localtuya/issues/980
