### ISSUE TITLE
Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists.

### ISSUE THREAD

**Issue by tomcoleman** [rospogrigio/localtuya#1345]
So Adding Tuya Local to HA it finds the device ID automatically and asks for local key and name.

I extracted the local Key from the Tuya API when putting in the local ID i get the responce in HA of

"Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists."

Not sure where to go from here as in the Tuya web platform the devices are showing and also in the Tuya iOS the devices are showing and i can control them.

Any advice would be great

**Comment by Dikkebij** [comment]
Same overhere
Only happens with lights V3.4

**Comment by ddokupil** [comment]
I even had a working switch (the one from Action stores) and one day found out it's no longer available. I tried reloading the integration, removed the device and no when i try to configure it once again I'm getting the same error.

**Comment by kapitonovdv** [comment]
@ddokupil I have same problem with my thermostates MOES. How did you downgreade from 5.1 to 5.0?

**Comment by ddokupil** [comment]
If you wish to downgreade go to HACS in your Home Assistant, click three vertical dots to the right from your Tuya repository and there is download again option. From there you'll know what to do.

**Comment by Dikkebij** [comment]
Downgraded to V5.0.0.
Same problem. Lights V3.3 working fine but lights V3.4 will not work.

**Comment by kapitonovdv** [comment]
I downgreaded my localtuya to v.5.0.0. Му thermostats are working.

**Comment by zhenyatk** [comment]
Even after downgrade to 5.0.0 v3.4 devices not work :(

**Comment by koen-schonhoven** [comment]
Same issue here, adding QN-WP01E WiFi power plug. Configuring Tuya Device automagically detected IP address and local key, but on hitting the Save button, I also get errormsg "Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists."

Logging:
`[bf9...v33] Failed to get status:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 863, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 795, in status
    status = await self.exchange(DP_QUERY)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError`

**Comment by grandeal** [comment]
Have this issue for two separate devices. I have been activating my devices via Tuya Smart app first before adding them into Localtuya. Works the first time but not subsequently.

First device is a Lenovo Smart plug. It worked for a while but suddenly stopped responding to localtuya. When I tried to remove and re-add, I got this error message as OP. Initially, I thought it was because my tuya IOT account privileges expired. But it didn't make sense because my other Lenovo Led lightstrip is working fine and could connect no matter how many times I removed it.

Today, I added a Bright manufactured bulb into Localtuya. Again it worked the first time. Then I fiddled with the bulb and accidentally got it to reset. What I did:
- removed the device from the Tuya smart app and re-add. Works.
- In Localtuya, the device in the entities page had an exclamation mark. 
- Tried "Edit a device" and saved settings with no changes. 
- The exclamation mark was gone but the bulb still would not respond to the "on/off" in Localtuya. 
- Tried "Edit device again" but this time I chose to remove the device from there. It gave me an error and could not be removed. 
- Went to the Device page which had a Delete device option. That worked but now I am getting this error when I try to add the device into localtuya

I am new to HA and localytuya. I have not seen any logs that look similar to the other posters and documentation is not very clear on where to find the logs. I would gladly give the error logs if someone can guide me.
But this seems a Localtuya issue, the Tuya smart app had no problems with me removing and readding the two devices I mentioned above and works fine. Most importantly, the Tuya's own integration in HA works, it detects my smart plug without issue every time while localtuya just complains about not having datapoints.

Side question, I only managed to get my led light strip with "on/off" function even though I specified all the parameters when adding. Any suggestions?

**Comment by grandeal** [comment]
> If you wish to downgreade go to HACS in your Home Assistant, click three vertical dots to the right from your Tuya repository and there is download again option. From there you'll know what to do.

Where is this "download again" option?
![image](https://user-images.githubusercontent.com/106002117/230477289-9a5f1467-ba91-4f09-be72-fa8b4dc51f87.png)

**Comment by Dikkebij** [comment]
![localtuya1](https://user-images.githubusercontent.com/88229683/230576968-9d1ea792-b6b3-4d0a-93a0-4f332795ce36.jpg)
![Localtuya2](https://user-images.githubusercontent.com/88229683/230576988-1014e0d5-4839-494b-b714-af8865079d22.jpg)
![Localtuya3](https://user-images.githubusercontent.com/88229683/230577002-8bc0c6d1-231e-4c1d-a390-99445011773d.jpg)

**Comment by ovidiuc88** [comment]
Same problem and I tried redownloading older versions but the same problem appeared (went down to 4.1.1).
I am trying to connect a wireless zigbee gateway which controls 3 TRVs. Working fine in the Tuya Smart Life App.

**Comment by OG-algo** [comment]
same problem with ZigBee Gateway

**Comment by Railsimulatornet** [comment]
Same Problem with Gosund plugs 3.3

**Comment by grandeal** [comment]
@Dikkebij wanted to thank you for the image steps, I realized that I was on 4.1.1 with the issues.
Upgraded to 5.1, still didn't work and both the non-working light and working lightstrip gave weird errors (a circle with an exclamation mark) on the entities page. 
Downgraded to 4.1 and still no luck.

**Comment by MrEcosse** [comment]
Similar behavior here.  Was new to the integration and a number of my devices could not be added reporting this error.  Downgraded to 5.0.0 and most of the expected devices (such as plug top switches) are now able to be added.

**Comment by spanzetta** [comment]
I have 6 device (Lamps) working fine from beginning (5.1.0)
Now I have a new device (Smart Water Timer, HCT-611) which works fine with Tuya/Smartlife app but I get this error when trying to add to my HA (connection to device succeeded but no datapoints .. blah blah)
How to fix?

**Comment by Railsimulatornet** [comment]
Version 5.0 
`3-04-14 17:56:29.887 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-14 17:56:29.891 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-14 17:56:47.557 WARNING (MainThread) [homeassistant.components.dlna_dms] Failed connecting to recently alive device at http://10.8.0.1:8096/dlna/126d3f23-0db1-439f-8197-09927d377060/description.xml: UpnpConnectionError('ClientConnectorError(ConnectionKey(host=\'10.8.0.1\', port=8096, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-1203528730348637513), OSError(101, "Connect call failed (\'10.8.0.1\', 8096)"))', None)
2023-04-14 17:56:49.193 ERROR (SyncWorker_5) [homeassistant.components.fritzbox_callmonitor.sensor] Cannot connect to 192.168.120.1 on port 1012: [Errno 111] Connection refused
2023-04-14 17:56:49.375 WARNING (MainThread) [homeassistant.config_entries] Config entry 'HP OfficeJet Pro 8710 [0566FF]' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2023-04-14 17:57:07.988 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform fritz is taking over 10 seconds.
2023-04-14 19:01:26.767 ERROR (MainThread) [frontend.js.latest.202304111] :0:0 ResizeObserver loop completed with undelivered notifications.
2023-04-14 19:02:06.022 DEBUG (MainThread) [custom_components.localtuya.pytuya] [386...218] Sending command 10 (device type: type_0a)
2023-04-14 19:02:06.023 DEBUG (MainThread) [custom_components.localtuya.pytuya] [386...218] Sending payload: b'{"gwId":"38646214c4dd57359218","devId":"38646214c4dd57359218","uid":"38646214c4dd57359218","t":"1681491726"}'
2023-04-14 19:02:06.025 DEBUG (MainThread) [custom_components.localtuya.pytuya] [386...218] Command 10 waiting for sequence number 1
2023-04-14 19:02:06.038 DEBUG (MainThread) [custom_components.localtuya.pytuya] [386...218] Dispatching message CMD 10 TuyaMessage(seqno=1, cmd=10, retcode=1, payload=b'\x10`r\x9cX\x82\xbed8\xa9\\l\xe6\xd1#\xd2\xa0\x1b\xb9^\xb1A0\x84\xae\xd2\xb4\xd0\x1f[\x16\x9a', crc=3862278895, crc_good=True)
2023-04-14 19:02:06.039 DEBUG (MainThread) [custom_components.localtuya.pytuya] [386...218] Deciphered data = ''
2023-04-14 19:02:06.039 DEBUG (MainThread) [custom_components.localtuya.pytuya] [386...218] ERROR Invalid JSON Response from Device - 900 - payload: ""
2023-04-14 19:02:06.039 DEBUG (MainThread) [custom_components.localtuya.config_flow] Detected DPS: {}
2023-04-14 19:02:06.039 DEBUG (MainThread) [custom_components.localtuya.pytuya] [386...218] Closing connection
2023-04-14 19:02:06.042 DEBUG (MainThread) [custom_components.localtuya.pytuya] [386...218] Connection lost: None`

How can I fix this please?

**Comment by spanzetta** [comment]
> I have 6 device (Lamps) working fine from beginning (5.1.0) Now I have a new device (Smart Water Timer, HCT-611) which works fine with Tuya/Smartlife app but I get this error when trying to add to my HA (connection to device succeeded but no datapoints .. blah blah) How to fix?

I tried (just as test) with official Tuya integration and I was able to add the device.. but it didn't find any senors
I assume that this is the problem of adding this device.. 

Strangely on Tuya iot platfrom I see these infos in the device details .. so I assume it can be in some way supported by HA but it needs some special programming? If you want (@rospogrigio) to try to support it pls contact me and I can provide you all the info you may need 

"status": [
      {
        "code": "switch",
        "value": false
      },
      {
        "code": "battery_percentage",
        "value": 5
      },
      {
        "code": "battery_state",
        "value": "high"
      },
      {
        "code": "weather_delay",
        "value": "cancel"
      },
      {
        "code": "countdown",
        "value": 0
      },
      {
        "code": "work_state",
        "value": "auto"
      },
      {
        "code": "smart_weather",
        "value": "cloudy"
      }
    ],

**Comment by man55** [comment]
same bug here

**Comment by hizber** [comment]
Hello, I have the same issue. Is there any improvement for this bug? Any explanation why it happens?

**Comment by cadavre** [comment]
I had this issue when re-connecting WiFi to another SSID. I removed the device and when tried to re-add it – I faced this error.

What worked for me was:
* remove device,
* restart HA,
* add device.
