### ISSUE TITLE
Integration broken completely after HAOS 10.0

### ISSUE THREAD

**Issue by direx1** [rospogrigio/localtuya#1359]
First occurred: 13:49:08 (13518 occurrences)
Last logged: 20:04:44

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1035, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
    self.device_found(decoded)
  File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
    self._callback(device)
  File "/config/custom_components/localtuya/__init__.py", line 105, in _device_discovered
    entry = async_config_entry_by_device_id(hass, device_id)
  File "/config/custom_components/localtuya/common.py", line 127, in async_config_entry_by_device_id
    if device_id in entry.data[CONF_DEVICES]:
KeyError: 'devices'

**Comment by BigRedHolger** [comment]
Any resolution? I seem to have the same problem:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/localtuya/common.py:127
Integration: LocalTuya (documentation, issues)
First occurred: 6:11:30 PM (121 occurrences)
Last logged: 6:12:03 PM

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1035, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
    self.device_found(decoded)
  File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
    self._callback(device)
  File "/config/custom_components/localtuya/__init__.py", line 105, in _device_discovered
    entry = async_config_entry_by_device_id(hass, device_id)
  File "/config/custom_components/localtuya/common.py", line 127, in async_config_entry_by_device_id
    if device_id in entry.data[CONF_DEVICES]:
KeyError: 'devices'


Also:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/localtuya/__init__.py:283
Integration: LocalTuya (documentation, issues)
First occurred: 6:11:31 PM (1 occurrences)
Last logged: 6:11:31 PM

Error setting up entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 283, in async_setup_entry
    hass.async_create_task(setup_entities(entry.data[CONF_DEVICES].keys()))
KeyError: 'devices'

**Comment by DedicatedF100** [comment]
Just wanted to see if there was any solution for this issue yet. I'm having the same problem, most my lights stopped working.

Error setting up entry localtuya for localtuya

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 283, in async_setup_entry
    hass.async_create_task(setup_entities(entry.data[CONF_DEVICES].keys()))
KeyError: 'devices'

**Comment by BigRedHolger** [comment]
Hi, I ended up uninstalling the integration. Then reinstalling it. I was
hoping to avoid doing that as I had to re-enter and reset up all the lights
and switches and vacuums. Not a very satisfactory answer, but it worked.
