### ISSUE TITLE
Many errors in the logs

### ISSUE THREAD

**Issue by D33M** [rospogrigio/localtuya#136]
Hello. First of all, I would like to thank you for the integration, this is great and exactly what I was looking for. You are doing a great job!

Recently, my log gets flooded with errors like:

```txt
home-assistant    | 2020-11-03 19:53:17 ERROR (MainThread) [custom_components.localtuya.pytuya] [753802832462ab3c12e6] Heartbeat failed (), disconnecting
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/config/custom_components/localtuya/pytuya/__init__.py", line 346, in heartbeat_loop
home-assistant    |     await self.heartbeat()
home-assistant    |   File "/config/custom_components/localtuya/pytuya/__init__.py", line 435, in heartbeat
home-assistant    |     return await self.exchange(HEARTBEAT)
home-assistant    |   File "/config/custom_components/localtuya/pytuya/__init__.py", line 407, in exchange
home-assistant    |     msg = await self.dispatcher.wait_for(seqno)
home-assistant    |   File "/config/custom_components/localtuya/pytuya/__init__.py", line 206, in wait_for
home-assistant    |     await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
home-assistant    |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
home-assistant    |     raise exceptions.TimeoutError()
home-assistant    | asyncio.exceptions.TimeoutError
```
or
```txt
home-assistant    | 2020-11-03 19:51:26 ERROR (MainThread) [custom_components.localtuya.pytuya] [604816782462ab541ff5] Heartbeat failed ('NoneType' object has no attribute 'write'), disconnecting
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/config/custom_components/localtuya/pytuya/__init__.py", line 346, in heartbeat_loop
home-assistant    |     await self.heartbeat()
home-assistant    |   File "/config/custom_components/localtuya/pytuya/__init__.py", line 435, in heartbeat
home-assistant    |     return await self.exchange(HEARTBEAT)
home-assistant    |   File "/config/custom_components/localtuya/pytuya/__init__.py", line 406, in exchange
home-assistant    |     self.transport.write(payload)
home-assistant    | AttributeError: 'NoneType' object has no attribute 'write'
```
While the timeout I can understand, the .write method on NoneType keeps appearing very often. Just after the restart:
![image](https://user-images.githubusercontent.com/6951861/98028899-0ad4e800-1e0f-11eb-8042-dfce7f69208d.png)

I would also like to ask, is there any documentation what specific "numbers"/"ids" mean for each device? Kinda with try-and-fail  I was able to guess:
```yaml
    - platform: switch
      friendly_name: Washing machine
      id: 1
      current: 4
      current_consumption: 5
      voltage: 6
```
but there are still some IDs, which value is always `0`. Do you maybe know, what they are?

**Comment by postlund** [comment]
It's hard to say anything with these logs alone as a lot of context is missing (I.e. more logs from before the errors happen are needed). Do you know at what frequency these errors happen? Is it once a day, directly or every now and then? You can get more logs by enabling [them](https://github.com/rospogrigio/localtuya#debugging).

You can use [tuyadebug](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump) to dump all datapoints and their values. This will not tell you what each datapoint actually mean as we don't have that information, you will have to guess. The easiest way is to just skip YAML and add via config flow directly (Configuration -> Integrations) as you will be presented with all datapoints and their values. So no need for tuyadebug either.

Normally power attributes are 18-20 and most of the datapoint below 10 timers of various sorts. Might be worth looking into, but it's totally vendor specific so you light very well have the correct datapoints.

**Comment by jfparis** [comment]
Going through the same issue at the moment with some of my devices become unavailable after some time (as tuya local seems to be failing to reconnect after a timeout)

I have multiple devices so my logs are worthless (i am running with some custom built so I can better filter the logs) I will upload something when I can reproduce the bug

**Comment by D33M** [comment]
@postlund No, those are the only logs that are appearing nearby. I can enable debug logs today, I will check if there are any more details.

**Comment by postlund** [comment]
@jfparis @D33M If you can re-test using what is on `master` and with debug logs enabled...


![](https://i.imgflip.com/q1g68.jpg)

**Comment by D33M** [comment]
Sure thing, will try today. I had recently almost no time at all, so sorry for the long delay.

**Comment by D33M** [comment]
No luck, after the update and half a day on the debug logs, no heartbeat problems appeared with the localtuya integration... I will leave debug logs on, maybe it will happen tomorrow. Or... Maybe it is fixed?:D

**Comment by postlund** [comment]
@D33M We are of course hoping for it being fixed 😉

**Comment by jfparis** [comment]
Hi.

So there are still some errors on this side. 

Attached is the log for last night
1) 'NoneType' object has no attribute 'write' at 3.30 in the morning
2) Quite a few Disconnected: [Errno 104] Connection reset by peer. At that point, the device becomes unavailable in HASS but it recovers so this is manageable
3) Finally at about 8:15 our 15-month-old toddler got in the room and disconnected a tuya plug [bf7...3eg] (easy with those switch we have in the UK). What is interesting is that pytuya or localtuya did not handle that gracefully and there is no attempt to reconnect. My understanding of the code is that it should try to reconnect with an increasing delay between each attempt

[localtuya1.log](https://github.com/rospogrigio/localtuya/files/5563348/localtuya1.log)

**Comment by jfparis** [comment]
Attached is the log from today

Had another device crash (with no reconnect). This one was not assisted by my son. Just some network error and the system fails to reconnect

At 13:51 we hear of [bf5...xev] for the last time (until I restart the localtuya integration hours later)
the system attempts to reconnect but abort the reconnection because it is already attempting to connect

This chain of events is the same I was observing last week
[localtuya2.log](https://github.com/rospogrigio/localtuya/files/5563404/localtuya2.log)

**Comment by D33M** [comment]
Hm, so today I got an error 
```
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 381, in heartbeat_loop
    self.exception("Heartbeat failed (%s), disconnecting", ex)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 140, in exception
    return self._logger.log(logging.EXCEPTION, msg, *args)
AttributeError: module 'logging' has no attribute 'EXCEPTION'
```
[errors](https://github.com/rospogrigio/localtuya/files/5566374/logs2.txt)

What's worse, my plug became unavailable:
![image](https://user-images.githubusercontent.com/6951861/99658632-0f7cdb80-2a60-11eb-9a94-26d6d3f8887c.png)

![image](https://user-images.githubusercontent.com/6951861/99658658-186dad00-2a60-11eb-9312-2d9bc782dfa7.png)

But I do not see any errors in logs around this time. Full log can be found here:

[home-assistant-from-start-to-around-plug-disconnection](https://github.com/rospogrigio/localtuya/files/5566367/logs.txt)

**Comment by jfparis** [comment]
Hi

Check if you have something along the line of  the below

A connection dropping followed by an attempt to reconnect which is aborted with "Already connecting to..."
```
2020-11-18 13:51:17 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...xev] Connection lost: [Errno 104] Connection reset by peer
2020-11-18 13:51:17 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...xev] Closing connection
2020-11-18 13:51:17 DEBUG (MainThread) [custom_components.localtuya.common] [bf5...xev] Disconnected: [Errno 104] Connection reset by peer
2020-11-18 13:51:17 DEBUG (MainThread) [custom_components.localtuya.common] [bf5...xev] Already connecting to 192.168.2.150 (bf50b24b0a08e11cafgxev) - False, <Task finished name='Task-93410' coro=<TuyaDevice._make_connection() done, defined at /config/custom_components/localtuya/common.py:130> exception=AttributeError("module 'logging' has no attribute 'EXCEPTION'")>, None
```

**Comment by postlund** [comment]
I created #173 that should fix that particular issue (we will likely see another one instead). Please try it out.

**Comment by D33M** [comment]
I will try it after work (around 16:00). Yesterday I also updated HASS to 0.118, but I do not think this is relevant to the issue.

@jfparis, it happened twice in logs:
```
2020-11-18 23:19:52 DEBUG (MainThread) [custom_components.localtuya.common] [753...2e6] Already connecting to 192.168.86.44 (753802832462ab3c12e6) - False, <Task finished name='Task-69399' coro=<TuyaDevice._make_connection() done, defined at /config/custom_components/localtuya/common.py:130> exception=AttributeError("module 'logging' has no attribute 'EXCEPTION'")>, None
2020-11-18 23:19:52 DEBUG (MainThread) [custom_components.localtuya.pytuya] [455...d2a] Decrypted payload: {}
2020-11-18 23:19:54 DEBUG (MainThread) [custom_components.localtuya.pytuya] [825...1da] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b"3.3\x00\x00\x00\x00\x00\x03Y\xce\x00\x00\x00\x01\xe9_u\xff\x87~\xe6y\xe4\x8d\xbc'\x18\xdc\x881\xa1\xc2\xb7\x89\xa1\xe0\xa4i\x18\xfb\xeb\x8d\xfb\xe0`\xe5\xd1\xb0`'\x8a0\xe8\xa8\xa7\xe4g\x07\xc2R\x1f4|\x81-m F\xb1\x9c~'\xcb\xc8?{\x05+\x91\x89\xa4mW\xfb\x16<*\xc3,\x9b\xc41\x7f\x00", crc=4034472767)
2020-11-18 23:19:54 DEBUG (MainThread) [custom_components.localtuya.pytuya] [825...1da] Got status update
2020-11-18 23:19:54 DEBUG (MainThread) [custom_components.localtuya.pytuya] [825...1da] Decrypted payload: {"devId":"825062575002911a71da","dps":{"4":705,"5":1610},"t":1605741594}
```
```
2020-11-18 23:19:52 DEBUG (MainThread) [custom_components.localtuya.pytuya] [753...2e6] Connection lost: [Errno 104] Connection reset by peer
2020-11-18 23:19:52 DEBUG (MainThread) [custom_components.localtuya.pytuya] [753...2e6] Closing connection
2020-11-18 23:19:52 DEBUG (MainThread) [custom_components.localtuya.common] [753...2e6] Disconnected: [Errno 104] Connection reset by peer
2020-11-18 23:19:52 DEBUG (MainThread) [custom_components.localtuya.common] [753...2e6] Already connecting to 192.168.86.44 (753802832462ab3c12e6) - False, <Task finished name='Task-69399' coro=<TuyaDevice._make_connection() done, defined at /config/custom_components/localtuya/common.py:130> exception=AttributeError("module 'logging' has no attribute 'EXCEPTION'")>, None
2020-11-18 23:19:52 DEBUG (MainThread) [custom_components.localtuya.pytuya] [455...d2a] Decrypted payload: {}
2020-11-18 23:19:54 DEBUG (MainThread) [custom_components.localtuya.pytuya] [825...1da] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b"3.3\x00\x00\x00\x00\x00\x03Y\xce\x00\x00\x00\x01\xe9_u\xff\x87~\xe6y\xe4\x8d\xbc'\x18\xdc\x881\xa1\xc2\xb7\x89\xa1\xe0\xa4i\x18\xfb\xeb\x8d\xfb\xe0`\xe5\xd1\xb0`'\x8a0\xe8\xa8\xa7\xe4g\x07\xc2R\x1f4|\x81-m F\xb1\x9c~'\xcb\xc8?{\x05+\x91\x89\xa4mW\xfb\x16<*\xc3,\x9b\xc41\x7f\x00", crc=4034472767)
2020-11-18 23:19:54 DEBUG (MainThread) [custom_components.localtuya.pytuya] [825...1da] Got status update
2020-11-18 23:19:54 DEBUG (MainThread) [custom_components.localtuya.pytuya] [825...1da] Decrypted payload: {"devId":"825062575002911a71da","dps":{"4":705,"5":1610},"t":1605741594}
```

By the way, the issue with the unavailable plug will be resolved if I'll re-add it with the integration (firstly remove, then restart HASS). Should I do it, or should I leave it like that for debugging purposes?

**Comment by D33M** [comment]
```
home-assistant    | 2020-11-19 17:25:04 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.86.78', 'gwId': '825062575002911ae476', 'active': 2, 'ability': 0, 'mode': 0, 'encrypt': True, 'productKey': '37mnhia3pojleqfh', 'version': '3.3'}
home-assistant    | --- Logging error ---
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/usr/local/lib/python3.8/logging/__init__.py", line 1081, in emit
home-assistant    |     msg = self.format(record)
home-assistant    |   File "/usr/local/lib/python3.8/logging/__init__.py", line 925, in format
home-assistant    |     return fmt.format(record)
home-assistant    |   File "/usr/local/lib/python3.8/site-packages/colorlog/colorlog.py", line 123, in format
home-assistant    |     message = super(ColoredFormatter, self).format(record)
home-assistant    |   File "/usr/local/lib/python3.8/logging/__init__.py", line 664, in format
home-assistant    |     record.message = record.getMessage()
home-assistant    |   File "/usr/local/lib/python3.8/logging/__init__.py", line 369, in getMessage
home-assistant    |     msg = msg % self.args
home-assistant    | TypeError: not enough arguments for format string
home-assistant    | Call stack:
home-assistant    |   File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
home-assistant    |     self._bootstrap_inner()
home-assistant    |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
home-assistant    |     self.run()
home-assistant    |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
home-assistant    |     self._target(*self._args, **self._kwargs)
home-assistant    | Message: 'Update keys for device %s: %s'
home-assistant    | Arguments: {'product_key': '37mnhia3pojleqfh'}
```

After updating it to the new branch `logging_fix`

**Comment by D33M** [comment]
Ech... Seems like that update is a little bad luck for me:
```
home-assistant    | 2020-11-19 17:25:34 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Smart plug 2 (YAML) for switch
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
home-assistant    |     result = await component.async_setup_entry(hass, self)  # type: ignore
home-assistant    |   File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry
home-assistant    |     return await hass.data[DOMAIN].async_setup_entry(entry)
home-assistant    |   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry
home-assistant    |     raise ValueError("Config entry has already been setup!")
home-assistant    | ValueError: Config entry has already been setup!
```

Since I use YAML config, I'll delete everything and let it recreate.

**Comment by postlund** [comment]
I have submitted a PR to fix the log error (#174 ). The fact that you got a config entry error is strange, that is fixed on master since a long time back. Which version did you use?

**Comment by D33M** [comment]
Basically, I downloaded the branch `logging_fix` (https://github.com/rospogrigio/localtuya/pull/173) and uploaded the integration from this code (the whole `localtuya` directory). To be honest, I believed that the branch is from the latest `master` commits, haven't checked it by myself. I am comfortable with Gitlab's UI and Github's one is less readable for me... Can't find information on how much behind is the branch from the master.

**Comment by D33M** [comment]
I will update the localtuya integration to the latest from master, as the #173 got merged - I will check whether the problem is fixed.

**Comment by D33M** [comment]
Just to try to help with the diagnosis, today two smart sockets became unavailable.

[logs3.txt](https://github.com/rospogrigio/localtuya/files/5614406/logs3.txt)

**Comment by jfparis** [comment]
A bit of an update here

This bug, #140 and #202 all seems to be related to the following pattern
* System is connected and humming happily
* Connection drops (could it be a wifi reliability issue? who knows)
* In some cases but not all of them, the system fails to reconnect to the socker (this is something to do with the way the async loop is behaving).

This is not the expected system behaviour. My reading of the code (but I lack the expertise to see where things go wrong) would be to try to reconnect forever with an increasing delay between the attempts (which for some reason does not happen)

For the purpose of debugging, an easy way to simulate the drop of connection is to pull the "smart socket" out of the plug for 10 seconds and plug it back in

**Comment by jfparis** [comment]
@postlund I installed your branch (above) this morning. Will report if I see improvements

**Comment by egorgam** [comment]
https://github.com/rospogrigio/localtuya/pull/561 

I found a solution!
Just replace logging type in line 156 of common.py (replace self.exception to self.debug) to fix it.

**Comment by D33M** [comment]
Doesn't this just hide the error instead of fixing the issue?

**Comment by jellespijker** [comment]
It isn't an error on my opinion. Devices can be offline for various reasons. By just showing a warning or debug message the user is still notified without polluting the logs
