### ISSUE TITLE
Discovery list empty, unable to add new devices

### ISSUE THREAD

**Issue by sambarlick** [rospogrigio/localtuya#1366]
## Environment

- Localtuya version:  
- Home Assistant Core version:  
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

1.
2. 
3.

## Provide Home Assistant traceback/logs

```
put your log output between these markers
```

**Comment by oopptt** [comment]
Hello!

Same here, after adding the integration, there is no devices discovered. Project is created and I have all the data, system id, client id and pwd, and I see all the devices on the project webpage. My system is the following:
Home Assistant 2023.4.6
Supervisor 2023.04.0
Operating System 10.0

Logs don't show errors:

2023-04-23 16:28:41.748 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-23 16:31:17.434 INFO (MainThread) [custom_components.localtuya.config_flow] Cloud API connection succeeded.
2023-04-23 16:31:17.439 INFO (MainThread) [homeassistant.setup] Setting up localtuya
2023-04-23 16:31:17.451 INFO (MainThread) [homeassistant.setup] Setup of domain localtuya took 0.0 seconds
2023-04-23 16:31:17.618 INFO (MainThread) [custom_components.localtuya] Cloud API connection succeeded.

Could anybody help? 

Thanks in advance.

**Comment by kjeldahl** [comment]
I am in the same position. No errors logged and no devices shown. 

If I download the diagnostics for the local tuya integration it lists the devices under data -> cloud_devices in the returned json structure. The data -> devices are however an empty map. 
Each of the devices listed under cloud_devices have an ip that corresponds to my public ip. Could that be an issue?

Or is it more of an issue that all the devices are on another subnet than my HA installation?

**Comment by treyd** [comment]
I have this issue as well with HA 2023.5 and integration 5.1.0.  I'm new to tuya so I'm not sure how it all should work, but poking around in the API Explorer on iot.tuya.com showed a "Permission Denied" when trying to get Device information (and see the local key).  I wonder if this is part of the issue?

**Comment by wisheh** [comment]
Can confirm the exact same issue.
Home Assistant 2023.5.2
Local Tuya 5.1.0

**Comment by sacbhale** [comment]
Ditto, no devices being discovered for me as well. Tried various HA versions up to 2023.5.2

**Comment by sambarlick** [comment]
I am also unable to edit my current devices.
I reach the last entity then get an unknown error.

Here are my logs:
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/localtuya/config_flow.py:743
Integration: LocalTuya integration (documentation, issues)
First occurred: 19:21:30 (2 occurrences)
Last logged: 19:22:04

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 743, in async_step_configure_entity
    ent_reg = await er.async_get_registry(self.hass)
AttributeError: module 'homeassistant.helpers.entity_registry' has no attribute 'async_get_registry'

**Comment by r3pek** [comment]
same here... anyone has any idea?

**Comment by GordonSmith** [comment]
Just a me too - the devices appear in the diagnostic download, but nothing available in the drop down...
