### ISSUE TITLE
Switch becomes unavailable after HA restart

### ISSUE THREAD

**Issue by majkers** [rospogrigio/localtuya#1385]
## The problem
Suddenly my switch started to act weird. After HA restart it becomes unavailable and I have to unplug it and plug it again to make it visible again. 

These are the logs from HA start:

```
2023-05-12 15:37:58.533 WARNING (MainThread) [custom_components.localtuya.switch] [bf0...jxb] Entity switch.tuya_gniazdko is requesting unknown DPS index 18
2023-05-12 15:37:58.541 WARNING (MainThread) [custom_components.localtuya.switch] [bf0...jxb] Entity switch.tuya_gniazdko is requesting unknown DPS index 19
2023-05-12 15:37:58.547 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 652, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/localtuya/switch.py", line 65, in extra_state_attributes
    self.dps(self._config[CONF_CURRENT_CONSUMPTION]) / 10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

But even then when I try to re configure it I get an error:

```
Logger: aiohttp.server
Source: custom_components/localtuya/config_flow.py:743
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 15:39:27 (3 occurrences)
Last logged: 15:43:17

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 743, in async_step_configure_entity
    ent_reg = await er.async_get_registry(self.hass)
AttributeError: module 'homeassistant.helpers.entity_registry' has no attribute 'async_get_registry'
```

Enviroment:

![image](https://github.com/rospogrigio/localtuya/assets/21099773/0bf09c07-f4a5-456b-9c46-8d2cb0bbbdce)

![image](https://github.com/rospogrigio/localtuya/assets/21099773/e4f97d30-9a27-46f9-be6b-6348c605197a)

**Comment by LupoCri** [comment]
Same here but just reload the integration is enoug, all the time i restart HA or for upgrade.
Tnx

**Comment by majkers** [comment]
Reloading helps indeed but strange we need to do that....

**Comment by mediacutlet** [comment]
This has become a real problem for me lately. Reloading the integration doesn't fix it. After a few recent power outages and having to reconfigure all my localtuya plugs I've given up on this integration in exchange for 100% natively local wifi plugs.

**Comment by FragMenthor** [comment]
I have the same problem, only with certain plugs, and found out that the Product ID in the tuya cloud is the same for all 4; they worked before, and now I can only get them back after a restart with the reloading of the intergation (process that I can only do once, the second time I try it cannot reload).

![TuyaPlugs](https://github.com/rospogrigio/localtuya/assets/74264069/76f628b3-9a5a-4fe6-ad25-efe4eced3353)

These are my plugs, can you check, please, if they are the same?
I have tryed changing manually the protocol: 3.3 works (is the default), 3.1 doesn't work, 3.2 seems also to work (both in 3.3 and 3.2 versions, only get them available after a reload of the integration)
Any solution for this?
Thanks in advance!

**Comment by ZTHawk** [comment]
Hello, I have the same issue. I have two devices. One is working the other is not.
Reloading LocalTuya makes the device work again.

**Comment by FragMenthor** [comment]
> Hello, I have the same issue. I have two devices. One is working the other is not. Reloading LocalTuya makes the device work again.

Can you check the info I posted above and compare the product information in the tuya cloud, please?

**Comment by majkers** [comment]
@FragMenthor seems you are right!

![image](https://github.com/rospogrigio/localtuya/assets/21099773/b98e792b-742a-4490-83e1-40819e7f87ce)

**Comment by FragMenthor** [comment]
@rospogrigio anything we can do to help to debug why this happens only to these specific devices?

**Comment by zolakt** [comment]
Same issue after a power outage, same error.
Reloading the integration doesn't help in my case.
I tried editing the device config (which usually helps), but that doesn't help either.

Does any one have another suggestion?
The plug is tucked behind a refrigerator, so it's not really practical to get to it.
It does work in Smart Life however.

The only idea I have is to delete it, and add it again.
