### ISSUE TITLE
Error when trying to add dpids in edit

### ISSUE THREAD

**Issue by stain3565** [rospogrigio/localtuya#1386]
## Environment

- Localtuya version: plugin version from HACS, v5.1.0 
- Home Assistant Core version: 2023.5.2
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [x] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

1. Edit device in integration 
2. Select available dpids for current, voltage etc
3. Click submit

## Provide Home Assistant traceback/logs

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/localtuya/config_flow.py:743
Integration: LocalTuya integration (documentation, issues)
First occurred: 23:26:17 (3 occurrences)
Last logged: 23:31:07

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 743, in async_step_configure_entity
    ent_reg = await er.async_get_registry(self.hass)
AttributeError: module 'homeassistant.helpers.entity_registry' has no attribute 'async_get_registry'

```

**Comment by rx7guy** [comment]
I believe I am experiencing the same issue.

**Comment by shaggy6156** [comment]
Count me in with the same issue...

**Comment by Poci** [comment]
Same issue

**Comment by Tomasz45** [comment]
Mam taki sam problem

**Comment by Spotje1981** [comment]
Same here.
Also adding a device not possible, will loop because th e checkbox "Do not add any more entities" is not doing anything here :S

**Comment by shaggy6156** [comment]
I have tried rolling back from 2023.5.3 to 2023.5.0 testing each rollback and the issue still exists. I cannot modify a device in tuyalocal. I can add a new device if I put one on. My tuya iot account is active. All devices in tuyalocal still operate.

**Comment by Rumbaar** [comment]
Experiencing this also, cannot update existing device.  The last time I was able to edit and save a device, was around 24th April 2023.  If that helps tracking HAC and/or HA versions.

**Comment by Slippery-Silvia** [comment]
Same problem for me also.

**Comment by oven-lab** [comment]
Hey there, @sftgunner has resolved this issue with a pull request. I have also used his solution in a pr i made. Although @rospogrigio haven't seem to notice either the problem or the pull requests yet.

async_get_registry has been deprecated since 2023.05. So the solution is to either install the integration manually with these fixes, or to downgrade to anything before 2023.05.
