### ISSUE TITLE
Unknown error occurred during existing device edit

### ISSUE THREAD

**Issue by Jabber-se** [rospogrigio/localtuya#1404]
## The problem
Unknown error occurred during existing device update

## Environment
RPI 3 haos
- Localtuya version: 5.1.0
- Home Assistant Core version: 2023.5.3 
- [] Does the device work using the Home Assistant Tuya Cloud component ? NO
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? NO
- [] Was the device working with earlier versions of localtuya ? NONE
- [] Are you using the Tuya/SmartLife App in parallel ? YES

## Steps to reproduce
1. run settings of localtuya
2. select Edit a device
3. select needed device from the list
4. make a changes of selectel devise
5. push Confirm batton of the second page to have error

## Provide Home Assistant traceback/logs

```
Logger: aiohttp.server
Source: custom_components/localtuya/config_flow.py:743
Integration: LocalTuya integration (documentation, issues)
First occurred: 11:25:02 (1 occurrences)
Last logged: 11:25:02

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 241, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 743, in async_step_configure_entity
    ent_reg = await er.async_get_registry(self.hass)
AttributeError: module 'homeassistant.helpers.entity_registry' has no attribute 'async_get_registry'
```

## Additional information
similar issue https://community.home-assistant.io/t/error-async-get-registry-after-core-2023-5-0/567951/6

![localtuya_error_update_device](https://github.com/rospogrigio/localtuya/assets/81160361/8c496c59-4775-47da-b7f1-d7e2e1f2289e)

**Comment by Jabber-se** [comment]
Work arround -

localtuya/config_flow.py line 743 replaced
from
ent_reg = await er.async_get_registry(self.hass)
to
ent_reg = er.async_get(self.hass)

"Edit a device" update start to works

**Comment by oven-lab** [comment]
fixed since version 5.2.0 :)

**Comment by muzzthegreat** [comment]
Thank you. I was also having this issue, but it is now resolved.
