### ISSUE TITLE
Cannot add to local tuna Unexpected exception: [Errno 113] 

### ISSUE THREAD

**Issue by anubis-code** [rospogrigio/localtuya#1407]
This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:1172
Integration: LocalTuya integration (documentation, issues)
First occurred: 16:15:25 (7 occurrences)
Last logged: 16:28:15

Unexpected exception: [Errno 113] Connect call failed ('192.168.1.244', 6668)
Unexpected exception: [Errno 113] Connect call failed ('192.168.1.153', 6668)
Unexpected exception: [Errno 113] Connect call failed ('192.168.1.210', 6668)
Unexpected exception: [Errno 110] Connect call failed ('192.168.1.197', 6668)
Unexpected exception: [Errno 113] Connect call failed ('192.168.1.185', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 582, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 240, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1172, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.244', 6668)

**Comment by kenhoppla** [comment]
Have the same issue. Tried literally everything.

**Comment by phoenixfire425** [comment]
I recently started get the same.  And many of the bulbs that I have are not responding now.

**Comment by mat2c** [comment]
Same issue with T & H Sensor and Contact Sensor.

**Comment by DocDrydenn** [comment]
Receiving the same error trying to add a new device.

**Comment by Romero-KCBS2003** [comment]
Same here:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:1183
Integration: LocalTuya integration (documentation, issues)
First occurred: 07:21:40 (1 occurrences)
Last logged: 07:21:40

Unexpected exception: [Errno 110] Connect call failed ('192.168.5.89', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1183, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.5.89', 6668)

**Comment by Atilvass** [comment]
I am having the same problem when adding new devices, I have tried several ways but it still returns the same error
