### ISSUE TITLE
Can't connect to devices in setup

### ISSUE THREAD

**Issue by DansGitHubUsername** [rospogrigio/localtuya#141]
Hi
Thanks for the great work, really looking forward to local control ability.
I’m having issues trying to see / add devices. I have not yet successfully added a device.
I’ve using a Raspberry Pi 4 8gb with a fresh install of Raspberry Pi OS 32 bit; running Home Assistant Core v 0.117.4 on a Docker container with Portainer.  Port 8123 is port forwarded.
I initially downloaded and copied across localtuya 3.03; and more recently, 3.01.
After clicking on the + button under Home Assistant - Integrations, and selecting LocalTuya, the search fails to find any devices on my local network.  I have attempted to manually enter the IP, Device ID and Local Key, and friendly name, for both 3.1 and 3.3. It searches for about 2 minutes, then fails.
I’m attempting to connect to a Deta Single Gang Light Switch.  I’ve also attempted to connect to others of these same switches.  The switches still have the original firmware with updates, and have not been flashed.
I’m using Google WiFi and have confirmed the IP addresses are correct.  I’ve also attempted to use the name that appears in the Google WiFi as the “Friendly Name”.
On the last attempt, I received two error logs as follows:

Logger: custom_components.localtuya.config_flow 
Source: custom_components/localtuya/pytuya/__init__.py:593 
Integration: LocalTuya (documentation) 
First occurred: 9:01:07 PM (1 occurrences) 
Last logged: 9:01:07 PM 

Unexpected exceptionTraceback (most recent call last):  File "/config/custom_components/localtuya/config_flow.py", line 238, in async_step_basic_info    self.dps_strings = await validate_input(self.hass, user_input)  File "/config/custom_components/localtuya/config_flow.py", line 166, in validate_input    interface = await pytuya.connect(  File "/config/custom_components/localtuya/pytuya/__init__.py", line 593, in connect    _, protocol = await loop.create_connection(  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection    raise exceptions[0]  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection    sock = await self._connect_sock(  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock    await self.sock_connect(sock, address)  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect    return await fut  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb    raise OSError(err, f'Connect call failed {address}')TimeoutError: [Errno 110] Connect call failed ('192.168.86.22', 6668) 

 

Logger: custom_components.localtuya.common 
Source: custom_components/localtuya/pytuya/__init__.py:593 
Integration: LocalTuya (documentation) 
First occurred: 8:54:48 PM (4 occurrences) 
Last logged: 9:01:32 PM 

Connect to 192.168.86.180 failedTraceback (most recent call last):  File "/config/custom_components/localtuya/common.py", line 141, in _make_connection    self._interface = await pytuya.connect(  File "/config/custom_components/localtuya/pytuya/__init__.py", line 593, in connect    _, protocol = await loop.create_connection(  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection    raise exceptions[0]  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection    sock = await self._connect_sock(  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock    await self.sock_connect(sock, address)  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect    return await fut  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb    raise OSError(err, f'Connect call failed {address}')TimeoutError: [Errno 110] Connect call failed ('192.168.86.180', 6668)

Thank you in advance

**Comment by postlund** [comment]
Since you get a timeout error, there's something wrong with the network connectivity. First of all, how have you configured the network in docker? It sounds to me like you run in NAT mode or something. You should try running in host mode, so your container gets access to the same traffic as the host (e.g. broadcasts the tuya devices send, which are used for discovery). You should try to attach to the container and see if you can ping your gang switch from there.

**Comment by postlund** [comment]
Bump
