### ISSUE TITLE
Failed to get status: could not decrypt data: wrong local_key?

### ISSUE THREAD

**Issue by s1mpl316** [rospogrigio/localtuya#1432]
Hi, 

 iam a newbie und absoluty new in local tuya. its my first device. 

The developer account is activatet and the device is online. 

its this device: https://www.amazon.de/Bew%C3%A4sserungscomputer-Intelligente-Automatische-Bew%C3%A4sserungssteuerung-Sprachsteuerung/dp/B09MRN3P3H/ref=sr_1_17_mod_primary_new?keywords=bew%C3%A4sserungscomputer+2+ausg%C3%A4nge&qid=1686769506&sr=8-17 

The device is shown in local tuya, but when i will set the configure for this device i get:

bf9...wwa] Failed to get status: could not decrypt data: wrong local_key? (exception: Expecting value: line 1 column 1 (char 0))
Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 953, in _decode_payload
    json_payload = json.loads(payload)
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 863, in detect_available_dps
    data = await self.status()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 795, in status
    status = await self.exchange(DP_QUERY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 780, in exchange
    payload = self._decode_payload(msg.payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 955, in _decode_payload
    raise DecodeError(
custom_components.localtuya.pytuya.DecodeError: could not decrypt data: wrong local_key? (exception: Expecting value: line 1 column 1 (char 0))

**Comment by NeoFax75** [comment]
Same issue here.  I just got this error message today after updating like a week or so ago.
