### ISSUE TITLE
Error doing job: Exception in callback

### ISSUE THREAD

**Issue by Anashost** [rospogrigio/localtuya#1447]
This error happens every couple of seconds, devices seems to work fine tho!

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/localtuya/discovery.py:67
Integration: LocalTuya (documentation, issues)
First occurred: 11:51:43 AM (6 occurrences)
Last logged: 11:52:08 AM

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 185, in finalize
    data = self._ctx.finalize()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 222, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1169, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
           ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 0: invalid start byte

```

**Comment by PixelPingin** [comment]
Same version setup and the same exeption repeats in the log.

In my case localtuya is not able to discover devices in the same subnet athought UDP packets from devices can be captured on the interface (and then script fails in decrypting it?)

```
2023-07-04 15:59:00.160 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 185, in finalize
    data = self._ctx.finalize()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 222, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1169, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
           ^^^^^^^^^^^^^
```

**Comment by Anashost** [comment]
@PixelPingin seems like the devs are not answering any issues in past couple of months for som reason.

I moved yesterday to Tuya Local (different than Local Tuya) it's an active integration and they release updates more frequent, and logs are clean so far.

If you want to move and  you face problems with adding some devices, try changing the protocol manually as i struggled with adding some devices until i did that.

**Comment by PixelPingin** [comment]
Oooooh! Thanks for the tip. In turn I will try local-tuya instead.

I'm not much of a programmer, so I have no idea if python would throw the error we have in the log if the file is missing.
Anyway, the folder /usr/local/lib/python3.11/ is completely missing from Home Assist
And I was just about to populate it with all the necessary dependencies.
Which didn't seem like a system solution to me and certainly not supported anymore.

Thanks a lot @Anashost  , you've most likely saved me a lot of time now and in the future.

**Comment by Anashost** [comment]
I don't have a lot of programming skills either so i wouldn't touch HA files 😅.
You're welcome @PixelPingin  and i hope all your devices are already supported in the [Tuya-Local](https://github.com/make-all/tuya-local) integration.

**Comment by dominikprucha** [comment]
I have the same error. Any solution?

**Comment by DieBreuers** [comment]
Hi, Ive got the same errors... is there any Idea ti fix it?

**Comment by Anashost** [comment]
> Hi, Ive got the same errors... is there any Idea ti fix it?

I personally moved to [Tuya Local](https://github.com/make-all/tuya-local) it's more stable and development is active.

**Comment by solidsnakespirit** [comment]
Hi !

If you are seeing thousands of UnicodeDecodeError or JSON errors in your logs related to discovery.py, here is the most effective "Dirty Fix" to silence the logs while keeping your existing devices working.

The Problem:
LocalTuya's discovery script tries to decrypt/decode every UDP packet on ports 6666/6667. If it encounters malformed packets, it crashes and spams the logs.

The Solution:
Disable the discovery function manually in the code. Your already configured devices will continue to work perfectly as they communicate via direct IP.

    Navigate to /config/custom_components/localtuya/.

    Open discovery.py with a text editor.

    Locate the function def datagram_received(self, data, addr): (around line 62).

    Add a return statement immediately at the beginning of the function:

Python

    def datagram_received(self, data, addr):
        """Handle received broadcast message."""
        return  # <--- Add this line here (with 8 spaces indentation)
        data = data[20:-8]
        try:
            data = decrypt_udp(data)

    Save the file and Restart Home Assistant.

Result:
The discovery process will stop immediately upon receiving any packet, preventing any decoding attempt. The log spam will disappear instantly.

Here we go ! Fixed. ^^
