### ISSUE TITLE
Error message: The length of the provided data is not a multiple of the block length 

### ISSUE THREAD

**Issue by lennon101** [rospogrigio/localtuya#1452]
-->
## The problem
Reopening issue number [#78](https://github.com/rospogrigio/localtuya/issues/78) which was closed in 2020. I have on the latest version (v5.2.1) and experiencing the exact same probelm. My home-assistant log has a repeating error (seems to be stuck in a loop) with the following contents: 

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 1035, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte
2023-07-07 14:10:02.176 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
  File "/usr/lib/python3.10/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 185, in finalize
    data = self._ctx.finalize()
  File "/usr/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 222, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:
```

## Environment
- Localtuya version:  v5.2.1
- Home Assistant Core version: Home Assistant 2023.7.1
- [x] Does the device work using the Home Assistant Tuya Cloud component ?
- [x] Was the device working with earlier versions of localtuya ?

**Comment by lennon101** [comment]
Just updating the errror message to include everything in its entirety. It's very possible this is linked to only some devices. The issue is, I can't seem to be able to see in the log which device is sending the data that can't be decoded. Any help with this? 

```
2023-07-09 13:07:10.955 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 186, in finalize
    data = self._ctx.finalize()
           ^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 222, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 1169, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
           ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 2: invalid start byte
```

**Comment by sharkwsk** [comment]
Anyone able to fix this issue, I get the same error messages and some devices are not discovered in localtuya

**Comment by sharkwsk** [comment]
Thanks heaps @paris-ci - this new integration works perfectly

**Comment by sowmyagowri** [comment]
Thanks a ton @paris-ci !!!!

**Comment by lkroeker** [comment]
> Use this instead https://github.com/xZetsubou/hass-localtuya

Not sure of the best practice for switching to a fork, so I just replaced the tuyalocal directory with the latest one linked there, rebooted, and the messages have now stopped. Seemingly a direct replacement without needing to reconfigure anything in HA.  Thanks! 🙏 

I was having tens of thousands of lines in my logs with these error messages. Whatever's causing this seems to be being ignored in this original repo?

**Comment by AABDELHAKIM** [comment]
> > Use this instead https://github.com/xZetsubou/hass-localtuya
> 
> Not sure of the best practice for switching to a fork, so I just replaced the tuyalocal directory with the latest one linked there, rebooted, and the messages have now stopped. Seemingly a direct replacement without needing to reconfigure anything in HA. Thanks! 🙏
> 
> I was having tens of thousands of lines in my logs with these error messages. Whatever's causing this seems to be being ignored in this original repo?

can you explain to me in detail how did you do that ? i am facing the same issue but with very limited programming / coding knowledge :)

**Comment by Nisbo** [comment]
I also had millions of this entries in my log.
Switching was easy

Go to HACS
search for local tuya
on the right click on the 3 dots and select delete
there will be a warning that you shall remove the config
click on ignore
click on the install link (in the readme) from the new repo
add the repo
download the repo
restart HA

nothing was lost :)
