### ISSUE TITLE
Changing fan speed cause device to be unavailable

### ISSUE THREAD

**Issue by tekdru** [rospogrigio/localtuya#1495]
## The problem

Device:
Ceiling Fan Dimmer Switch DS03 
Firmware: 3.3

The on/off function works fine for both the light and fan but whenever I try to change the fan speed, both fan and light becomes "unavailable".

## Environment

- Localtuya version:  v5.2.1
- Home Assistant Core version: Home Assistant 2023.9.2
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ?
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [] Are you using the Tuya/SmartLife App in parallel ?

I haven't tried Tuya Cloud Component, TinyTuya or any previous version of local Tuya.

## Provide Home Assistant traceback/logs

```
2023-09-14 14:18:14.152 ERROR (MainThread) [custom_components.localtuya.common] [720...ae9] Failed to set DP 3 to 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 321, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 842, in set_dp
    return await self.exchange(CONTROL, {str(dp_index): value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-09-14 14:18:16.772 WARNING (MainThread) [custom_components.localtuya.common] [720...ae9] Disconnected - waiting for discovery broadcast
2023-09-14 14:19:04.903 ERROR (MainThread) [custom_components.localtuya.common] [720...ae9] Failed to set DP 3 to 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 321, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 842, in set_dp
    return await self.exchange(CONTROL, {str(dp_index): value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-09-14 14:19:09.635 WARNING (MainThread) [custom_components.localtuya.common] [720...ae9] Disconnected - waiting for discovery broadcast
2023-09-14 14:20:04.080 ERROR (MainThread) [custom_components.localtuya.common] [720...ae9] Failed to set DP 3 to 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 321, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 842, in set_dp
    return await self.exchange(CONTROL, {str(dp_index): value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-09-14 14:20:06.979 WARNING (MainThread) [custom_components.localtuya.common] [720...ae9] Disconnected - waiting for discovery broadcast
2023-09-14 14:21:03.287 ERROR (MainThread) [custom_components.localtuya.common] [720...ae9] Failed to set DP 3 to 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 321, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 842, in set_dp
    return await self.exchange(CONTROL, {str(dp_index): value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-09-14 14:21:06.372 WARNING (MainThread) [custom_components.localtuya.common] [720...ae9] Disconnected - waiting for discovery broadcast
2023-09-14 14:29:05.367 ERROR (MainThread) [custom_components.localtuya.common] [720...ae9] Failed to set DP 3 to 4
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 321, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 842, in set_dp
    return await self.exchange(CONTROL, {str(dp_index): value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-09-14 14:29:07.312 ERROR (MainThread) [custom_components.localtuya.common] [720...ae9] Failed to set DP 1 to True
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 321, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 842, in set_dp
    return await self.exchange(CONTROL, {str(dp_index): value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2023-09-14 14:29:08.142 WARNING (MainThread) [custom_components.localtuya.common] [720...ae9] Disconnected - waiting for discovery broadcast
2023-09-14 14:29:10.874 ERROR (MainThread) [custom_components.localtuya.common] [720...ae9] Failed to set DP 1 to True
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 387, in acquire
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 321, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 842, in set_dp
    return await self.exchange(CONTROL, {str(dp_index): value})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
```

**Comment by grzesw72** [comment]
my fix based on https://community.home-assistant.io/t/local-tuya-fan-controller/306985/45.

fan.py
line 133+: function definition async_set_percentage (original)
```
    async def async_set_percentage(self, percentage):
        """Set the speed of the fan."""
        _LOGGER.debug("Fan async_set_percentage: %s", percentage)

        if percentage is not None:
            if percentage == 0:
                return await self.async_turn_off()
            if not self.is_on:
                await self.async_turn_on()
            if self._use_ordered_list:
                await self._device.set_dp(
                    self._dps_type(
                        percentage_to_ordered_list_item(self._ordered_list, percentage)
                    ),
                    self._config.get(CONF_FAN_SPEED_CONTROL),
                )
                _LOGGER.debug(
                    "Fan async_set_percentage: %s > %s",
                    percentage,
                    percentage_to_ordered_list_item(self._ordered_list, percentage),
                )

            else:
                await self._device.set_dp(
                    self._dps_type(
                        math.ceil(
                            percentage_to_ranged_value(self._speed_range, percentage)
                        )
                    ),
                    self._config.get(CONF_FAN_SPEED_CONTROL),
                )
                _LOGGER.debug(
                    "Fan async_set_percentage: %s > %s",
                    percentage,
                    percentage_to_ranged_value(self._speed_range, percentage),
                )
            self.schedule_update_ha_state()
```
change to
```
    async def async_set_percentage(self, percentage):
        """Set the speed of the fan."""
        _LOGGER.debug("Fan async_set_percentage: %s", percentage)

        if percentage is not None:
            if percentage == 0:
                return await self.async_turn_off()
            if not self.is_on:
                await self.async_turn_on()
            if self._use_ordered_list:
                await self._device.set_dp(
#fix https://community.home-assistant.io/t/local-tuya-fan-controller/306985/45
                    percentage_to_ordered_list_item(self._ordered_list, percentage)
                    ,
                    self._config.get(CONF_FAN_SPEED_CONTROL),
                )
                _LOGGER.debug(
                    "Fan async_set_percentage: %s > %s",
                    percentage,
                    percentage_to_ordered_list_item(self._ordered_list, percentage),
                )

            else:
                await self._device.set_dp(
#fix https://community.home-assistant.io/t/local-tuya-fan-controller/306985/45
                    math.ceil(
                        percentage_to_ranged_value(self._speed_range, percentage)
                    ),

                    self._config.get(CONF_FAN_SPEED_CONTROL),
                )
                _LOGGER.debug(
                    "Fan async_set_percentage: %s > %s",
                    percentage,
                    percentage_to_ranged_value(self._speed_range, percentage),
                )
            self.schedule_update_ha_state()
```

**Comment by tekdru** [comment]
Thanks @grzesw72,

I just try using your code but I'm still getting the same "Unavailable" message after trying to change fan speed.  Am I missing something else?

**Comment by grzesw72** [comment]
Hello.
I'm moved to fork -> https://github.com/xZetsubou/hass-localtuya


śr., 21 lut 2024 o 18:26 tekdru ***@***.***> napisał(a):
