### ISSUE TITLE
Error: "An unknown error occurred. See log for details." when trying to add a device with a non-alphanumeric local key

### ISSUE THREAD

**Issue by kauspethe** [rospogrigio/localtuya#1513]
I got a new tuya contact sensor and it has a different local key compared to all my older devices. Looks like the key now contains special characters. The key now contains characters like ( / !. I am unable to add this device to LocalTuya and keep getting the above error. Below are the logs for reference. Can someone guide me how I can fix this? I'm pretty new to this. Help appreciated.

```
2023-10-07 22:30:16.934 ERROR (MainThread) [custom_components.localtuya.config_flow] Unexpected exception: [Errno 113] Connect call failed ('192.168.1.116', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.116', 6668)
```

**Comment by MenzeJan** [comment]
I got the same error when adding a nedis smart plug:

This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:595
Integration: LocalTuya (documentation, issues)
First occurred: 19:26:03 (2 occurrences)
Last logged: 19:31:44

Unexpected exception: [Errno 113] Connect call failed ('192.168.68.106', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.68.106', 6668)

![image](https://github.com/rospogrigio/localtuya/assets/144695818/9673cc3e-b0c0-436d-b781-cd114ae90e3a)

**Comment by lowerclasswarfare** [comment]
Same problem adding a few Enbrighten smart plugs, and 3 Feit bulbs.

`This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:595
Integration: LocalTuya (documentation, issues)
First occurred: 10:22:52 PM (5 occurrences)
Last logged: 10:31:20 PM

Unexpected exception: [Errno 110] Connect call failed ('192.168.1.223', 6668)
Unexpected exception: [Errno 110] Connect call failed ('192.168.1.241', 6668)
Unexpected exception: [Errno 110] Connect call failed ('192.168.1.102', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.1.223', 6668)
`

**Comment by aloha-schwabe** [comment]
Same issue for four different contact sensors 
Already tried to modify the local keys via the tuya api which did not work - Seams like that that the non alpha numeric characters are not allowed…

**Comment by arnoprod** [comment]
Same issue for me. I've tryed to renitialize 3 times, but local_key always generated with non alpha numeric characters. :(

**Comment by arnoprod** [comment]
it works fine with my other tuya device that generate a code only on alpha numeric.

**Comment by Potkan8** [comment]
Same issue :/ After I changed my wifi settings, it generated a new local key for my thermostat - to my surprise, non-aplhanumerical (haven't seen it yet, until now I had only alphanumerical) and I can't edit edit it in LocalTuya.

**Comment by aloha-schwabe** [comment]
Did anybody find a solution for this?

**Comment by antelidberg** [comment]
I tested converting the local key from string to hex which produces a hex string 32 bytes long. Connection to my lamps work but there seems to be an issue fetching the DP’s. Haven’t sorted that out yet. 
Please try this method out and let me know if you get it to work.

**Comment by kauspethe** [comment]
@antelidberg Yes, seems like you are on to something. I too was able to connect to my switch after converting the localkey to a hex string. However, I am also struggling with the DP's. All DP's end up showing value = -1. I'll keep trying and see if I can sort that out.

**Comment by shallowal** [comment]
Same problem I think with an Aliexpress Temperature/Humidity Sensor. First time user of Tuya devices and Localtuya. Localkey has characters from the whole ascii character set including spaces.

**Comment by koutsie** [comment]
Same issue with an random ali t&h sensor haha:
```
Unexpected exception: [Errno 113] Connect call failed ('192.168.1.162', 6668)

Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.162', 6668)
```

**Comment by cescofry** [comment]
I do not have enough experience with this, but it looks like the tuya API has switched encoding on the generated local key and this library is not able to deal with the additional character set. When looking at the the dev portal the local keys do contain punctuation characters, contrary of what it used to be just alphanumeric (as reported, I could not actually very).

Is there any active developers that can take this in or at least give instructions on how to fix it?

**Comment by Rolax68** [comment]
Same issue for me. I have bought 3 Tuya door sensors recently. Local_key are always generated with non alpha numeric characters and therefore I can't get Tuya local working. Please rise priority for this issue.

**Comment by Maxxxel** [comment]
Same issue for me. Any Dev know about this breaking thing??

**Comment by Rolax68** [comment]
With each new Tuya device traded this will be increasingly becoming a bigger and is a really breaking issue. 
It is clear that everyone will be affected soon. Developers please consider to act!

**Comment by zerpex** [comment]
Same error here. Only functional work-around : downgrade to 2023.10.3

Regards.

**Comment by Mr-Alicates** [comment]
I'm affected by this issue too:

I have confirmed I have local keys with non alphanumeric numbers on my new devices. An existing device seems stop still work fine.

I'm running 
HA 2023.12.3
Localtuya 5.2.1

Devices are 2 standard humidity and temperature sensors.

**Comment by menoscuatro** [comment]
This is another "me too" message.

I have local key with non alphanumeric numbers on my new device. Humidity/temperature sensor
Two existing devices working fine

I'm running
HA 2023.12.3
Localtuya 5.2.1

**Comment by Blackspell01** [comment]
Is there a solution to this?

**Comment by yassirbisteni** [comment]
Hi @Maxxxel is there any solution to this? thanks

**Comment by Shwalamazula** [comment]
I am running into an Error 113 as well. I have 3 Tuya devices, 2 Feit overhead shop lamps for the grage, and a Sunbeam mattress heater. All local keys that I pulled from Tuya IoT have special characters in them. 

```
This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:595
Integration: LocalTuya (documentation, issues)
First occurred: 3:50:22 PM (4 occurrences)
Last logged: 3:58:58 PM

Unexpected exception: [Errno 113] Connect call failed ('192.168.1.211', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.211', 6668)
```

**Comment by boheme61** [comment]
> @antelidberg Yes, seems like you are on to something. I too was able to connect to my switch after converting the localkey to a hex string. However, I am also struggling with the DP's. All DP's end up showing value = -1. I'll keep trying and see if I can sort that out.

Which Character encoding, did you use, and did you use delimiter when you encoded it to HEX ?

Sitting here with 4 new device i can't add :(

**Comment by antelidberg** [comment]
@boheme61: Can´t remember the encoding and I ran into the same problem with DP's as you. For some reason it started working using the new format after I added the first device and I later (after some tampering with the first) successfully added the devices I had using the GUI and the new format for the localkey.

**Comment by dzabel** [comment]
I was able to add my T&H Sensor regardless of the non-alphanumeric chars of the password. See my comment here for more details: https://github.com/rospogrigio/localtuya/issues/1426#issuecomment-1890196293
