### ISSUE TITLE
Cannot Connect to device (switch device) - cannot use Cloud API with the Tuya CE (central europe) datacenter 

### ISSUE THREAD

**Issue by BenoitVH** [rospogrigio/localtuya#1578]
## The problem

Using a fresh localtuya install (v5.2.1) I run into 2 problems :
1) the Cloud API section cannot be used on the CE (central europe) datacenter
2) connecting the device (Din Rail Circuit breaker, merely a switch) without the cloud API fails and logs an error

## Environment
- Localtuya version: <v5.2.1> 
- Home Assistant Core version: <2023.11.3> running on a raspberry pi 4 with 4GB
- [x, yes]      Does the device work using the Home Assistant Tuya Cloud component ?
- [x, yes]      Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command?  
- [no]          Was the device working with earlier versions of localtuya ? this is my first attempt to use localtuya
- [x, yes]      Are you using the Tuya/SmartLife App in parallel ?

## Steps to reproduce
Just followed the steps documented in the readme install section:
1) When adding the integration I cannot configure the Cloud API account since my cloud/devices are connected to the Tuya CE (central europe) datacenter; this option is not available in the dialog window. I tried to go ahead using the EU Datacenter (I'm based in europe) but then I receive the following error "Failed to retrieve device list. Error 1106: permission deny". The same data and credentials for the CE datacenter work in the tinytuya code (tinytuya wizard)

2) since one can ignore the Tuya cloud API, I proceed with adding the device. The device is discovered automatically and appears in the localtuya dialog window. There I enter all the parameters (id, key, IP, name, version, dps). These are exactly the same as the ones I use in tinytuya where they function correctly. 
I tried several options: with/without dps, different protocol versions (although it needs to be 3.3), restart HA ...
But invariably in localtuya I get an error: "An unknown error occurred. See log for details."
see log below.

## Provide Home Assistant traceback/logs

This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:595
Integration: LocalTuya (documentation, issues)
First occurred: 10:36:20 PM (2 occurrences)
Last logged: 11:04:50 PM

Unexpected exception: [Errno 113] Connect call failed ('192.168.0.191', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.191', 6668)

## Additional information

Thanks for any support in solving this issue !

**Comment by BenoitVH** [comment]
Strange... am I the only HA user with Tuya devices connected to the CE datacenter ?

**Comment by BenoitVH** [comment]
Hi,
This week I received a message to update to the latest version (v5.2.1). As previous updates did not solve the "add device" issue (item 2 above) I was still quite sceptical if I would ever get this to work...
But behold, for no apparent reason, my switch device was now recognized. So for now, I'm happy  :-)

As for the other item: I used the method documented by Jason Cox to download the local keys as the Local Tuya still doesn't recognize the "Central Europe" (CE) datacenter 

![Untitled](https://github.com/rospogrigio/localtuya/assets/71166296/20d3bf55-7787-49dd-ab0c-7a857d83e038)
