### ISSUE TITLE
PIR Motion Sensor will not Add.

### ISSUE THREAD

**Issue by NZ-Neil** [rospogrigio/localtuya#1584]
## Environment

- Localtuya version:  
- Home Assistant Core version:  
- [x] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ?  Not installed
- [] Was the device working with earlier versions of Localtuya ? Which one?  First use of Localtuya
- [] Are you using the Tuya/SmartLife App in parallel ?  No

## Steps to reproduce

1. Installed Localtuya via HACS with no issues.
2. Retrieved the device's "local_key" from the Tuya iOT developer platform
3. clicked "Configure:
4. Selected the discovered device that matched the device on the Tuya iOT platform.
5. Added the "Name" for the device
6. Pasted as clear text the "local_key" from the Tuya iOT
7. Selected protocal 3.3 which supports sensors
8. Received "unknown error occurred"
## Provide Home Assistant traceback/logs

```
put your log output between these markers
```
2023-12-09 11:33:26.972 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 186, in finalize
    data = self._ctx.finalize()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 222, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1163, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
           ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 3: invalid start byte
2023-12-09 11:33:27.689 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 186, in finalize
    data = self._ctx.finalize()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 222, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1163, in _read_ready
    self._protocol.datagram_received(data, addr)

## Additional information

The issue appears to be with using the "local_key" possibly due to special characters not being escaped?
![Screenshot 2023-12-09 121711](https://github.com/rospogrigio/localtuya/assets/148874712/9acdd4a9-d8dd-4b8c-8d20-366029c04661)

**Comment by camostar** [comment]
same here

**Comment by bartvosman** [comment]
This is probably related to: https://github.com/rospogrigio/localtuya/issues/1058

> if that motion sensor is battery powered, well, you only have 10 second to add it to localtuya and even if you manged to add it, its not going to work, you will be using the official tuya integration for these stuff and unfortunately that's how it works.... unless that PIR sensor is USB powered (which majority of these tuya wifi based sensors have), then the device is always available over the network and you can add the sensors without issue, not to mention that reaction time of the sensor is very fast 1-2 seconds after it detects a motion vs around 10-20seconds in battery power.

**Comment by berilevi** [comment]
I see the same issue, unable to add.
