### ISSUE TITLE
Fan and Climate entities not provided in 2024.1.0b0

### ISSUE THREAD

**Issue by sambarlick** [rospogrigio/localtuya#1601]
## Environment

- Localtuya version:   v5.2.1
- Home Assistant Core version:   Core 2024.1.0b0
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

1.
2. 
3.

## Provide Home Assistant traceback/logs

```
Logger: homeassistant.components.fan
Source: helpers/entity_platform.py:368
Integration: Fan (documentation, issues)
First occurred: 16:16:11 (4 occurrences)
Last logged: 18:19:20

Error while setting up localtuya platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 406, in capability_attributes
    FanEntityFeature.SET_SPEED in supported_features
TypeError: argument of type 'int' is not iterable

```

## Additional information
 My entities are set to 'str' not 'int'

**Comment by LEJOUI** [comment]
Looks like is also reporting on this #1596. Also having this issue.

**Comment by sambarlick** [comment]
> Looks like #1596 is also reporting on this. Also having this issue.

I saw that but mine was working prior to be 2024.1.0b0 update.

**Comment by Nemesis24** [comment]
for fans this is the same

**Comment by LEJOUI** [comment]
> > Looks like #1596 is also reporting on this. Also having this issue.
> 
> 
> 
> I saw that but mine was working prior to be 2024.1.0b0 update.

Yeah, you're right. I downgraded back to 2023.12.X and there it works. Looks like changes are made to the climate integration. Not a developer, hope that someone has the time to look in to it.

**Comment by LEJOUI** [comment]
See also https://github.com/home-assistant/core/issues/106522

**Comment by sambarlick** [comment]
> > > Looks like #1596 is also reporting on this. Also having this issue.
> > 
> > 
> > I saw that but mine was working prior to be 2024.1.0b0 update.
> 
> Yeah, you're right. I downgraded back to 2023.12.X and there it works. Looks like changes are made to the climate integration. Not a developer, hope that someone has the time to look in to it.

Yea it's definitely something changed in core affecting the custom integrations.

Hopefully these issues can be resolved, as I thought this was the point of the betas, to allow devs time to change things before the full release.
