### ISSUE TITLE
Error on add a new device. Tuya WiFi Temperature and Humidity Sensor TH08

### ISSUE THREAD

**Issue by dmitrkov** [rospogrigio/localtuya#1617]
## The problem
Error on add a new device. Tuya WiFi Temperature and Humidity Sensor TH08
https://www.aliexpress.com/item/1005005869866043.html

## Environment
- Localtuya version: 5.2.1
- Home Assistant Core version: 2024.1.2
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [x] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

1. Add new device
2. Pick automatically discovered devic
3. Set name and local id
4. Send

## Provide Home Assistant traceback/logs
```
Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:595
Integration: LocalTuya integration (documentation, issues)
First occurred: 12:35:14 (5 occurrences)
Last logged: 12:53:43

Unexpected exception: [Errno 113] Connect call failed ('192.168.50.55', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.50.55', 6668)
```

**Comment by Shaolo** [comment]
I don't know what happened, but most of us seem to be in this boat. The devices show up, but they can't be added to HA.

**Comment by junemacaspac** [comment]
I got the same issues

**Comment by aizmob** [comment]
No luck with this device too

**Comment by dzabel** [comment]
i was able to add mibe using this way: https://github.com/rospogrigio/localtuya/issues/1426#issuecomment-1890196293

**Comment by dmitrkov** [comment]
> i was able to add mine using this way: [#1426 (comment)](https://github.com/rospogrigio/localtuya/issues/1426#issuecomment-1890196293)

Hmm, need to try. Thanks

**Comment by dmitrkov** [comment]
> i was able to add mine using this way: [#1426 (comment)](https://github.com/rospogrigio/localtuya/issues/1426#issuecomment-1890196293)

It was really possible to add the device this way. Only battary Id in my case is 4. But these sensors are permanently unavailable. Exactly, after a TH reboot the data shows up for a short period of time and then becomes unavailable again. I think this is because this device transmits data only once an hour

**Comment by BroManDudeGuyPhD** [comment]
You may need to manually query the DPS on the configuration during adding. There are 3 fields after the "Protocol Version" selection, one is called "Manual DPS"

Do you know how to query Tuya devices in the cloud? 
If not, these videos helped me
https://www.youtube.com/watch?v=Q1ZShFJDvE0
https://www.youtube.com/watch?v=VCd0kYWLvMQ

In the `Device Control > Query Properties` query if you add the device ID you will get back a list of the **dp_ids** and vaguely what they do, enter the values you want to map there 


I did NOT need to used bluestacks and all that mess, was able to get all the info from the Tuya IOT Platform

**Comment by dmitrkov** [comment]
> You may need to manually query the DPS on the configuration during adding. There are 3 fields after the "Protocol Version" selection, one is called "Manual DPS"
> 
> Do you know how to query Tuya devices in the cloud? If not, these videos helped me https://www.youtube.com/watch?v=Q1ZShFJDvE0 https://www.youtube.com/watch?v=VCd0kYWLvMQ
> 
> In the `Device Control > Query Properties` query if you add the device ID you will get back a list of the **dp_ids** and vaguely what they do, enter the values you want to map there
> 
> I did NOT need to used bluestacks and all that mess, was able to get all the info from the Tuya IOT Platform

Thank you so much for this info

**Comment by aizmob** [comment]
Added successfully TH-08 device to HA (manually specifying its DPS). Reported values are correct, etc. But sensors are unavailable almost all the time, turning on for a few seconds only - after the device wakes up to make status report.  Then deepsleep till the next sample.

The following message appears in system log:
`
First occurred: 00:07:44 (248 occurrences)
`
`
Last logged: 04:09:44
`
`
[bf5...aa3] Failed to connect to 192.168.14.120: [Errno 113] Connect call failed ('192.168.14.120', 6668)
`
`
[bf5...aa3] Disconnected - waiting for discovery broadcast
`

248 occurences / 4 hours ~ 1 call per minute

**Comment by ishimarumakoto** [comment]
Having problem here today too.
