### ISSUE TITLE
Connect call failed

### ISSUE THREAD

**Issue by Alexandros89** [rospogrigio/localtuya#1652]
Hi,
I'm trying to connect a temperature and humidity sensor but i receive this error:
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:595
Integration: LocalTuya (documentation, issues)
First occurred: 28 gennaio 2024 alle ore 20:56:15 (2 occurrences)
Last logged: 07:47:10

Unexpected exception: [Errno 113] Connect call failed ('192.168.1.74', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.74', 6668)

**Comment by fr0x3n** [comment]
Hi Alexandros
I got the exact same error with the same sensor.
Hope we'll find a solution soon ;)

**Comment by fr0x3n** [comment]
unfortunatly, it's probably an unsupported device.

**Comment by boywiz** [comment]
> I am getting this too i have tried it on a clean install of Hass core and got these same for my new device, (which may or may not be supported) and also get it for existing working entities that are in my existing Homeassistant core and are supported.
> 
> Happy to provide technical info

I tried rolling back to 5.1.0 and 5.2.0 I could add entities that already exist, as well as the new device.

**Comment by Boba1982** [comment]
Also, same error, I am traying to connect tem/humy sensor, nothing special.

**Comment by fenogueira** [comment]
It's the same with a PIR device. Were they able to figure it out?

**Comment by mmilose** [comment]
hi everyone,

check this one, it helped me.
it is in german, but you will easily translate

https://community.simon42.com/t/ha-tuya-local-sensor-einbinden-klapt-nicht/7038/7

**Comment by gitmicroban** [comment]
Thank you @mmilose, this resolved my "connect call failed" issue when adding a new device.
Need a load on the device before submitting the config.

**Comment by bernardolm** [comment]
> hi everyone,
> 
> check this one, it helped me. it is in german, but you will easily translate
> 
> https://community.simon42.com/t/ha-tuya-local-sensor-einbinden-klapt-nicht/7038/7
> 
> The main trick is that some tuya sensors come online only periodically, so you need to "trigger" them.

broken link 💔

**Comment by thundercatsNZ** [comment]
I followed the steps above and successfully added the device.  But for a device that sleeps like this, I still get the "Connect call failed" error in the logs every minute as HA tries to poll a device that is offline.

Is there a way to disable this polling for a specific device and still have the values updating?
