### ISSUE TITLE
Fatal error: protocol.data_received() call failed.

### ISSUE THREAD

**Issue by Symon84** [rospogrigio/localtuya#1654]
## The problem
 Apparently I don't have any problems in the home assistant frontend, but I get these errors in the log file.

## Environment

- Localtuya version: v5.2.1  
- Home Assistant Core version: 2024.1.5 
- [X] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [X] Are you using the Tuya/SmartLife App in parallel ? 

## Provide Home Assistant traceback/logs

```
Logger: homeassistant
Source: custom_components/localtuya/pytuya/__init__.py:304
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 15:25:39 (2 occurrences)
Last logged: 15:26:35
Error doing job: Fatal error: protocol.data_received() call failed.

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1003, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 668, in data_received
    self.dispatcher.add_data(data)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in add_data
    msg = unpack_message(
          ^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 304, in unpack_message
    raise DecodeError("Not enough data to unpack header")
custom_components.localtuya.pytuya.DecodeError: Not enough data to unpack header
```

**Comment by ggar10** [comment]
I have the same issue: Local Tuya v5.2.3 
Home Assistant Core version: 2025.1.4

**Comment by lcsfox** [comment]
Same issue : LocalTuya v5.2.3
