### ISSUE TITLE
Unknow error when addting T&H Sensor 

### ISSUE THREAD

**Issue by awmr2023** [rospogrigio/localtuya#1728]
## Environment

- Localtuya version: 1.34.0
- Home Assistant Core version: 2024.6.1
- [] Does the device work using the Home Assistant Tuya Cloud component ?  X
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? Not tested 
- [] Was the device working with earlier versions of localtuya ? Which one? Not this is the first time i have set up 
- [] Are you using the Tuya/SmartLife App in parallel ? Yes as i am running inital set up and testing 
## Steps to reproduce

1.
2. 
3.

## Provide Home Assistant traceback/logs

```
2024-06-10 08:25:04.559 ERROR (MainThread) [custom_components.localtuya.config_flow] Unexpected exception: [Errno 113] Connect call failed ('192.168.1.27', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1120, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1102, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1005, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.27', 6668)

```

**Comment by scaesare** [comment]
I get this as well. It's a TH-002 BT/Wi-Fi sensor... it's listed under Add Device and the keys and IP address show up but get a similar unexpected error 113.

This unit is battery powered, and I've seen some posts that may be an issue?

**Comment by Alerian26** [comment]
Sorry to wake an old thread but I am facing the same issue. Cannot add the temp sensor to the integration as it returns the same error. I was able to trigger the autodiscover using the battery trick, but I can't go further.
