### ISSUE TITLE
G4 6W 12v Bulbs - Connection to device succeeded but no datapoints found, please try again. 

### ISSUE THREAD

**Issue by evergreen0057** [rospogrigio/localtuya#1744]
## The problem
Trying to add the G4 bulbs to LocalTuya (G4 6W 12v model) that I bought from Aliexpress:
https://www.aliexpress.com/item/1005007153035993.html?spm=a2g0o.order_list.order_list_main.42.6f791802v3WPi1

The following error message is returned in the logs
Connection to device succeeded but no datapoints found, please try again. 

From the log file
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte

## Environment
- Localtuya version: 5.2.1
- Home Assistant Core version: 2024.6.4
- [x] Does the device work using the Home Assistant Tuya Cloud component ?
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? Unsure
- [] Was the device working with earlier versions of localtuya ? Which one? Unsure
- [] Are you using the Tuya/SmartLife App in parallel ? No

## Steps to reproduce
1. Connect bulbs to Tuya app
2. Get the local key from Tuya Developer account
3. Try add device to LocalTuya

## Provide Home Assistant traceback/logs
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/localtuya/discovery.py:67
integration: LocalTuya (documentation, issues)
First occurred: 7:20:15 PM (197 occurrences)
Last logged: 7:38:18 PM

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 184, in finalize
    data = self._ctx.finalize()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 223, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1238, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
           ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte
```

**Comment by balrog-kun** [comment]
I've hit this issue too, done some debugging.

TL;DR: try uninstalling this extension and using the following, improved version: https://github.com/xZetsubou/hass-localtuya

Long version: The error is caused by Tuya 3.5 devices. localtuya supports protocols up to 3.4 right now. UDP message format and encryption is different. There may be more differences.

I added the decryption of the 3.5 discovery packets to my repo but when looking for where to contribute the changes, I found this respository (rospogrigio/localtuya) has been abandonded for about a year with lots of improvements pending review from the maintainer. It looks like xZetsubou/hass-localtuya is currently the most complete fork and it looks like it has protocol 3.5 support already.
