### ISSUE TITLE
Address used for discovery is already in use

### ISSUE THREAD

**Issue by aklausing** [rospogrigio/localtuya#1749]
## The problem
When trying to add a new device I only get this error message:

Address used for discovery is already in use. Make sure no other application is using it (TCP port 6668).

I checked the haos Server for open ports an services using ports (using lsof and ss/netstat) an there is no service using this port.

I had all devices running with the tuya Cloud integration. It makes no difference if the cloud integration is still enabled or if I uninstall it previous to installing the tuya local integration (tested both).

## Environment

- Localtuya version: 5.2.1
- Home Assistant Core version:  
Core 2024.7.2
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

- Are you using the Tuya/SmartLife App in parallel ? [x] 

Tested stopping the app on my phone (complete shutdown) as advised in the readme. Made no difference

## Steps to reproduce
1. Download integration wia HACS
2. Install and configure integration
   a. Tried with cloud credentials and with "Do not configure a Cloud API account" 
4. try to add device

## Provide Home Assistant traceback/logs

```
2024-07-11 11:05:30.400 ERROR (MainThread) [custom_components.localtuya] failed to set up discovery
Traceback (most recent call last):
  File "/config/custom_components/localtuya/__init__.py", line 176, in async_setup
    await discovery.start()
  File "/config/custom_components/localtuya/discovery.py", line 52, in start
    self._listeners = await asyncio.gather(listener, encrypted_listener)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1423, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1407, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [Errno 98] Address in use
2024-07-11 11:05:30.402 INFO (MainThread) [custom_components.localtuya] Cloud API account not configured.
```

**Comment by mateusfn98** [comment]
same here.
checked 6666/6667/6668 in home assistant cli, and nothing.

found any solution ?
