### ISSUE TITLE
EL450HA: Connection to device succeeded but no datapoint returned

### ISSUE THREAD

**Issue by ronsnyder** [rospogrigio/localtuya#1750]
I have a Arlec LED batten Product Codes are ...
       "category": "dj",
        "product_name": "EL450HA",
        "product_id": "v00jsoknheiucj3u",
        "biz_type": 18,
        "model": "EL450HA JLD-2",
It works well from the Smartlife app.
     
The interesting issue is the Tuya Protocol is 3.5 
TinyTuya scan provides : Unknown v3.5 Device

I can control the device in TinyTuya if I set d.set_version(3.5) otherwise the device is not controllable from HA (can't set the protocol) or TinyTuya without using the 3.5 protocol.

**Comment by spaulson500** [comment]
same issue here.  Cannot configure newly acquired Tuya bulbs with local Tuya.  Tiny Tuya does not work with new bulbs unless using protocol 3.5

new bulb using firmware 2.9.15
old bulbs using firmware 2.9.6

**Comment by jpeters001** [comment]
I have the same issue, after fighting for hours on end to setup local tuya with it never revealing any devices i finally installed tiny tuya to get the localkeys. now when i try to add a device manually I get the " Connection to device succeeded but no datapoint returned" error message. 
this is the only log I have
 This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/localtuya/discovery.py:67
integration: LocalTuya (documentation, issues)
First occurred: 9:10:30 AM (1246 occurrences)
Last logged: 9:19:11 AM

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 184, in finalize
    data = self._ctx.finalize()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 223, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1238, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
           ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 1: invalid start byte
