### ISSUE TITLE
Support for Tuya cat feeder

### ISSUE THREAD

**Issue by FredrikM97** [rospogrigio/localtuya#1753]
## The problem
Missing support for data points for tuya cat feeder

## Environment
- Localtuya version: 

> https://github.com/hacs/integration/releases/tag/1.34.0
> [v5.2.1](https://github.com/rospogrigio/localtuya/releases/tag/v5.2.1) 

- Home Assistant Core version: 
> Core: 2024.7.3
> Supervisor 2024.06.2

- [X] Does the device work using the Home Assistant Tuya Cloud component ?
- [X] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ?
- [X] Was the device working with earlier versions of localtuya ? Which one?

> Answer:  All of them

- [] Are you using the Tuya/SmartLife App in parallel ?

## Steps to reproduce

1.
2. 
3.

## DP dump

> DEBUG:localtuya.pytuya:[bfd...vrx] Deciphered data = '{"dps":{"3":1,"11":70,"12":false,"14":0,"15":1,"19":true,"101":"ac_power_on","103":"real_time_mode","112":3,"116":"94%"}}'
> AVAILABLE DPS ARE [{'3': 1, '11': 70, '12': False, '14': 0, '15': 1, '19': True, '101': 'ac_power_on', '103': 'real_time_mode', '112': 3, '116': '94%'}]
> INFO:localtuya:COMPLETE response from device bfd0273e59494eb34esvrx [192.168.1.229].
> 
> **** deviceInfo returned OK ****
> 
> TuyaDebug (Tuya DPs dump) [1.0.0]
> 
> Device bfd0273e59494eb34esvrx at 192.168.1.229 key |mv@;?)v~OtPYFQt protocol 3.3 dev_type type_0a:
>     DPS [3] VALUE [1]
>     DPS [11] VALUE [70]
>     DPS [12] VALUE [False]
>     DPS [14] VALUE [0]
>     DPS [15] VALUE [1]
>     DPS [19] VALUE [True]
>     DPS [101] VALUE [ac_power_on]
>     DPS [103] VALUE [real_time_mode]
>     DPS [112] VALUE [3]
>     DPS [116] VALUE [94%]
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001BBB9F5BD30>
> Traceback (most recent call last):
>   File "C:\Users\fredr\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
>     self.close()
>   File "C:\Users\fredr\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
>     self._loop.call_soon(self._call_connection_lost, None)
>   File "C:\Users\fredr\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
>     self._check_closed()
>   File "C:\Users\fredr\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed
> 

## Additional information
The following is extracted from tuya's api.

> {
>   "result": {
>     "properties": [
>       {
>         "code": "meal_plan",
>         "custom_name": "",
>         "dp_id": 1,
>         "time": 1721998811896,
>         "type": "raw",
>         "value": "fwQAAgF/CQACAX8PAAIBfxUAAwEoEgABAA=="
>       },
>       {
>         "code": "manual_feed",
>         "custom_name": "",
>         "dp_id": 3,
>         "time": 1722003418547,
>         "type": "value",
>         "value": 1
>       },
>       {
>         "code": "factory_reset",
>         "custom_name": "",
>         "dp_id": 9,
>         "time": 1674401358259,
>         "type": "bool",
>         "value": false
>       },
>       {
>         "code": "battery_percentage",
>         "custom_name": "",
>         "dp_id": 11,
>         "time": 1721379054006,
>         "type": "value",
>         "value": 70
>       },
>       {
>         "code": "charge_state",
>         "custom_name": "",
>         "dp_id": 12,
>         "time": 1719785242708,
>         "type": "bool",
>         "value": false
>       },
>       {
>         "code": "fault",
>         "custom_name": "",
>         "dp_id": 14,
>         "time": 1719780937169,
>         "type": "bitmap",
>         "value": 0
>       },
>       {
>         "code": "feed_report",
>         "custom_name": "",
>         "dp_id": 15,
>         "time": 1722003426571,
>         "type": "value",
>         "value": 1
>       },
>       {
>         "code": "light",
>         "custom_name": "",
>         "dp_id": 19,
>         "time": 1719780937112,
>         "type": "bool",
>         "value": true
>       },
>       {
>         "code": "power_state",
>         "custom_name": "",
>         "dp_id": 101,
>         "time": 1719780937173,
>         "type": "enum",
>         "value": "ac_power_on"
>       },
>       {
>         "code": "mode",
>         "custom_name": "",
>         "dp_id": 103,
>         "time": 1719780937114,
>         "type": "enum",
>         "value": "real_time_mode"
>       },
>       {
>         "code": "mfeed_speech_volume",
>         "custom_name": "",
>         "dp_id": 112,
>         "time": 1719780937140,
>         "type": "value",
>         "value": 3
>       },
>       {
>         "code": "battery_capacity",
>         "custom_name": "",
>         "dp_id": 116,
>         "time": 1721379054009,
>         "type": "string",
>         "value": "94%"
>       }
>     ]
>   },
>   "success": true,
>   "t": 1722005860359,
>   "tid": "678f51a34b5f11ef83c362b822d692e4"
> }

**Comment by bit0x43** [comment]
Any progress on this topic?

**Comment by FredrikM97** [comment]
Unfortunately no. Need access to the privatet api or rework the backend library. Only solution I found is to move to tuya local.

**Comment by FredrikM97** [comment]
Went over to tuya local which have support
