### ISSUE TITLE
Log Persistent Error

### ISSUE THREAD

**Issue by JoshC1994** [rospogrigio/localtuya#1754]
**Receiving a Persistent Log Error**

- Have removed Local Tuya however still persists
- Have reinstalled Tuya w/o any devices configured, still persists 

**ERROR**
As shown in HA Log Below

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/localtuya/discovery.py:67
integration: LocalTuya (documentation, issues)
First occurred: 5:52:40 PM (290 occurrences)
Last logged: 5:58:43 PM

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 184, in finalize
    data = self._ctx.finalize()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 223, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1238, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
           ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 1: invalid continuation byte

![image](https://github.com/user-attachments/assets/56eca627-5191-4e93-bbf3-b0b546836a66)

**Comment by martinw72** [comment]
There a more threads at the moment with the same or similar problems. The log lines are always the same. ...in addition I realized that it is not possible to add any new devices after this error occures. If you remove an existing device and add it again, this will work, but now new one's.

**Comment by corgan2222** [comment]
same issue here.. 
This error emerges every few seconds and I can only see half of my devices in the "add new device list".

**Comment by sdekker90** [comment]
Same issues as described above here. I'm on HA Core 2024.9.0 and Localtuya 5.2.1

**Comment by balrog-kun** [comment]
I've hit this issue too, done some debugging.

TL;DR: try uninstalling this extension and using the following, improved version: https://github.com/xZetsubou/hass-localtuya

Long version: The error is caused by Tuya 3.5 devices.  localtuya supports up protocols up to 3.4 right now.  UDP message format and encryption is different.  There may be more differences.

I added the decryption of the 3.5 format to my repo but when looking for where to contribute the changes, I found this respository (rospogrigio/localtuya) has been abandonded for about a year with lots of improvements pending review from the maintainer.  It looks like xZetsubou/hass-localtuya is currently the most complete fork and it looks like it has protocol 3.5 support already.
