### ISSUE TITLE
Connection to device succeeded but no datapoints found

### ISSUE THREAD

**Issue by XalaTheShepard** [rospogrigio/localtuya#1764]
Dear Rospogrigio, 

I noticed today that a Tuya wifi light was unavailable in the Localtuya integration for over 14 hours, while it was still available in the Tuya integration. 
Thinking I might had to refresh the local key, I deleted the device from the integration. 
However, the local key was unchanged from the last time I configured it. 
While trying to add the device again to the Localtuya integration, I got the following error message: Connection to device succeeded but no datapoints found.

In the detailed logs, I noticed the error below concerning the device. 

Could you please lend me a hand adding the device again? 

Many thanks. 

Kind regards, 

Robin

2024-08-19 21:11:56.442 ERROR (MainThread) [custom_components.localtuya.pytuya] [bff...0p7] Failed to get status: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/locks.py", line 386, in acquire
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 863, in detect_available_dps
    data = await self.status()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 795, in status
    status = await self.exchange(DP_QUERY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 769, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 450, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

**Comment by awshirley** [comment]
I've experienced the exact same problem.  One of my lights quit working on Local Tuya but works fine for the regular Tuya integration.  I removed the Local Tuya integration and reinstalled it, but the same bulb is failing and I get this when trying to add it.
![image](https://github.com/user-attachments/assets/7e1fef21-2d33-47c3-88a1-07056b315868)

**Comment by swaggerino** [comment]
same issue here, not directly a light but a wifi LED controller

**Comment by Seellr07** [comment]
Same issue here

**Comment by Marco15453** [comment]
Same issue using an LSC Smart Connect Light 3004919

**Comment by codemonkey2k5** [comment]
Same issue. can add older devices, but not newer ones

**Comment by lovian83** [comment]
Same issue. I have tow ELIVCO plugs model LSPA9. Older works fine but with newer i get error.
