### ISSUE TITLE
 v5.2.2 broke all my devices. Became unavailable. Reverted back to  v5.2.1

### ISSUE THREAD

**Issue by cloudbr34k84** [rospogrigio/localtuya#1772]
Sorry didn't have time to check or provice more info and other things as I needed access to some of those devices to use. Ill try again tomorrow and update again and see what errors are showing

**Comment by straybiker** [comment]
Same here,  existing ones broke. Removing them and adding them again did not work either

**Comment by alawadhi3000** [comment]
Same here, but its not for all sensors, some of them still work.

**Comment by irresisti** [comment]
`2024-08-27 15:33:20.929 ERROR (MainThread) [homeassistant.components.light] Error while setting up localtuya platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/localtuya/common.py", line 96, in async_setup_entry
    entity_class(
  File "/config/custom_components/localtuya/light.py", line 170, in __init__
    if self._config.get(CONF_SCENE) < 20:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
`

**Comment by ArnolddeBolster** [comment]
same here for all my light bulbs. my switches still work

**Comment by vivdesign** [comment]
Me to everything went offline had to restore backup

**Comment by GuidoTraversari** [comment]
i have the same problem.. after the update at LocalTuya 5.2.1, my my light bulbs stop to working. I have the same problem with one led strip. my switches still work!

**Comment by harjaj** [comment]
same here, my light unavailable ,if I want to use i have to change my light to switch

**Comment by mguyard** [comment]
Same for me for climate entity.
Rollback works

**Comment by ELERON23** [comment]
Protocol version 3.5 is not present after upgrade to 5.2.2, broke light buld support. Reverted back to 5.2.1 and protocol 3.5 is back.

**Comment by farnsy** [comment]
I'm getting the same error:
`Error while setting up localtuya platform for light`

however rollback to 5.2.1 didn't resolve it for me. UI showing 5.2.1 is running, logs still show same error. Have restarted HA and restarted server. 

any tips welcome!

**Comment by JampireX** [comment]
All lights broken after update, reverting to 5.2.1 didn't helped.

```
Error while setting up localtuya platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/localtuya/common.py", line 96, in async_setup_entry
    entity_class(
  File "/config/custom_components/localtuya/light.py", line 156, in __init__
    self._max_mired = color_util.color_temperature_kelvin_to_mired(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 638, in color_temperature_kelvin_to_mired
    return math.floor(1000000 / kelvin_temperature)
                      ~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'int' and 'str'
```

**Comment by GuidoTraversari** [comment]
I solved... Now i use tuya official integration and worked all device...

**Comment by cloudbr34k84** [comment]
> I solved... Now i use tuya official integration and worked all device...

what do you mean?

**Comment by titovskiy** [comment]
> I solved... Now i use tuya official integration and worked all device...

What about local work without the Internet?

**Comment by GuidoTraversari** [comment]
> > I solved... Now i use tuya official integration and worked all device...
> 
> what do you mean?

it means that I stopped using localtuya and installed the Tuya integration... without having to re-pair anything, the official Tuya integration immediately recognized all my devices in an instant and now they work... it's true that in theory I lost the functionality in LAN, but at least everything works!

**Comment by titovskiy** [comment]
>  but at least everything works!

works on 5.2.1 too %) just roll back

**Comment by cloudbr34k84** [comment]
> > > I solved... Now i use tuya official integration and worked all device...
> > 
> > 
> > what do you mean?
> 
> it means that I stopped using localtuya and installed the Tuya integration... without having to re-pair anything, the official Tuya integration immediately recognized all my devices in an instant and now they work... it's true that in theory I lost the functionality in LAN, but at least everything works!

oh yeah, nah i need tuya local as tuya Integration does recognise all my devices or i need specific entities

**Comment by LoznOz** [comment]
Lost (unavailable) all our light globes as well. No stress here - I’m heading overseas in 36 hours & family at home has no lights coming on 😓. I’ll try revert as others have done in comments above if I can figure out how to do that 🤞

**Comment by ImSkully** [comment]
Anyone looking for a temporary _(or better alternative)_ solution for LocalTuya in the meantime until this issue is fixed, you can use this fork instead: [xZetsubou/hass-localtuya](https://github.com/xZetsubou/hass-localtuya) - I have been using a mix of both versions as some of my devices only function properly in the fork.

The steps to install it through HACS is the exact same and you do not have to uninstall the existing integration as it will simply be overwritten because both of these custom integrations are providing the same component. _(Be warned: make a backup before you do this in case anything goes wrong, I can't be certain this works for everyone and for all possible devices)_
1. Add the fork repository in your HACS custom repositories list:
    - **Repository:** `https://github.com/xZetsubou/hass-localtuya`
    - **Type:** Integration
2. Search for `localtuya` in HACS and install or use button below - the fork version of the `localtuya` integration appears in the HACS table with a 🔹 prefix on the description line
    
    [![Open your Home Assistant instance and open a repository inside the Home Assistant Community Store.](https://my.home-assistant.io/badges/hacs_repository.svg)](https://my.home-assistant.io/redirect/hacs_repository/?category=integration&repository=hass-localtuya&owner=xZetsubou)

3. Restart Home Assistant
4. If your [existing hub](https://home.skully.tech/config/integrations/integration/localtuya) with your devices is still showing them as unavailable, simply add a new one by configuring localtuya again - it might be worthwhile to just completely start fresh by deleting all existing configurations in localtuya and setting up all your devices again as normal

**Comment by a-bianucci** [comment]
I am in the same boat - rolled back and it's back to working for now.  Exact same error as above

**Comment by fenty17** [comment]
Roll back to 5.2.1 didn’t work for me. Only have four lights and trying to resubmit configuration for them doesn’t work either.

**Comment by alawadhi3000** [comment]
> ights and trying to resubmit configuration for them doesn’t work either.

Restore from backup.

**Comment by wesleykirkland** [comment]
Even after restoring to 5.2.1 and even 5.2.0 none of my Tuya devices will come online. Restoring a full Home Assistant backup is pretty much out of the question given how long it's been broken for me. I back everything up to a Git Repo and I pulled down the entire folder and reuploaded it in custom_compents before it broke and still nothing :/

**Comment by Caligo82** [comment]
I wonder ... has there been any progress here? Did a cold reboot actually solve this for most people?

**Comment by irresisti** [comment]
> > I wonder ... has there been any progress here? Did a cold reboot actually solve this for most people?
> 
> I switched to a fork and it works perfect with no need to reset the settings. https://github.com/xZetsubou/hass-localtuya

How did you switch?

**Comment by JampireX** [comment]
> > > I wonder ... has there been any progress here? Did a cold reboot actually solve this for most people?
> > 
> > 
> > I switched to a fork and it works perfect with no need to reset the settings. https://github.com/xZetsubou/hass-localtuya
> 
> I installed the other version and it now works perfectly again. Thanks for the tip

Add repository (link to github) in HACS and just update integration from it. The settings will be saved.
