### ISSUE TITLE
No l8caltuya device working after upgrade to 5.2.2

### ISSUE THREAD

**Issue by hbaes** [rospogrigio/localtuya#1782]
Directly after upgrading local tuya to 5.2.2 on current Version of ha, all tujy devices get offline and cokld Kot be maintained. Also reboot did not fix it. 
After reverting to prior localtuya version via hacs, all Devices get back maintainable.
Devices affected bulp, Switches

## Environment

- Localtuya version:  
- Home Assistant Core version:  
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [x] Was the device working with earlier versions of localtuya ? Which one? 
- [] Are you using the Tuya/SmartLife App in parallel ? <!-- if yes, put a x between the

**Comment by ramonfontes** [comment]
The same to me

**Comment by Caligo82** [comment]
Yes I'm facing the same problem. Just suddenly unavailable...

**Comment by thetastate1** [comment]
Could have the same issue. All existing devices not working after hacs upgrade to 5.2.1. Can add new devices. Editing existing devices doesn't fix. Deleting existing devices and re-adding works but not super keen on deleting 42 devices, re-adding, and editing automations.

**Comment by Keith-H-T** [comment]
Same issue with my local tuya devices. Reverted 5.2.1 to resolve.

**Comment by mohsenheravi** [comment]
I had kept March 23 version since Local Tuya got broken after that update. Yesterday I lost a few of my Local Tuya integrations. So I said what the heck, and updated to the latest version. Funny enough, local tuya started working, but with the same devices being unavailable. In short, a few devices don't work, no matter what version I am using. The funny thing is, I have a couple of devices that are exactly the same, but one works and the other doesn't!! I deleted them and re-integrate them. They get detected and configured, yet just to be unavailable. So frustrating.

**Comment by phankins11** [comment]
Same issue here.

**Comment by phankins11** [comment]
Same issue here.

> Yes I'm facing the same problem. Just suddenly unavailable... Reverting to 5.2.1 solved the issue for me.

[Caligo82](https://github.com/Caligo82)

Would you be willing to share the steps to revert to previous version... I'm kinda new to this integration

**Comment by Caligo82** [comment]
Sure, provided you installed Localtuya with HACS, you'll head over to the integration page of HACS, click the three dots and select "Redownload". You'll be presented with the following screen:

![image](https://github.com/user-attachments/assets/b0d0e1f5-9b1a-43bc-96b5-6632d07f3291)

**Comment by phankins11** [comment]
@Caligo82 thanks so much!

For me, turns out a full restart\reboot of my Raspberry Pi did the trick.

Not sure why a restart through the HA app didn't resolve, but after reboot, all is well.

**Comment by andyb2000** [comment]
Just adding a same here.
Version 5.2.2 fails, all entities unavailable, if you delete and re-create one, that entity does not actually re-appear (though localtuya thinks its configured and won't re-add, but allows an edit).

In v5.2.2 the error repeating in my logs was:
```
ModuleNotFoundError: Platform localtuya.button not found
``` 

I've rolled back to v5.2.1 which is working, however I think an upgrade/change may have also occurred as i'm constantly getting errors in my logs:

```
2024-09-17 11:55:50.157 ERROR (SyncWorker_26) [homeassistant.util.logging] Exception in _update_handler when dispatching 'localtuya_REDACTED': ({'1': True, '9': 0, '18': 16, '19': 7, '20': 2431, '21': 1, '22': 726, '23': 30333, '24': 20408, '25': 1020},)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 411, in _update_handler
    self.status_updated()
  File "/config/custom_components/localtuya/binary_sensor.py", line 61, in status_updated
    elif state == self._config[CONF_STATE_OFF].lower():
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'state_off'

2024-09-17 11:55:50.593 WARNING (SyncWorker_4) [custom_components.localtuya.sensor] [063...795] Entity sensor.summer_mainpower_electricity is requesting unknown DPS index 17
2024-09-17 11:55:50.597 WARNING (SyncWorker_4) [custom_components.localtuya.binary_sensor] [063...795] Entity binary_sensor.summer_mainpower_fault is requesting unknown DPS index 26
2024-09-17 11:55:50.597 WARNING (SyncWorker_4) [custom_components.localtuya.binary_sensor] [063...795] Entity binary_sensor.summer_mainpower_fault is requesting unknown DPS index 26
2024-09-17 11:55:50.602 ERROR (SyncWorker_4) [homeassistant.util.logging] Exception in _update_handler when dispatching 'localtuya_REDACTED': ({'1': True, '9': 0, '18': 25, '19': 12, '20': 2454, '21': 1, '22': 724, '23': 30088, '24': 19891, '25': 1045},)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 411, in _update_handler
    self.status_updated()
  File "/config/custom_components/localtuya/binary_sensor.py", line 61, in status_updated
    elif state == self._config[CONF_STATE_OFF].lower():

```

**Comment by nevadascout** [comment]
I had the same problem, but I was able to get my localtuya devices to report values again by using the "configure" option of the localtuya integration to edit each of my sensors and just click through without changing anything to save them.

This made them work again, but the target temperature value was then coming back as `180` instead of `18`. To fix that, I had to change the target temperature precision from `1` to `0.1`, and now everything works fine again.

**Comment by Caligo82** [comment]
Well depending on the amount of devices you have this isn't a good solution unfortunatly. I ended up [switching the fork ](https://github.com/xZetsubou/hass-localtuya) and have been a happy camper since.

Steps to switch (if you used HACS to install the old fork):

- Go over to HACS (not the homeassistant integrations page!)
- Remove the rospogrigio fork _(mi dispiace)_
- Add custom repository https://github.com/xZetsubou/hass-localtuya
- Install "new" localtuya
- reboot
- be a happy camper

**Comment by Eambo** [comment]
I had this issue recently for some reason, the error shown was:


```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 13:06:55 (2 occurrences)
Last logged: 13:29:48

Error setting up entry localtuya for localtuya
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/localtuya/init.py", line 276, in async_setup_entry
await hass.config_entries.async_forward_entry_setups(entry, platforms)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2568, in async_forward_entry_setups
await integration.async_get_platforms(platforms)
File "/usr/src/homeassistant/homeassistant/loader.py", line 1102, in async_get_platforms
if platform := self._get_platform_cached_or_raise(platform_name):
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1193, in _get_platform_cached_or_raise
raise ModuleNotFoundError(
...<2 lines>...
)
ModuleNotFoundError: Platform localtuya.alarm_control_panel not found
```

I managed to fix this with a hacky workaround, but I'm not sure why it was needed. I'm putting it here incase it helps anyone else, but it shouldn't be needed in the core system which is why I'm not putting through a PR:

* Navigate to config --> custom components --> localtuya (I did this via Studio Code Server in the UI)
* Make a new file called `alarm_control_panel.py`
* Add this content to the file:

```
"""Alarm control panel for localtuya integration."""
from homeassistant.components.alarm_control_panel import (
    AlarmControlPanelEntity,
    AlarmControlPanelEntityFeature,
)
from homeassistant.const import (
    STATE_ALARM_ARMED_AWAY,
    STATE_ALARM_ARMED_HOME,
    STATE_ALARM_ARMED_NIGHT,
    STATE_ALARM_DISARMED,
    STATE_ALARM_TRIGGERED,
)

from .common import LocalTuyaEntity, async_setup_entry
from .const import CONF_RESET_DPIDS


def flow_schema(dps):
    """Return schema used in config flow."""
    return {}


class LocaltuyaAlarmControlPanel(LocalTuyaEntity, AlarmControlPanelEntity):
    """Representation of a LocalTuya Alarm Control Panel."""

    def __init__(
        self,
        device,
        config_entry,
        sensorid,
        **kwargs,
    ):
        """Initialize the Tuya alarm control panel."""
        super().__init__(device, config_entry, sensorid, _LOGGER, **kwargs)
        self._state = None

    @property
    def state(self):
        """Return the state of the device."""
        return self._state

    def update(self):
        """Fetch state from the device."""
        super().update()
        # Add your state mapping logic here based on your device's DPs
        # This is a placeholder implementation
        self._state = STATE_ALARM_DISARMED


async_setup_entry = async_setup_entry
```

I then recommend going to Developer Tools --> check configuration. If it states everything is okay, restart HA. This resolved the issue for me!

Note that the new file is basically just a stump/dummy to prevent this specific error, in looking at the history I can't see any sign of this file existing in the past so I'm not sure what has broken...
