### ISSUE TITLE
broken climate in v5.2.2

### ISSUE THREAD

**Issue by zenguru84** [rospogrigio/localtuya#1787]
climate is broken in v5.2.2
i have 8 Avatto ME81H thermostats, al "unavailable" after update.
reverted to v5.2.1, all working fine again.

i have tried to reconfigure one thermostat under v5.2.2, it showed up, but it was uncontrollable. 

Core 2024.9.1
Supervisor 2024.08.0
Operating System 13.1
running as proxmox vm.

**Comment by Bezzaee** [comment]
Same issue, here is my log. Seems to be an issue importing default values: 

ERROR (MainThread) [homeassistant.components.climate] Error adding entity None for domain climate with platform localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 816, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 323, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 495, in capability_attributes
    ATTR_MIN_TEMP: show_temp(hass, self.min_temp, temperature_unit, precision),
                                   ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 323, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/climate.py", line 427, in min_temp
    return self._config[CONF_TEMP_MIN]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'min_temperature_const'

**Comment by DeeSaR47** [comment]
Same issue with two "Danyon Split AC Devices" after update to v5.2.2 they are "unavailable".
Restored Backup with v5.2.1 everything ist working again.

**Comment by Kydonakis** [comment]
Any progress on this one guys? Or we will stick to 5.2.1 forever?

Thanks for the support.

**Comment by proosth** [comment]
I can confirm that this has solved the problem. Thank you for your work on this issue!
