### ISSUE TITLE
Exception in callback _SelectorDatagramTransport._read_ready()

### ISSUE THREAD

**Issue by SmartM-ui** [rospogrigio/localtuya#179]
Hi @postlund @ultratoto14,
Just for information, I report that when you start Home Assistant the following errors are reported in the log:

Logger: homeassistant
Source: custom_components/localtuya/__init__.py:161
First occurred: 00:23:13 (4 occurrences)
Last logged: 00:23:14
Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 1021, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
    self.device_found(decoded)
  File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
    self._callback(device)
  File "/config/custom_components/localtuya/__init__.py", line 161, in _device_discovered
    device = hass.data[DOMAIN][entry.entry_id][TUYA_DEVICE]
KeyError: 'af6...7e9'

2020-11-22 00:23:13 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 1021, in _read_ready
self._protocol.datagram_received(data, addr)
File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
self.device_found(decoded)
File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
self._callback(device)
File "/config/custom_components/localtuya/__init__.py", line 161, in _device_discovered
device = hass.data[DOMAIN][entry.entry_id][TUYA_DEVICE]
KeyError: 'af6...7e9'
2020-11-22 00:23:13 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 1021, in _read_ready
self._protocol.datagram_received(data, addr)
File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
self.device_found(decoded)
File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
self._callback(device)
File "/config/custom_components/localtuya/__init__.py", line 161, in _device_discovered
device = hass.data[DOMAIN][entry.entry_id][TUYA_DEVICE]
KeyError: '597...dc7'
2020-11-22 00:23:14 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 1021, in _read_ready
self._protocol.datagram_received(data, addr)
File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
self.device_found(decoded)
File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
self._callback(device)
File "/config/custom_components/localtuya/__init__.py", line 161, in _device_discovered
device = hass.data[DOMAIN][entry.entry_id][TUYA_DEVICE]
KeyError: 'a04...a64'
2020-11-22 00:23:14 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 1021, in _read_ready
self._protocol.datagram_received(data, addr)
File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
self.device_found(decoded)
File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
self._callback(device)
File "/config/custom_components/localtuya/__init__.py", line 161, in _device_discovered
device = hass.data[DOMAIN][entry.entry_id][TUYA_DEVICE]
KeyError: 'af6...659'

**Comment by postlund** [comment]
Which version are you running? Does this happen on master?

**Comment by SmartM-ui** [comment]
> Which version are you running? Does this happen on master?

Hi @postlund , 
I have the latest PR "Add support for passive devices (# 171)" 

Have a nice day

**Comment by postlund** [comment]
You should write in the PR, not open new issues as the PR is just work that hasn't been merged yet.

**Comment by SmartM-ui** [comment]
> You should write in the PR, not open new issues as the PR is just work that hasn't been merged yet.

Hi Pierre,
I opened a new PR because I didn't know if this error was due to the PR 171 or a general error.
If you believe it is due to the PR in question, you can move or close it.
If I have to move it, give me directions and I'll move it right away.
Thanks

**Comment by postlund** [comment]
The code that generates the error is not on master, so I assume it should go into the PR. You can just copy the error logs and paste in the PR and close this one.

**Comment by SmartM-ui** [comment]
> The code that generates the error is not on master, so I assume it should go into the PR. You can just copy the error logs and paste in the PR and close this one.

OK!
