### ISSUE TITLE
Tuya celing fan dont work after upgrade to HA to 2024.9.1 and local tuya to 5.2.0

### ISSUE THREAD

**Issue by RanAkiva** [rospogrigio/localtuya#1792]
## Environment

- Localtuya version: 5.2.0 
- Home Assistant Core version: 2024.9.1 
- [] Does the device work using the Home Assistant Tuya Cloud component yes
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? No
- [] Was the device working with earlier versions of localtuya ? yes with ver 4.1.0
- [] Are you using the Tuya/SmartLife App in parallel ? yes, SmartLife

## Steps to reproduce

1.
2. 
3.

## Provide Home Assistant traceback/logs

```
put your log output between these markers
```
**Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:595
integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 18:02:59 (1 occurrences)
Last logged: 18:02:59

Unexpected exception: [Errno 113] Connect call failed ('192.168.1.166', 6668)
Traceback (most recent call last):
File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
self.dps_strings = await validate_input(self.hass, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
interface = await pytuya.connect(
^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/localtuya/pytuya/init.py", line 1183, in connect
_, protocol = await loop.create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
sock = await self._connect_sock(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
return await fut
^^^^^^^^^
File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.166', 6668)**

## Additional information

![1](https://github.com/user-attachments/assets/83e9ac9c-b241-4efe-a232-6070c3395352)
![zzz](https://github.com/user-attachments/assets/dcef7e62-855a-4e8c-a6ce-259c854dac8f)

**Comment by silvelo** [comment]
I get the same error. I can configure with localtuya the entities of the device, but they all appear as Unavailable, then I go to the smartlife application and the changes I make in the application are reflected in the entities and appear available to interact. But when I change in localtuya nothing happens and the same error appears in the logs.

**Comment by CloCkWeRX** [comment]
The problem is potentially the device only accepting one connection to port 6668 at a time, if it works with the tuya smartlife app but not the others.
Close off the connection from your phone,.see if that comes good.
