### ISSUE TITLE
Beok RF BOT-R7W-X-WIFI,Tuya 

### ISSUE THREAD

**Issue by MIRORSTAR** [rospogrigio/localtuya#1823]
Hello!

Please add the ability to control the Beok RF BOT-R7W-X-WIFI thermostat via the Tuya app. This is currently not possible with the existing integration.

## Environment

- Localtuya version:  
- Home Assistant Core version:  
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

1.
2. 
3.

## Provide Home Assistant traceback/logs

```
put your log output between these markers
```

**Comment by ialtuhov** [comment]
Hi. I have several of the same devices and I am ready to help in any way I can if you tell me what data needs to be provided.
I tried adding devices manually, via "...", but I got errors, mostly the inability to establish a connection.

**Comment by rubu** [comment]
I'm interrested into this as well. Did not work out of the box - the same connection error.

When i ran wireshark in the background, i noticed that all the conneciton attempts got a RST from the BEOK device  (88.236 is ha, and 89.196 is the thermostat)

<img width="1581" height="185" alt="Image" src="https://github.com/user-attachments/assets/ed54354e-7bd7-4867-9bc5-5dc97caf07d2" />

I am not sure what the normal flow is (since i don't have other tuya compatible devices) - they just listen on 6668 all the time?

**Comment by ecSpl01t** [comment]
I have the issue, cannot add those thermostat's to via localTuya.

`
Unexpected exception: [Errno 113] Connect call failed ('192.168.88.14', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1171, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1146, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
        exceptions, addrinfo, laddr_infos)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1045, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.88.14', 6668)
`


`
 % nc -vz 192.168.88.14 6668 
nc: connectx to 192.168.88.14 port 6668 (tcp) failed: Connection refused
`

Motimation:
When I use Tuya cloud (in HA) to turn on thermostat, it turns on with auto mode, when is not acceptable for me. I just want to turn on with last known mode.

**Comment by bouw002** [comment]
Have the same issue with the thermostat. It work almost fine use tuya intergration but with localtuya I cannot connect.
Does anyone already found the cause ?

**Comment by nikdvrn93** [comment]
+1 actual 
On tuya integration he cant send status without open tuya app

**Comment by antonkudinov** [comment]
hello!

Could you find solution for this problem ?
