### ISSUE TITLE
Problem with integration after HA update to 2024.11.3 . Integration is stop working

### ISSUE THREAD

**Issue by MarekOleksik** [rospogrigio/localtuya#1856]
Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: homeassistant
Źródło: custom_components/localtuya/discovery.py:67
integracja: LocalTuya integration (dokumentacja, Problemy)
Pierwsze zdarzenie: 14:43:34 (11310 zdarzenia)
Ostatnio zalogowany: 22:37:13

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready() (None)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
                                              ^^^^^^^^^^^^^^^^^^^^
ValueError: The length of the provided data is not a multiple of the block length.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1238, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
           ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 0: invalid continuation byte

**Comment by crwilcox** [comment]
I suspect the issue here is the content isn't UTF-8. Locally I patched with specifying latin-1 (aka 'latin-1', 'iso_8859_1' and '8859'). This is the simplest encoding available and wont' attempt to process multichar unicode. https://docs.python.org/3/library/codecs.html#encodings-and-unicode

Line 30:
```
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode("latin-1")
```

Line 67: This may not be necessary, I think Line 30 is the root cause.
```
            data = data.decode('latin-1')
```

**Comment by dathosim** [comment]
+1
