### ISSUE TITLE
Ledvance SMART+ WiFi Tube T8EM no DPs found

### ISSUE THREAD

**Issue by FlossenNacht** [rospogrigio/localtuya#1867]
## The problem
When trying to connect a Ledvance SMART+ WiFi Tube T8EM, I can find the device and local key via various options. But local-tuya can't find it in auto. When trying to add it manualy, it isn't able to find any DPS automaticly. Every DPS ID I try to add manualy gets a value of "-1". Protocol accoring to tinytuya for the lamp is 3.5.

## Environment
- Localtuya version: 5.2.1 
- Home Assistant Core version: 2024.12.3
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

1. Add new device
2. Add [...] Device
3. Add the Ledvance SMART+ WiFi Tube T8EM in any way

## DP dump
INFO:localtuya:localtuya version 1.0.0
INFO:localtuya:Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
INFO:localtuya:Using pytuya version '10.0.0'
INFO:localtuya:Detecting list of available DPS of device bf1ff984c952945bfbzdr9 [192.168.170.132], protocol 3.5.
DEBUG:localtuya.pytuya:[bf1...dr9] Sending command 10 (device type: type_0a)
DEBUG:localtuya.pytuya:[bf1...dr9] Sending payload: b'{"gwId":"bf1ff984c952945bfbzdr9","devId":"bf1ff984c952945bfbzdr9","uid":"bf1ff984c952945bfbzdr9","t":"1734219029"}'
DEBUG:localtuya.pytuya:[bf1...dr9] Command 10 waiting for sequence number 1
ERROR:localtuya.pytuya:[bf1...dr9] Failed to get status:
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 849, in detect_available_dps
    data = await self.status()
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 781, in status
    status = await self.exchange(DP_QUERY)
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 755, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 446, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "C:\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
INFO:localtuya:Detecting list of available DPS of device bf1ff984c952945bfbzdr9 [192.168.170.132], protocol 3.5.
DEBUG:localtuya.pytuya:[bf1...dr9] Sending command 10 (device type: type_0a)
DEBUG:localtuya.pytuya:[bf1...dr9] Sending payload: b'{"gwId":"bf1ff984c952945bfbzdr9","devId":"bf1ff984c952945bfbzdr9","uid":"bf1ff984c952945bfbzdr9","t":"1734219036"}'
DEBUG:localtuya.pytuya:[bf1...dr9] Command 10 waiting for sequence number 1
ERROR:localtuya.pytuya:[bf1...dr9] Failed to get status:
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 849, in detect_available_dps
    data = await self.status()
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 781, in status
    status = await self.exchange(DP_QUERY)
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 755, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 446, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "C:\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
INFO:localtuya:Detecting list of available DPS of device bf1ff984c952945bfbzdr9 [192.168.170.132], protocol 3.5.
DEBUG:localtuya.pytuya:[bf1...dr9] Sending command 10 (device type: type_0a)
DEBUG:localtuya.pytuya:[bf1...dr9] Sending payload: b'{"gwId":"bf1ff984c952945bfbzdr9","devId":"bf1ff984c952945bfbzdr9","uid":"bf1ff984c952945bfbzdr9","t":"1734219043"}'
DEBUG:localtuya.pytuya:[bf1...dr9] Command 10 waiting for sequence number 1
ERROR:localtuya.pytuya:[bf1...dr9] Failed to get status:
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 849, in detect_available_dps
    data = await self.status()
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 781, in status
    status = await self.exchange(DP_QUERY)
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 755, in exchange
    msg = await self.dispatcher.wait_for(seqno, payload.cmd)
  File "C:\Python310\Projekte\tuyadebug\localtuya\pytuya\__init__.py", line 446, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "C:\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
INFO:localtuya:TIMEOUT: No response from device bf1ff984c952945bfbzdr9 [192.168.170.132] after 2 attempts.

## Provide Home Assistant traceback/logs
Due to no DPs found in DP Dump, excluded. If needed, can be added.

**Comment by Panossa** [comment]
Same with my new LEDVANCE 9.5W RGBW Wi-Fi E27 light.
I got 12 a year ago, connected them to my HomeAssistant and they worked quite well. Then, one broke and I got a replacement. It's clearly a different version of it but has the exact same stats (down to the wattage). However, I updated LocalTuya before the replacement arrived and either due to it being a different/broken version of the lamp or due to a new LocalTuya version, I can't connect to it. It doesn't discover the lamp by itself and when I input the IP address, it says "Connection to device succeeded but no datapoints found, please try again."

I'll attach my logs
[home-assistant_localtuya_2024-12-21T21-52-07.560Z.log](https://github.com/user-attachments/files/18220184/home-assistant_localtuya_2024-12-21T21-52-07.560Z.log)

**Comment by Nadav-B** [comment]
(Same problem on my side, IP is not any more discoverable after upgrading my LDVWIFIG125FE27RGBW light got an update.  When giving the ip manually it delivers also: "Connection to device succeeded but no datapoints found, please try again.")

**Comment by Panossa** [comment]
> (Same problem on my side, IP is not any more discoverable after upgrading my LDVWIFIG125FE27RGBW light got an update. When giving the ip manually it delivers also: "Connection to device succeeded but no datapoints found, please try again.")

Since this repo is barely maintained, the only real choice you seem to have right now (except implementing the support yourself on an own fork) is to use this fork of localtuya with v.3.5 protocol support:
https://xzetsubou.github.io/hass-localtuya/ 
(Comes with the usual caveats of barely known repositories of the possibility of containing malicious code; just like this add-on and any other, proportional to how unknown it is.)
