### ISSUE TITLE
Connection problems with Nedis Smartlife Switch

### ISSUE THREAD

**Issue by Mastiffen** [rospogrigio/localtuya#197]
I am new to this, and it doesn’t work as it should. I click the switch, but nothing happens, and the slider on the swith goes back. Turning the switch off and on manually doesn’t make it change in the GUI. After a restart of Home Assistant I could turn it on. Then off. And then nothing. The slider jumped back to on, while the switch was off, so naturally I could not do anything with it. And now I can't even do that, the switch is marked as "unavailable". Here's the log:

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:626
Integration: LocalTuya integration (documentation, issues)
First occurred: 14:20:52 (7 occurrences)
Last logged: 14:22:44

[655...e12] Connect to 192.168.1.79 failed
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/localtuya/common.py", line 146, in _make_connection
    self._interface = await pytuya.connect(
  File "/home/homeassistant/.homeassistant/custom_components/localtuya/pytuya/__init__.py", line 626, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.79', 6668)

**Comment by Mastiffen** [comment]
Btw I will not keep these switches, I prefer the Tasmoda way with MQTT, so if this is something that's a one off for my system, there's no need to bother. But I will keep them for some days, so I can do testing if you deem it necessary to hunt this down.

**Comment by Mastiffen** [comment]
Since there's been no answer I assume this is not n interesting issue because it's a one-off for me, so I'm returning the switches tomorrow morning.

**Comment by postlund** [comment]
I think it's more of a time issue right now, most of us are rather busy at the moment.

**Comment by Mastiffen** [comment]
I see. I am going to Jula (which you probably know very well! ;) ) tomorrow, but is it worth holding on to one of these switches a while longer in case you find something? I bought seven, but I could return six of them. They have av 60 days returns policy now, so I can wait another month or so.

**Comment by P3nkiln** [comment]
It's not just Mastiffen. I've recently installed the component and I'm seeing similar. Any help would be gratefully appreciated.
