### ISSUE TITLE
Errors running on a GoSund UP111 smart plug with energy monitoring

### ISSUE THREAD

**Issue by elyobelyob** [rospogrigio/localtuya#202]
Hi,
I have the setup working, but unfortunately not very stable. If I restart Home Assistant, the logging starts again, presumably the plug therefore is not at issue.
<img width="496" alt="Screenshot 2020-11-30 at 11 58 57" src="https://user-images.githubusercontent.com/298022/100607971-9f920f00-3303-11eb-8462-3be32556c742.png">

Here are the main issues I have spotted in the logs ... 

https://paste.ubuntu.com/p/TXQjnnm9Ds/

Thanks for any feedback ... 

Nick

**Comment by tehnoinstyle** [comment]
Hi.
I have same problem with Energy Meter Switch.
![localtuya-master-v 3 1 0](https://user-images.githubusercontent.com/9967078/100629667-3b3a7400-3332-11eb-944e-b847bf528ea6.png)

**Comment by elyobelyob** [comment]
<img width="429" alt="Screenshot 2020-11-30 at 18 03 09" src="https://user-images.githubusercontent.com/298022/100647480-7c815280-3337-11eb-9e15-767fcdf67766.png">

Am getting this with the following error, very regularly ... 

2020-11-30 18:00:41 ERROR (MainThread) [custom_components.localtuya.common] [71c...80e] Connect to 192.168.0.181 failed
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/custom_components/localtuya/common.py", line 146, in _make_connection
    self._interface = await pytuya.connect(
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 626, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1068, in _create_connection_transport
    protocol = protocol_factory()
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 627, in <lambda>
    lambda: TuyaProtocol(
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 350, in __init__
    self.cipher = AESCipher(self.local_key)
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 182, in __init__
    self.cipher = Cipher(algorithms.AES(key), modes.ECB(), default_backend())
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 38, in __init__
    self.key = _verify_key_size(self, key)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/cryptography/hazmat/primitives/ciphers/algorithms.py", line 21, in _verify_key_size
    raise ValueError(
ValueError: Invalid key size (160) for AES.

**Comment by tehnoinstyle** [comment]
Hi.

After a while, the problem repeats itself.

![localtuya-master-v 3 1 0_1](https://user-images.githubusercontent.com/9967078/100703588-8002f100-33ac-11eb-8d83-5cf576ce555b.png)

in log:

`
ERROR
Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:239
Integration: LocalTuya integration (documentation, issues)
First occurred: 30 ноября 2020 г., 17:43:21 (6 occurrences)
Last logged: 7:28:29

[024...ace] Connect to 192.168.1.115 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 156, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 461, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 440, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 239, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
`
In my opinion, this problem appeared after version 3.0.3

On version 3.0.3, I did not see this problem.
