### ISSUE TITLE
Bulb won't re-connect

### ISSUE THREAD

**Issue by jsbrich** [rospogrigio/localtuya#203]
I have several bulbs that I added in the Tuya Smart app and were working with HA.  I deleted one from the Tuya Smart App accidently and re-added it.  I'm able to control it fine through the app, but I can't get it to come up in HA.  I've confirmed the device_id and local_key value are correct by checking the IoT developer page and re-running the tuya-cli wizard command.

In HA, I get this a number of times after starting HA.  I've checked, the IP address is correct.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:548
Integration: LocalTuya (documentation, issues)
First occurred: 10:11:24 PM (12 occurrences)
Last logged: 10:23:10 PM

[eba...xeo] Connect to 192.168.68.145 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 156, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 461, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 446, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 548, in _decode_payload
    return json.loads(payload)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jsbrich** [comment]
I was able to get this working.  Turns out the local key changed, but it took awhile (I let it sit overnight) for the tuya-cli wizard to show the change.
