### ISSUE TITLE
[ISSUE] Can't config cover

### ISSUE THREAD

**Issue by Matssa56** [rospogrigio/localtuya#204]
Hi,

I'm trying to use this integration in order to control my Smart Life covers. The brand is Maxcio and I managed to get the deviceID and the localkey.

I can add the device through the integration, however I can't seem to make the cover work. I managed to make the light work on the cover using the ID 101 and with the default values (indeed it's only on or off).

For the covers, I tested with the ID 1 (value:stop) since the cover isn't in mouvement. The other ID 9 (value=25) doesn't really seem to give me any info, maybe concerns the wifi status?
Anyway, I didn't change the open close commands and I used the non positionning mode or the false one (indeed I don't have a version where the position is returned).

I can see the cover but it's in grey so I can't send any commands. Using it manually doesn't change anything.

In iot.tuya I can see that the control range is {"range":["open","stop","close"]}, maybe the issue comes from here? I mean maybe the order has something to do with the issue since in the integration it's open_close_stop.

Other than that I don't really know what I can test. What info do you need to help me out?

Thanks again!

**Comment by Matssa56** [comment]
For info I'm using V3.1.0

**Comment by Matssa56** [comment]
[localtuya.log](https://github.com/rospogrigio/localtuya/files/5623355/localtuya.log)

**Comment by Matssa56** [comment]
Fak sorry misclick

**Comment by Matssa56** [comment]
Seems like the issues comes from here:

```
2020-12-01 15:51:31 ERROR (SyncWorker_40) [homeassistant.util.logging] Exception in _update_handler when dispatching 'localtuya_21183627cc50e37576de': ({'1': 'stop', '9': 25, '101': False},)
Traceback (most recent call last):
File "/config/custom_components/localtuya/common.py", line 245, in _update_handler
self.status_updated()
File "/config/custom_components/localtuya/cover.py", line 185, in status_updated
time_diff = time.time() - self._timer_start
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

**Comment by Matssa56** [comment]
FYI having the same issue using YAML:

`localtuya:
  - host: XXXX
    device_id: XXXXX
    local_key: XXXXX
    friendly_name: Volets Bureau
    protocol_version: "3.3"
    entities:
      - platform: cover
        friendly_name: XXXXX
        id: 1
        #open_close_cmds: "on_off" # Optional, default: "on_off" ["on_off","open_close"]
        positioning_mode: "fake" # Optional, default: "none"
        #currpos_dps: 3 # Optional, required only for "position" mode
        #setpos_dps: 4  # Optional, required only for "position" mode
        span_time: 25  # Full movement time: Optional, required only for "fake" mode`

**Comment by Matssa56** [comment]
Ok my bad, the timer only works if you have the same local time as the device it seems, which is kinda logical (my system was in UTC and my real local time is +1). Changed it and it fixed everything.
