### ISSUE TITLE
requesting unknown DPS index 1

### ISSUE THREAD

**Issue by smithbill17** [rospogrigio/localtuya#220]
I'm getting more issues appearing with SmartPlugs that were previously working correctly in LocalTuya. I don't know what "_requesting unknown DPS index 1_" actual means? Updating the device and restarting HA doesn't make any difference.

```
Logger: custom_components.localtuya.switch
Source: custom_components/localtuya/pytuya/__init__.py:132
Integration: LocalTuya integration (documentation, issues)
First occurred: 9:23:54 (4 occurrences)
Last logged: 9:23:57

[046...1d9] Entity switch.kitchen_lights is requesting unknown DPS index 1
[444...666] Entity switch.landing_light is requesting unknown DPS index 1
[765...418] Entity switch.standard_lamp is requesting unknown DPS index 1
[683...9b1] Entity switch.diningroom_lamp is requesting unknown DPS index 1
```

**Comment by leva0887** [comment]
The same for me

**Comment by postlund** [comment]
It's a bit annoying that this happens because it basically means that we added an entity without receiving a value for the datapoint used to determine its state. I would expect that fetching of initial state failed. Can you please provide a debug log?

**Comment by Lebo-Wang** [comment]
I have two brands of Tuya switches. The 'gosund' one always have issues like this (succeed once before). Here is some debug info. Hope it helps:

```
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.common] [346...30d] Connecting to 192.168.1.154
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Started heartbeat loop
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Sending command heartbeat (device type: type_0a)
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Send payload: b'{}'
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Waiting for sequence number -100
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.common] [346...30d] Retrieving initial state
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Sending command status (device type: type_0a)
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Send payload: b'{"gwId":"3464370350029125b30d","devId":"3464370350029125b30d"}'
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Waiting for sequence number 1
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Got heartbeat response
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Decrypted payload: {}
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Dispatching message TuyaMessage(seqno=1, cmd=10, retcode=1, payload=b"\xc2\xca\xcd\xc9\xf7\xce\x1c#wv\x99\xfd\x84\xf9\x021Z'^\x1aS\xb8a\x99s\x82v\x89\xa1\x9a\xd3\xac", crc=2652832782)
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Dispatching sequence number 1
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Decrypted payload:
2020-12-07 00:42:40 ERROR (MainThread) [custom_components.localtuya.common] [346...30d] Connect to 192.168.1.154 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 156, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 461, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 446, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 548, in _decode_payload
    return json.loads(payload)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Closing connection
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Connection lost: None
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.pytuya] [346...30d] Closing connection
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.common] [346...30d] Disconnected: None
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.common] [346...30d] Connecting to 192.168.1.154
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.common] [346...30d] Already connecting to 192.168.1.154 (3464370350029125b30d) - False, <Task pending name='Task-1027' coro=<TuyaDevice._make_connection() running at /config/custom_components/localtuya/common.py:142> w
2020-12-07 00:42:40 DEBUG (MainThread) [custom_components.localtuya.common] [346...30d] Waiting 116 seconds before connecting
```

**Comment by postlund** [comment]
We can see for instance here:

2020-12-07 00:54:31 DEBUG (MainThread) [custom_components.localtuya.pytuya] [432...73b] Dispatching message TuyaMessage(seqno=1, cmd=10, **retcode=1**, payload=b'\xfdB\xe0...

That return code 1 is returned, which implies an error of some sort. I/we have seen this before but I don't think we have a solution for it. I feel that it's time that we try to figure out how to intercept the local traffic between the app and device, so we can see what is actually happening.

**Comment by Lebo-Wang** [comment]
> We can see for instance here:
> 
> 2020-12-07 00:54:31 DEBUG (MainThread) [custom_components.localtuya.pytuya] [432...73b] Dispatching message TuyaMessage(seqno=1, cmd=10, **retcode=1**, payload=b'\xfdB\xe0...
> 
> That return code 1 is returned, which implies an error of some sort. I/we have seen this before but I don't think we have a solution for it. I feel that it's time that we try to figure out how to intercept the local traffic between the app and device, so we can see what is actually happening.

Thanks for your kind reply. I finally turned to 'tuya-convert'. After failed on one, I succeeded on another one. I did get something useful templates as the device-specific configuration in Tasmota. It works perfect and straight-forward.

Anyway, I succeed to manage another 'KMC' device with your work. Impressive!

**Comment by Akshue** [comment]
I, too, am getting this error.  I cannot reflash these lights (Geeni) as they do not use the correct chipset.

Here is my error: 

```
Logger: custom_components.localtuya.light
Source: custom_components/localtuya/pytuya/__init__.py:132
Integration: LocalTuya (documentation, issues)
First occurred: December 28, 2020, 10:12:04 PM (2910 occurrences)
Last logged: 1:58:28 PM

    [eb0...3al] Entity light.kitchen_island_3 is requesting unknown DPS index None
    [eba...gfj] Entity light.kitchen_island_1 is requesting unset index for option color_mode
    [eba...gfj] Entity light.kitchen_island_1 is requesting unknown DPS index None
    [ebe...iq1] Entity light.kitchen_island_2 is requesting unset index for option color_mode
    [ebe...iq1] Entity light.kitchen_island_2 is requesting unknown DPS index None
```

I think some of this has to do with the color_mode.  These are white/color temp only lights.  Tuya's info for them shows the following... 

```
Code | Type | Values
-- | -- | --
switch_led | Boolean | {true,false}
bright_value | Integer | {"min":25,"scale":0,"unit":"","max":255,"step":1}
temp_value | Integer | {"min":0,"scale":0,"unit":"","max":255,"step":1}
```
And, they are set up in config flow
```
ID : 1 (on/off)
Brightness : 2
Color Temp : 3
Brightness Lower/Upper 25-255
Color mode/color (blank)
color temp 2700-6500
scene/music blank

Is localtuya trying to set the color_mode to white?

**Comment by postlund** [comment]
Please try running from `master`.

**Comment by garry0garry** [comment]
Home Assistant v2022.2.9
HIPER IoT Weather Station P1

WARNING (SyncWorker_2) [custom_components.localtuya.sensor] [324...7d7] Entity sensor.hiper_temperature_internal is requesting unknown DPS index 101
WARNING (SyncWorker_2) [custom_components.localtuya.sensor] [324...7d7] Entity sensor.hiper_humidity_internal is requesting unknown DPS index 102
WARNING (SyncWorker_2) [custom_components.localtuya.sensor] [324...7d7] Entity sensor.hiper_temperature_ext1 is requesting unknown DPS index 103
WARNING (SyncWorker_2) [custom_components.localtuya.sensor] [324...7d7] Entity sensor.hiper_temperature_ext2 is requesting unknown DPS index 106
WARNING (SyncWorker_2) [custom_components.localtuya.sensor] [324...7d7] Entity sensor.hiper_humidity_ext1 is requesting unknown DPS index 104
WARNING (SyncWorker_2) [custom_components.localtuya.sensor] [324...7d7] Entity sensor.hiper_pressure is requesting unknown DPS index 110

How can this be fixed?
