### ISSUE TITLE
Updating from 3.1 to master results in .JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by bigretromike** [rospogrigio/localtuya#258]
```

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:559
Integration: LocalTuya integration (documentation, issues)
First occurred: 14:38:04 (180 occurrences)
Last logged: 14:53:01
[646...a6f] Connect to 192.168.1.31 failed

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 149, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 457, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 559, in _decode_payload
    return json.loads(payload)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by postlund** [comment]
Strange, wouldn't expect that kind of error. Please enable debug logs and include them here.

https://github.com/rospogrigio/localtuya#debugging

**Comment by bigretromike** [comment]
I added:
```
logger:
  default: warning
  logs:
    custom_components.localtuya: debug
```
to configuration.yaml

Where I will find log after reboot ?

**Comment by bigretromike** [comment]
Do you need more logs ?

**Comment by postlund** [comment]
Those will do! I have probably messed something up. Can you email me the local key if the device?

**Comment by bigretromike** [comment]
> 
> 
> Those will do! I have probably messed something up. Can you email me the local key if the device?

You should have them on mail.

**Comment by postlund** [comment]
I think we concluded that the local key is wrong (old), but @bigretromike will have to confirm that. Please close the issue if that was the case.

**Comment by bigretromike** [comment]
@postlund, yes. Looks like the key was wrong. thanks with debugging process
