### ISSUE TITLE
tuya local Failed to authenticate with device but the key is correct 

### ISSUE THREAD

**Issue by toben1997** [rospogrigio/localtuya#277]
i have no idea i am a noob, all my light and sockets are working but not my touch wall switches
 

`Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 499, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 461, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 446, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 533, in _decode_payload
    payload = self.cipher.decrypt(payload, False)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 196, in decrypt
    return self._unpad(decryptor.update(enc) + decryptor.finalize()).decode()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 164, in finalize
    data = self._ctx.finalize()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 181, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.`

**Comment by ultratoto14** [comment]
did you try with 3.1 and 3.3 protocol ?

**Comment by toben1997** [comment]
yes i get the error with the 3.3 protocol and with the 3.1 i only get: "An unknown error occurred" so i think 3.1 is the wrong protocol

**Comment by jlcash61** [comment]
I had same problem with two wall dimmers.  They have same model number but if you look at firmware version the one that works is Main Module V1.0.2 and the one that didn't is V1.0.3.  I have not found a work around yet, but will post if I do.
