### ISSUE TITLE
Cant add device with config flow or yaml....

### ISSUE THREAD

**Issue by szbbalint** [rospogrigio/localtuya#287]
Hi guys, firs i wish you a happy new year :) 
So my problem is that i cant add my devices to hassio with localtuya. I have 4 pcs martin jerry 3 way dimmer (not switch),  they runing the latest firmware according to the tuya smart app. I have received the key and id pairs for each devices (with tuyacli). Installed localtuya in hacs, restart, then im trying to instal the localtuya integration. A window with a list of my devices with the correct IP adresses appear, i selected one of them (tried all of them), and then i named it "Folyosó" (its like hallway in my language, but i think it doesnt matter), copypaste the local key (1ffk56d065e19108 it looks like this), the host and the device id is already filled out with the correct value. Then i select the protocol, first i try with the 3.3, then i got this erroe:
----Failed to authenticate with device. Verify that device id and local key are correct.-----
im really sure that the device id and the key is correct, 
then i try with protocol 3.1, with this error:
-----An unknown error occurred. See log for details.----
and the logs (ther are thrre of them)

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 457, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 544, in _decode_payload
    payload = self.cipher.decrypt(payload, False)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 196, in decrypt
    return self._unpad(decryptor.update(enc) + decryptor.finalize()).decode()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 164, in finalize
    data = self._ctx.finalize()
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 181, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 457, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 554, in _decode_payload
    raise Exception(f"Unexpected payload={payload}")
Exception: Unexpected payload=b'json obj data unvalid'

Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 279, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 192, in validate_input
    detected_dps = await interface.detect_available_dps()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 457, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 554, in _decode_payload
    raise Exception(f"Unexpected payload={payload}")
Exception: Unexpected payload=b'json obj data unvalid'

And if i trying to add it manually in config.yaml, tha entiti does not work... no matter what parameters i have added in the config...

Im a bit nervous because of this, i think its a minor and easy problem but i cant figure it out. Is there anybody who can help me? 
Thank you :)

**Comment by szbbalint** [comment]
?

**Comment by vide** [comment]
@szbbalint did you manage to fix it? if so, how? Thanks!

**Comment by szbbalint** [comment]
Nope. Im using the tuya cloud integration instead of this, its not perfect but i an use my stuff in hassio at least.

**Comment by nutellax** [comment]
Any fix found?

**Comment by nutellax** [comment]
I found a fix that worked for me: you need to make sure that all of the apps on your devices are closed, once i closed the Smartlife app on all my devices, it started working again.
