### ISSUE TITLE
Exception on scene selection

### ISSUE THREAD

**Issue by poofeg** [rospogrigio/localtuya#306]
Version of localtuya: v3.2.0
Device: Yandex lamp (YNDX-00010)
Product ID: muushnich7dcbbxi
Type: Light Source
Actions before exception: select any scene
Exception:
```
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/localtuya/common.py", line 239, in _update_handler
    self.status_updated()
  File "/home/homeassistant/.homeassistant/custom_components/localtuya/light.py", line 414, in status_updated
    self._effect = self.__find_scene_by_scene_data(
  File "/home/homeassistant/.homeassistant/custom_components/localtuya/light.py", line 275, in __find_scene_by_scene_data
    return next(
  File "/home/homeassistant/.homeassistant/custom_components/localtuya/light.py", line 276, in <genexpr>
    (item for item in self._effect_list if self._scenes[item] == data),
KeyError: 'Custom'
```
Scenes DPS updates:
* Night: `{"22":200,"23":0,"25":"00"}`
* Read: `{"22":1000,"23":500,"25":"01"}`
* Working: `{"22":1000,"23":1000,"25":"02"}`
* Leisure: `{"22":500,"23":500,"25":"03"}`
* Soft: `{"25":"04"}`
* Colorful: `{"25":"05"}`
* Dazzling: `{"25":"06"}`
* Gorgeous: `{"25":"07"}`

**Comment by ultratoto14** [comment]
Scenes are not well supported at the moment. It will be better supported once we have a device database. 
For the error you have, I created a PR a few days ago #291 that should fix that exact problem.

**Comment by ThomasCr** [comment]
maybe also helpful: https://github.com/rospogrigio/localtuya/issues/659
