### ISSUE TITLE
How use a type : Flooding Detector

### ISSUE THREAD

**Issue by g02jeff-hass** [rospogrigio/localtuya#315]
This plugin works perfeclty with my lights, my plugs but I can't use my flooding detector. 
I can see my product on iot.tuya.com but discovery don't find it. 
And I can't add with ... option. 
Could you help me please?

**Comment by ultratoto14** [comment]
Passive sensors are not yet supported as they cannot be contacted directly

**Comment by RASBR** [comment]
Hi,
any update on this sensor type? will they be added soon?



Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:637
Integration: LocalTuya integration (documentation, issues)
First occurred: 0:30:53 (4 occurrences)
Last logged: 0:39:54

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 279, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 185, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.100.113', 6668)
