### ISSUE TITLE
Cover timed position error: TypeError: unsupported operand type(s) for -: 'float' and 'str'

### ISSUE THREAD

**Issue by marciprete** [rospogrigio/localtuya#325]
Hello all, 
i am running HomeAssistant 2021.1.4 on a Raspberry Pi 4 with HomeAssistant OS 5.10.

I configured several curtain switch modules, that is the LoraTap SC500W via local tuya, with the 1_2_3 command set and TIMED positioning mode and 34s for the opening time.
Unfortunately, I experience the following errors:
1. Every time I open the entity page the slider is set to position 3
2. If I click on one the opening arrow, the shutter starts opening, but if I click the stop button, the shutter actually stops, but the opening button remains unavailable, as if it's still opening. Also the icon of the shutter is in the opening state and it become available again after the 34s. Once the process is finishes, the slider returns on the position 3
3. If i try to move the slider, I get the following exception:

```
[2821091280] unsupported operand type(s) for -: 'float' and 'str'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/config/custom_components/localtuya/cover.py", line 128, in async_set_cover_position
    posdiff = abs(newpos - currpos)
TypeError: unsupported operand type(s) for -: 'float' and 'str'
```

Thanks in advance for your help and don't hesitate to ask more information.

**Comment by marciprete** [comment]
Well, after some experiments, I decided to removed all my previously configured devices and reinstall them. This worked, and all the new devices started working as expected. 

The only issue that still remains is on the cover icon: it never changes its status to closed. 
Anyway, this is not very important so I will close the issue as resolved.

Thanks

**Comment by dingausmwald** [comment]
Same problem here. There seems to be a dead entry to the device. Deleting and recreating the broken blinds doesnt help, even with correct settings.
