### ISSUE TITLE
Permanent statuses - not available, connecting. Smart socket 4 * 220v + USB.

### ISSUE THREAD

**Issue by u102132** [rospogrigio/localtuya#354]
Permanent statuses - not available, connecting. Smart socket 4 * 220v + USB.
Connection:
# Tuya devices
localtuya:
  - host: 192.168.1.55
    device_id: 20276371f4cfa2086f08
    local_key: 0e187b4f1adc9999
    friendly_name: Switch 4*220 + (4*usb)
    protocol_version: "3.3"
    entities:
    - platform: switch
      friendly_name: Switch 1 220-1
      id: 1
    - platform: switch
      friendly_name: Switch 1 R-Pi
      id: 2 
    - platform: switch
      friendly_name: Switch 1 220-3
      id: 3
    - platform: switch
      friendly_name: Switch 1 220-4
      id: 4
    - platform: switch
      friendly_name: Switch 1 USB
      id: 5 

Journal:
Switch 1 220-1 включается
12:59:24 - 1 мин. назад
Switch 1 USB изменяет состояние на "Недоступно"
12:59:15 - 1 мин. назад
Switch 1 220-4 изменяет состояние на "Недоступно"
12:59:15 - 1 мин. назад
Switch 1 220-3 изменяет состояние на "Недоступно"
12:59:15 - 1 мин. назад
Switch 1 R-Pi изменяет состояние на "Недоступно"
12:59:15 - 1 мин. назад
Switch 1 220-1 изменяет состояние на "Недоступно"
12:59:15 - 1 мин. назад
Switch 1 USB включается
12:58:19 - 2 мин. назад
Switch 1 220-4 включается
12:58:19 - 2 мин. назад
Switch 1 220-3 включается
12:58:19 - 2 мин. назад
Switch 1 R-Pi включается
12:58:19 - 2 мин. назад
Switch 1 220-1 включается
12:58:19 - 2 мин. назад

In so-constantly...
Switching all sockets - working.

**Comment by u102132** [comment]
In Log 1 Error:

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:240
Integration: LocalTuya integration (documentation, issues)
First occurred: 12:32:47 (1 occurrences)
Last logged: 12:32:47

[202...f08] Failed to set DP 3 to 0
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 174, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 489, in set_dp
    return await self.exchange(SET, {str(dp_index): value})
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 451, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 240, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

**Comment by u102132** [comment]
Connected Rpi via cable - reconnection stopped. Before that, there was a connection via WIFI 5 or WIFI 2.4, an explicit prescription of upnp: local_ip: 192.168. *. * - didn't help ...
