### ISSUE TITLE
Fail to have integration working

### ISSUE THREAD

**Issue by gamilevin** [rospogrigio/localtuya#356]
I have 12 devices defined in Tuya integration. I want to check out TuyaLocal in order to have better automation on a smart plug consumption and the ability to add to home assistant an oil diffuser which I have.

I guess the problem could be that the device which I'm trying to add to TuyaLocal is still defined within the Tuya integration.
I deleted it from the SmartLife app, disabled it from Tuya integration, randeleted the entity, tuya.force_update service and restarted HAb but it's still there... :(

When I tried to define this smart plug using the integration UI manually I got the progress spinning for a while and then an error..
This is the error from the log:
`Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 279, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 185, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.39', `6668)``

I'm quite new to HA but would love to get some help as this integration seems perfect for me.

Thanks :)

**Comment by ropmip** [comment]
I have tuya integration and localtuya at the same time and they both work at the same time (also via smart life or tuya app), so that should not be the problem. Install via HACS and add your devices via integrations menu and it should work.
