### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by ranrinc** [rospogrigio/localtuya#391]
Upgrade localtuya 3.2.2 to the latest update on hacs and running the latest HA 2021.3.3

Somehow the tuya device becomes unstable upon start most devices will be unavailable and after reboot localtuya it will become available, however, the switches don't work at all. Error saying that the device already being configured appears on my portainer.

The current solution is to downgrade to 3.2.1 which working perfectly -> no error message

**Comment by AdmiralStipe** [comment]
Same here, just... sometimes it works quite OK, but sometimes even after multiple restarts of core it's still not working... At previous versions I called service localtuya/reload a minute after core restart and it came alive, now it doesn't.  
Also service can not be called, it reports: "Failed to call service localtuya/reload."

Oh well, reverting to 3.2.1... and most likely won't be upgrading anymore, as with every upgrade something goes wrong and I can't make use of any new functions at all...

**Comment by postlund** [comment]
Please enable debug logs and provide a detailed flow of what happens and when. I don't understand why the latest release would cause any issues as it only adds new logic on top of the existing connect logic. As I cannot reproduce this myself, I need help understanding the behavior.

**Comment by imkebe** [comment]
Same here, I will provide log.

**Comment by imkebe** [comment]
I've posted #398 cause my problems may be different. However you can follow up.

**Comment by ranrinc** [comment]
The error logs

```
2021-03-16 17:47:14 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Family Room Outlet (YAML) for switch

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup

    result = await component.async_setup_entry(hass, self)  # type: ignore

  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry

    return await hass.data[DOMAIN].async_setup_entry(entry)

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry

    raise ValueError("Config entry has already been setup!")

ValueError: Config entry has already been setup!

2021-03-16 17:47:14 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Mom Room Outlet (YAML) for switch

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup

    result = await component.async_setup_entry(hass, self)  # type: ignore

  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry

    return await hass.data[DOMAIN].async_setup_entry(entry)

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry

    raise ValueError("Config entry has already been setup!")

ValueError: Config entry has already been setup!
```

**Comment by ranrinc** [comment]
In some other cases

```
2021-03-16 17:50:30 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Family Room Outlet (YAML) for switch

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup

    result = await component.async_setup_entry(hass, self)  # type: ignore

  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry

    return await hass.data[DOMAIN].async_setup_entry(entry)

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry

    raise ValueError("Config entry has already been setup!")

ValueError: Config entry has already been setup!

2021-03-16 17:50:31 WARNING (MainThread) [homeassistant.loader] You are using a custom integration plex_recently_added which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-03-16 17:50:32 ERROR (MainThread) [custom_components.smartir.climate] Unable to update from temperature sensor: could not convert string to float: 'unavailable'

2021-03-16 17:50:32 ERROR (MainThread) [custom_components.smartir.climate] Unable to update from humidity sensor: could not convert string to float: 'unavailable'

2021-03-16 17:50:36 WARNING (SyncWorker_14) [custom_components.localtuya.binary_sensor] [eb1...ulq] Entity binary_sensor.front_room_ac_plug_status is requesting unknown DPS index 1

2021-03-16 17:50:36 WARNING (SyncWorker_14) [custom_components.localtuya.binary_sensor] [eb1...ulq] State for entity binary_sensor.front_room_ac_plug_status did not match state patterns

2021-03-16 17:50:36 WARNING (SyncWorker_15) [custom_components.localtuya.switch] [eb1...ulq] Entity switch.front_room_ac_plug_status is requesting unknown DPS index 1

2021-03-16 17:50:36 WARNING (SyncWorker_15) [custom_components.localtuya.sensor] [eb1...ulq] Entity sensor.front_room_ac_plug_current is requesting unknown DPS index 18

2021-03-16 17:50:36 WARNING (SyncWorker_15) [custom_components.localtuya.sensor] [eb1...ulq] Entity sensor.front_room_ac_plug_current_consumption is requesting unknown DPS index 19

```

**Comment by petruut** [comment]
here's a stupid question - how do you revert to a previous version without removing all of the switches I've registered?

**Comment by AdmiralStipe** [comment]
> here's a stupid question - how do you revert to a previous version without removing all of the switches I've registered?

If in HACS, choose Reinstall (from three dots menu of Localtuya) and just select desired version. Restart core after reinstall. 
If manually, just replace the files in "custom_components/localtuya". Restart core after replacing the files.
