### ISSUE TITLE
[Errno 113] Connect call failed 

### ISSUE THREAD

**Issue by Snuffy2** [rospogrigio/localtuya#429]
In the past few days, the error below has been firing repeatedly for all of my Treatlife Lights setup through the Tuya Local interface. Interestingly, the bulbs continue to work just fine through Home Assistnt.

2021-03-31 19:54:07 ERROR (MainThread) [custom_components.localtuya.common] [eb0...ukz] Connect to 192.168.101.177 failed
Traceback (most recent call last):
File "/config/custom_components/localtuya/common.py", line 139, in _make_connection
self._interface = await pytuya.connect(
File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
_, protocol = await loop.create_connection(
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
return await fut
File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.101.177', 6668)

**Comment by postlund** [comment]
One connection attempt probably fails (for whatever reason) and then succeeds when re-connecting. Do you see any other related errors in the log?

**Comment by Snuffy2** [comment]
Nevermind. I missed that a Smart Plug that I only infrequently use had become unplugged. Sorry about that.
