### ISSUE TITLE
Problem to integrate the PIR motion sensor

### ISSUE THREAD

**Issue by braudoo** [rospogrigio/localtuya#432]
After have follow the procedure to add a PIR sensor, the HA don't see the device.
This the steps that I have make:
- installed Local Tuya by HACS
- followed the guide to find the device's Key and ID
-  added to configuration.yaml the device + entity:

localtuya:
  - host: 192.168.1.x
    device_id: 8242418584f3ebfxxxxx
    local_key: d0a2a84d72f7xxxxxx
    friendly_name: Tuya Device
    protocol_version: "3.3"
    entities:
      - platform: binary_sensor
        friendly_name: PIR Status
        id: 1
        device_class: motion
        state_on: "true" # Optional
        state_off: "false" # Optional

restarted the HA.

But the device is not available.

I think to have follow correctly every step but the device is not see.

Can you help me?

**Comment by postlund** [comment]
Start by checking the logs, then by doing a DP dump (see [here](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump)). Hopefully we can get further after that.

**Comment by braudoo** [comment]
Thanks for the reply.
Below the log regarding the device that HA don't  see:

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:646
Integration: LocalTuya integration (documentation, issues)
First occurred: 23:12:53 (2 occurrences)
Last logged: 23:13:52

[824...8fb] Connect to 192.168.1.3 failed
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/localtuya/common.py", line 144, in _make_connection self,
  File "/home/homeassistant/.homeassistant/custom_components/localtuya/pytuya/__init__.py", line 646, in connect port,
  File "/usr/lib/python3.7/asyncio/base_events.py", line 959, in create_connection raise exceptions[0]
  File "/usr/lib/python3.7/asyncio/base_events.py", line 946, in create_connection await self.sock_connect(sock, address)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 464, in sock_connect return await fut
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 494, in _sock_connect_cb raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.3', 6668)

It's very strange becouse it seems don't match ID device with the host.

Do you have some theory?

Regarding the DP dumping, I don't know where I have to save tuyadebug folder, for made the test.

**Comment by braudoo** [comment]
Dear Pierre can you help me yet?

**Comment by iotinkognito** [comment]
What type of PIR sensor are you using? Wifi, Bluetooth or ZigBee?

**Comment by dimmuboy** [comment]
I have similar issue with Wifi PIR sensor

**Comment by slurpey** [comment]
Hi guys, I concur.  I have a wifi Pir sensor which I sort of like because I'm full of faraday cages in my house and zigbee fails..
![image](https://user-images.githubusercontent.com/10026060/156397413-f0681f70-ee5e-47e7-9514-8991ea063170.png)
https://nl.aliexpress.com/item/4000125912484.html

It's slow as hell using smartlife.  Would love to be able to add to local tuya - but I get an error - I also suppose integraton is not supported (I tried via UI - I have several other devices that work fine).

Thanks

**Comment by camnop** [comment]
**tuya-cli get --ip xx.xx.xx.xx --key xxxxxx --id yyyyyy --protocol-version 3.3 --full**

{ dps: { '1': 'pir' } }

### **Standard Status Set:**

<html>
<body>


Code | Type | Values
-- | -- | --
pir | Enum | {   "range": [     "pir",     "none"   ] }
battery_percentage | Integer | {   "unit": "%",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }


</body>
</html>

```

    entities:
      - platform: sensor
        friendly_name: _pir_
        id: 1
        device_class: motion
        state_on: "pir" # Optional
        state_off: "none" # Optional


```
