### ISSUE TITLE
Entity with this ID has already been configured.

### ISSUE THREAD

**Issue by acs-lux** [rospogrigio/localtuya#460]
## The problem
Adding a device that was previously added and removed fails with the error:

Entity with this ID has already been configured.

## Environment
- Localtuya version: 3.2.2
- Last working localtuya version : Unknown
- Home Assistant Core version: core-2021.4.6
  Installation Type | Home Assistant OS
  Development | false
  Supervisor | true
  Docker | true
  Virtual Environment | false
  Python Version | 3.8.7
  Operating System Family | Linux
  Operating System Version | 5.4.109
  CPU Architecture | x86_64

 
- [] Are you using the Home Assistant Tuya Cloud component ? No
- [] Are you using the Tuya App in parallel ? Not at the same time (rarely use the app)

## Steps to reproduce

1. Remove device from Local Tuya integration
2. Ensure entities no longer exist
3. Try to add the device again

## Configuration `configuration.yaml` or `config_flow`

  - platform: template
    switches:

      lounge_tv:
        friendly_name: "Lounge TV"
        value_template: "{{ is_state('switch.lounge_tv_tuya', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.lounge_tv_tuya
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.lounge_tv_tuya
        icon_template: mdi:television

Appears in Discovered devices:

431883812cfxxxxxxxxx (Lounge TV Tuya) but can not be added as was previously and the switch integration is not removed as expected.

The Local Tuya entity of switch.lounge_tv_tuya is always unavailable, is not shown in the list of Local Tuya Integration and can not be added again. If the entity is deleted this has no effect, it can not be added.

## Provide Home Assistant taceback/logs

Not really relevant but maybe important:

ConnectionResetError: [Errno 104] Connect call failed ('192.168.178.56', 6668)
2021-04-26 11:39:36 ERROR (MainThread) [custom_components.localtuya.common] [050...443] Connect to 192.168.178.61 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 139, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionResetError: [Errno 104] Connect call failed ('192.168.178.61', 6668)
2021-04-26 11:39:43 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'TimeoutError'
2021-04-26 11:39:43 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform androidtv is taking over 10 seconds.
2021-04-26 11:39:43 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform androidtv is taking over 10 seconds.
2021-04-26 11:39:43 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform systemmonitor is taking over 10 seconds.
2021-04-26 11:39:43 WARNING (SyncWorker_4) [custom_components.localtuya.switch] [050...06d] Entity switch.lounge_skts_tuya is requesting unknown DPS index 1
2021-04-26 11:39:44 WARNING (SyncWorker_4) [custom_components.localtuya.switch] [453...43f] Entity switch.kitchencam_skt_tuya is requesting unknown DPS index 1
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform gigasetelements is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.
2021-04-26 11:39:44 WARNING (SyncWorker_8) [custom_components.localtuya.switch] [431...aac] Entity switch.kitchen_tv_tuya is requesting unknown DPS index 1

## Additional information
Sometimes after restarting all Local Tuya entities are unavailable and reloading does not fix it. Only downgrading and updating the Integration in HACS seems to work.

**Comment by acs-lux** [comment]
I no longer have this issue. No idea why but its all good now.

**Comment by atjshop** [comment]
I am having exact same issue. Tried reboot HA still same error.

**Comment by leocaseiro** [comment]
I had the same issue, and I had to manually remove from the `.storage`.

If you want to try, make sure you know how to read and write JSON.

**FIRST: MAKE SURE YOU SAVE A BACKUP, IN CASE SOMETHING GOES BAD!**


I don't know which is the correct file, so I removed the entities I wanted via samba from all the 3 files: 

* /config/.storage/core.config_entries
* /config/.storage/core.device_registry
* /config/.storage/core.restore_state


Restart HA!
