### ISSUE TITLE
Unexpected exception when adding items

### ISSUE THREAD

**Issue by Monacoslo** [rospogrigio/localtuya#467]
## Environment

- Localtuya version: <latest update> 
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version: <Home Assistant 2021.4.5> 
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Integrations, add, LocalTuya
2. Select discovered devices
3. Enter name and local key

## Configuration `configuration.yaml` or `config_flow`

```yaml

```

## Provide Home Assistant taceback/logs

```Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:637
Integration: LocalTuya (documentation, issues)
First occurred: April 27, 2021, 11:29:28 AM (1 occurrences)
Last logged: April 27, 2021, 11:29:28 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 279, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 185, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.84', 6668)


```

**Comment by fatboysalimshady** [comment]
I get the same thing, although I have yet to try blocking the DNS as stated in the readme... not sure

**Comment by MikhailLS** [comment]
The same problem. I have two devices. The socket normaly added. But themperature sensor cant add.
