### ISSUE TITLE
static vs dynamic ip addresses

### ISSUE THREAD

**Issue by hros** [rospogrigio/localtuya#478]
I am seeing connection failure messages in the home assistant log:
```log
Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:240
Integration: LocalTuya (documentation, issues)
First occurred: May 10, 2021, 12:45:29 PM (7 occurrences)
Last logged: 12:39:32 PM

[..................] Connect to 192.168.0.109 failed
[..................] Connect to 192.168.0.102 failed
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/custom_components/localtuya/common.py", line 149, in _make_connection
    status = await self._interface.status()
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 451, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 240, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

could this be related to the fact that my tuya devices are using dynamic (dhcp) ip addresses? or are dynamic addresses OK and this is due to actual connection problems?

**Comment by TheGabeMan** [comment]
All my devices are using DHCP with reservations set in DHCP. Never have these issues.
