### ISSUE TITLE
Unable to set up Tuya Bulb.

### ISSUE THREAD

**Issue by naijaping** [rospogrigio/localtuya#479]
Hi guys,

Thanks for this addon, please am having the following  error while trying to set up my Novostella light bulb.

Previously, I was able to control this bulb locally via Homebridge.  I have all the keys and Id etc.

Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:240
Integration: LocalTuya integration (documentation, issues)
First occurred: 16:02:20 (1 occurrences)
Last logged: 16:02:20

[147...cd2] Failed to get status:
Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 451, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 240, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

Thanks for any hint on this error

**Comment by rzarobbie** [comment]
Same issue here.  However, my device is a switch.  

Internet: check
Ping; check
Reset device and got new local key: check

But this device shows up for a short amount of time to initiate setup, but ends with the same timeout error.
