### ISSUE TITLE
Error: No permissions. This API is not subscribed.

### ISSUE THREAD

**Issue by lironas** [rospogrigio/localtuya#490]
I'm getting this error

can you help?

[
  Error: No permissions. This API is not subscribed.
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  Error: No permissions. This API is not subscribed.
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  Error: No permissions. This API is not subscribed.
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5),
  Error: No permissions. This API is not subscribed.
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/openapi/dist/api.js:74:31)
      at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
]

**Comment by yousefabed** [comment]
Try this:
In your Tuya IoT project, go the API and search for "Smart Home Devices Management" and subscribe.

**Comment by del13r** [comment]
Hi,

I followed all the instructions too and got this

`tuya-cli link --api-key XXX --api-secret XXX --schema XXX --ssid XXX --password XXX --region eu
✖ Device(s) failed to be registered!
Error: No permissions. This API is not subscribed.
    at OpenAPI._client.got_1.default.extend.hooks.afterResponse (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/@tuyapi/link/node_modules/@tuyapi/openapi/dist/api.js:68:31)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/got/dist/source/as-promise.js:87:38)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

I also subscribed to 'Smart Home Devices Management' API

**Comment by kalyway101** [comment]
I wanted to follow up and say I am getting the exact same issue. Even after the directions were updated and I "subscribed"

**Comment by del13r** [comment]
> I wanted to follow up and say I am getting the exact same issue. Even after the directions were updated and I "subscribed"

I found another way to do this without using the command line app.

see my post here 
https://community.home-assistant.io/t/inkbird-ibs-m1-with-ibs-p01/255050/20?u=del13r

**Comment by kalyway101** [comment]
> > I wanted to follow up and say I am getting the exact same issue. Even after the directions were updated and I "subscribed"
> 
> I found another way to do this without using the command line app.
> 
> see my post here
> https://community.home-assistant.io/t/inkbird-ibs-m1-with-ibs-p01/255050/20?u=del13r

This worked fantastically well!! Getting the local key via the API Explorer was incredibly easy and didn't require me to run any commands or setup npm (though I had already done this). I'll definitely recommend this method via the issue from the original tuyaapi repo here: https://github.com/codetheweb/tuyapi/issues/485
