### ISSUE TITLE
Lightbulb becomes unavailable

### ISSUE THREAD

**Issue by Lahvuun** [rospogrigio/localtuya#495]
## The problem

Every now and then my tuya lightbulb becomes unavailable in home-assistant. I can still turn it on and off, change the brightness, but it's listed as unavailable and I get errors in home-assistant's log.

## Environment

- Localtuya version: v3.2.2
- Last working localtuya version (if known and relevant): N/A
- Home Assistant Core version: core-2021.5.5
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. wait until `tuya-cli get --key ... --id ... --ip 192.168.1.104 --protocol-version 3.3 --dps 4` stops returning a numeric value;
2. restart home-assistant.

## Configuration `configuration.yaml` or `config_flow`

```yaml
automation: !include automations.yaml
default_config: {}
homeassistant:
  elevation: ...
  latitude: ...
  longitude: ...
  name: Home
  time_zone: Europe/Kiev
  unit_system: metric
http:
  server_port: 8123
localtuya:
- device_id: ...
  entities:
  - brightness: 3
    brightness_lower: 25
    brightness_upper: 255
    color: 5
    color_mode: 2
    color_temp: 4
    color_temp_max_kelvin: 6500
    color_temp_min_kelvin: 2700
    friendly_name: lightbulb
    id: 1
    platform: light
    scene: 6
  friendly_name: lightbulb
  host: 192.168.1.104
  local_key: ...
  protocol_version: '3.3'

```

## DP dump

```
INFO:localtuya:localtuya version 1.0.0
INFO:localtuya:Python 3.8.10 (default, May 18 2021, 20:50:58)
[GCC 11.1.1 20210428] on linux
INFO:localtuya:Using pytuya version '8.1.0'
INFO:localtuya:Detecting list of available DPS of device ... [192.168.1.104], protocol 3.3.
DEBUG:localtuya.pytuya:Sending command status (device type: type_0a)
DEBUG:localtuya.pytuya:paylod=b'{"gwId":"...","devId":"..."}'
DEBUG:localtuya.pytuya:DATA RECEIVED!
DEBUG:localtuya.pytuya:decode payload=...
DEBUG:localtuya.pytuya:decrypted result='{"dps":{"1":true,"3":186}}'
AVAILABLE DPS ARE [{'1': True, '3': 186}]
INFO:localtuya:COMPLETE response from device ... [192.168.1.104].

**** deviceInfo returned OK ****

TuyaDebug (Tuya DPs dump) [1.0.0]

Device ... at 192.168.1.104 key ... protocol 3.3 dev_type type_0a:
    DPS [1] VALUE [True]
    DPS [3] VALUE [186]
```
## Provide Home Assistant taceback/logs

```txt
...
Jun 01 19:44:12 rockpro hass[21743]: 2021-06-01 19:44:12 WARNING (MainThread) [custom_components.localtuya.light] [bf1...wow] Entity light.lightbulb is requesting unknown DPS index 2
Jun 01 19:44:13 rockpro hass[21743]: 2021-06-01 19:44:13 WARNING (SyncWorker_1) [custom_components.localtuya.light] [bf1...wow] Entity light.lightbulb is requesting unknown DPS index 5
Jun 01 19:44:13 rockpro hass[21743]: 2021-06-01 19:44:13 WARNING (SyncWorker_1) [custom_components.localtuya.light] [bf1...wow] Entity light.lightbulb is requesting unknown DPS index 4
Jun 01 19:44:13 rockpro hass[21743]: 2021-06-01 19:44:13 WARNING (SyncWorker_1) [custom_components.localtuya.light] [bf1...wow] Entity light.lightbulb is requesting unknown DPS index 2
Jun 01 19:44:13 rockpro hass[21743]: 2021-06-01 19:44:13 WARNING (SyncWorker_1) [custom_components.localtuya.light] [bf1...wow] Entity light.lightbulb is requesting unknown DPS index 2
Jun 01 19:44:13 rockpro hass[21743]: 2021-06-01 19:44:13 WARNING (MainThread) [custom_components.localtuya.light] [bf1...wow] Entity light.lightbulb is requesting unknown DPS index 2
Jun 01 19:44:13 rockpro hass[21743]: 2021-06-01 19:44:13 WARNING (MainThread) [custom_components.localtuya.light] [bf1...wow] Entity light.lightbulb is requesting unknown DPS index 2
Jun 01 19:44:13 rockpro hass[21743]: 2021-06-01 19:44:13 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Jun 01 19:44:13 rockpro hass[21743]: Traceback (most recent call last):
Jun 01 19:44:13 rockpro hass[21743]:   File "/nix/store/3cxzszmz46awjg2dyxplcx2qhjws1bcn-homeassistant-2021.5.5/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 321, in async_update_ha_state
Jun 01 19:44:13 rockpro hass[21743]:     self._async_write_ha_state()
Jun 01 19:44:13 rockpro hass[21743]:   File "/nix/store/3cxzszmz46awjg2dyxplcx2qhjws1bcn-homeassistant-2021.5.5/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 370, in _async_write_ha_state
Jun 01 19:44:13 rockpro hass[21743]:     attr.update(self.state_attributes or {})
Jun 01 19:44:13 rockpro hass[21743]:   File "/nix/store/3cxzszmz46awjg2dyxplcx2qhjws1bcn-homeassistant-2021.5.5/lib/python3.8/site-packages/homeassistant/components/light/__init__.py", line 740, in state_attributes
Jun 01 19:44:13 rockpro hass[21743]:     color_mode = self._light_internal_color_mode
Jun 01 19:44:13 rockpro hass[21743]:   File "/nix/store/3cxzszmz46awjg2dyxplcx2qhjws1bcn-homeassistant-2021.5.5/lib/python3.8/site-packages/homeassistant/components/light/__init__.py", line 590, in _light_internal_color_mode
Jun 01 19:44:13 rockpro hass[21743]:     if COLOR_MODE_COLOR_TEMP in supported and self.color_temp is not None:
Jun 01 19:44:13 rockpro hass[21743]:   File "/var/lib/hass/custom_components/localtuya/light.py", line 205, in color_temp
Jun 01 19:44:13 rockpro hass[21743]:     ((self._max_mired - self._min_mired) / self._upper_color_temp)
Jun 01 19:44:13 rockpro hass[21743]: TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```
## Additional information

It looks like after some time the lightbulb stops reporting values for some DPs, as seen in the DP dump only having two DPs. However, if value is set, then it is reported again for some time:
```
lahvuun@lahvuun ~ tuya-cli get --key ... --id ... --ip 192.168.1.104 --protocol-version 3.3 --dps 4
undefined
lahvuun@lahvuun ~ tuya-cli set --key ... --id ... --ip 192.168.1.104 --protocol-version 3.3 --dps 4 --set 100
Set succeeded.
lahvuun@lahvuun ~ tuya-cli get --key ... --id ... --ip 192.168.1.104 --protocol-version 3.3 --dps 4
100
```
It then appears in the DP dump:
```
INFO:localtuya:localtuya version 1.0.0
INFO:localtuya:Python 3.8.10 (default, May 18 2021, 20:50:58)
[GCC 11.1.1 20210428] on linux
INFO:localtuya:Using pytuya version '8.1.0'
INFO:localtuya:Detecting list of available DPS of device ... [192.168.1.104], protocol 3.3.
DEBUG:localtuya.pytuya:Sending command status (device type: type_0a)
DEBUG:localtuya.pytuya:paylod=b'{"gwId":"...","devId":"..."}'
DEBUG:localtuya.pytuya:DATA RECEIVED!
DEBUG:localtuya.pytuya:decode payload=...
DEBUG:localtuya.pytuya:decrypted result='{"dps":{"1":true,"3":186,"4":100}}'
AVAILABLE DPS ARE [{'1': True, '3': 186, '4': 100}]
INFO:localtuya:COMPLETE response from device ... [192.168.1.104].

**** deviceInfo returned OK ****

TuyaDebug (Tuya DPs dump) [1.0.0]

Device ... at 192.168.1.104 key ... protocol 3.3 dev_type type_0a:
    DPS [1] VALUE [True]
    DPS [3] VALUE [186]
    DPS [4] VALUE [100]
```

**Comment by jacekpaszkowski** [comment]
same for me and the bulb remain in this state, olny way to fix is to restart HA
