### ISSUE TITLE
Device unavailable after Hass restart

### ISSUE THREAD

**Issue by tungmeister** [rospogrigio/localtuya#507]
I have a WL-Box1 configured however it always becomes unavailable after a restart of hass - reloading the integration makes it return again. Running 3.2.2 on hass 2021.6.4. I've tried using the localtuya.reload service but can't make it work - does it require any variables?

**Comment by jello1974** [comment]
Same here

**Comment by ldsmovil** [comment]
the same with a tuya plug

**Comment by auspic7** [comment]
same on smart home switch

**Comment by auspic7** [comment]
My error stack track trace is as follows:
```
2021-06-16 22:23:42 ERROR (MainThread) [custom_components.localtuya.common] [044...b4e] Connect to 192.168.0.17 failed
Traceback (most recent call last):
File "/config/custom_components/localtuya/common.py", line 149, in _make_connection
status = await self._interface.status()
File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
status = await self.exchange(STATUS)
File "/config/custom_components/localtuya/pytuya/__init__.py", line 451, in exchange
msg = await self.dispatcher.wait_for(seqno)
File "/config/custom_components/localtuya/pytuya/__init__.py", line 240, in wait_for
await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```
It seems kinda weird since it operates normally when I reload integration.

**Comment by DavyRoswinkel** [comment]
Have the same problem and error with a cover and with all my Tuya plugs.
Went back to cloud based integration for now, as this is an unworkable situation.

**Comment by tungmeister** [comment]
anyone found a solution for this - it's getting really annoying!
