### ISSUE TITLE
Failed to authenticate with device. Verify that device id and local key are correct

### ISSUE THREAD

**Issue by MrPsi** [rospogrigio/localtuya#514]
I cannot add my device. A Deltaco SH-OP01. I get the following log error:

2021-06-28 21:26:21 ERROR (MainThread) [custom_components.localtuya.pytuya] [bf0...sip] Failed to get status: 'utf-8' codec can't decode byte 0xd6 in position 1: invalid continuation byte
Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 457, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 557, in _decode_payload
    payload = payload.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 1: invalid continuation byte

The id starts with "bf0ed" and ends with "bbdsip". I got two other devices of the same brand and model that works. Those ids only contain hex characters though. The new device id seems to contain other characters. Any ideas how to add the new device?

**Comment by marchett0** [comment]
I have the same situation. I'm trying to add a lamp and the error is the same the ID is something like "eb7fxxxxxxxxxxxxxxxwjco"

**Comment by fizcris** [comment]
Similar situation with error:
```
Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 457, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 559, in _decode_payload
    return json.loads(payload)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by shtrom** [comment]
Sounds similar to #424.
