### ISSUE TITLE
Error Door Sensor

### ISSUE THREAD

**Issue by frantt** [rospogrigio/localtuya#525]
## The problem

 I have this error.
Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:637
Integration: LocalTuya integration (documentation, issues)
First occurred: 17 de julio de 2021 20:55:59 (27 occurrences)
Last logged: 13:57:37

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 279, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 185, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.183', 6668)

  Describe the issue you are experiencing here to communicate to the
  maintainers. Tell us what you were trying to do and what happened.
-->

## Environment

- Localtuya version: v3.2.2
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version: 2021.7.2 
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1.
2. 
3.

## Configuration `configuration.yaml` or `config_flow`

```yaml

```

## Provide Home Assistant taceback/logs

```txt

```
## Additional information
This is device details

{
  "result": {
    "active_time": 1625500614,
    "biz_type": 18,
    "category": "mcs",
    "create_time": 1625500614,
    "icon": "smart/icon/ay15427647462366edzT/042f961da388104417809668b6c83e2b.jpg",
    "id": "8288255198f4xxxxxxxx",
    "ip": "79.xxx.11.xxx",
    "lat": "37.7898402",
    "local_key": "xxxxxxxx",
    "lon": "-3.788033",
    "name": "xxxxxxx",
    "online": true,
    "owner_id": "xxxxx",
    "product_id": "3slpirlnlqp0bqo1",
    "product_name": "Contact Sensor",
    "status": [
      {
        "code": "doorcontact_state",
        "value": true
      },
      {
        "code": "battery_state",
        "value": "high"
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "eu1543958498271fCAay",
    "update_time": 1626609200,
    "uuid": "8288255198f4xxxxxxxx"
  },
  "success": true,
  "t": 1626609312504
}

**Comment by fuatakgun** [comment]
- what is your problem? What is expected here? 
- As far as i can te that you are trying to add a battery powered door sensor which is not supported by localtuya.
- current implementation supports only devices which are awake all the time and motion sensors/door sensors sleep when there is no action and wakes up for couple of seconds to send a message to tuya servers.

**Comment by PrzemekSkw** [comment]
Hello, @fuatakgun I have similar error with Temperature & Humidity sensors. I have them in iot.tuya.platform in devices tab. Home Assistant see them when I add integration but after I put ID and key and click accept I see error. Log shows me same error:
```
Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:637
Integration: LocalTuya integration (documentation, issues)
First occurred: 17:07:00 (5 occurrences)
Last logged: 17:09:06

Unexpected exception
Traceback (most recent call last):
  File "/mnt/dietpi_userdata/homeassistant/custom_components/localtuya/config_flow.py", line 279, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/localtuya/config_flow.py", line 185, in validate_input
    interface = await pytuya.connect(
  File "/mnt/dietpi_userdata/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/home/homeassistant/.pyenv/versions/3.8.11/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/home/homeassistant/.pyenv/versions/3.8.11/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/home/homeassistant/.pyenv/versions/3.8.11/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/home/homeassistant/.pyenv/versions/3.8.11/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/home/homeassistant/.pyenv/versions/3.8.11/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.29', 6668)
```
That means that sensors also will not work?
Regars,
Przemek
