### ISSUE TITLE
I have broken my integration - Connect call failed

### ISSUE THREAD

**Issue by roscoegray** [rospogrigio/localtuya#528]
## The problem

After playing with one of my devices to try and set it up, I have now ended up in a loop of connect call failed errors. I have reinstalled the packaged and tried reboots. I can no longer add any device using the config flow ui and via yaml the device remains unavailable.

unsure how to reproduce it, looking for some advice on what to try next to get out of this loop. I was working before so much be something I have done that I can clear? 

> 2021-07-26 22:32:09 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.1.125', 'gwId': '************************', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': '************************', 'version': '3.3'}
2021-07-26 22:32:09 DEBUG (MainThread) [custom_components.localtuya] Device ************************ found with IP 192.168.1.125
2021-07-26 22:32:09 DEBUG (MainThread) [custom_components.localtuya.common] [bfb...tfk] Connecting to 192.168.1.125
2021-07-26 22:32:12 ERROR (MainThread) [custom_components.localtuya.common] [bfb...tfk] Connect to 192.168.1.125 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 139, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.125', 6668)

## Environment

- Localtuya version: V3.2.2
- Home Assistant Core version: core-2021.7.4, supervisor-2021.06.8
- [x] Are you using the Home Assistant Tuya Cloud component ?
- [x] Are you using the Tuya App in parallel ?

**Comment by roscoegray** [comment]
So looks like it was my router! After a reboot, it connected, only realised as had another connection issue with a camera.
