### ISSUE TITLE
DPs dump error

### ISSUE THREAD

**Issue by Francisk0** [rospogrigio/localtuya#545]
Hi,
I try to connect my new lamp with Fan Mantra https://www.mantrailuminacion.com/
I have problems because I don´t know how  to configure.
The ID 1 is the fan, but I can control the Speed
The light no is ID 20 and don´t know how to setup.
I try to execute a test.py of a tuyadebug in my mac but ever have same error:
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    import localtuya
  File "/Users/fran/Downloads/tuyadebug/localtuya/__init__.py", line 44, in <module>
    from . import pytuya
  File "/Users/fran/Downloads/tuyadebug/localtuya/pytuya/__init__.py", line 314
    raise Exception(f"Unexpected payload={payload}")
                                                  ^
SyntaxError: invalid syntax

I need an additional step before?

 Regards
Franzisc0

**Comment by Francisk0** [comment]
Solved this problem, I install a virtual ubuntu and  get the info.
Now I need read more for can understand.
    DPS [1] VALUE [True] 
    DPS [3] VALUE [1] 
    DPS [6] VALUE [0] 
    DPS [7] VALUE [0] 
    DPS [9] VALUE [True] 
    DPS [10] VALUE [789] 
    DPS [11] VALUE [1000] 
    DPS [101] VALUE [False]
