### ISSUE TITLE
At the same time, the devices may work correctly, or they may remain in an unmanaged state. Restarting the device integration does not help.

### ISSUE THREAD

**Issue by VikeDragon** [rospogrigio/localtuya#560]
## The problem

After restarting the Home assistant, I see errors in the log. At the same time, the devices may work correctly, or they may remain in an unmanaged state. Restarting the device integration does not help. Sometimes, after some time, an unmanaged device can be controlled : it starts working correctly.

Log : 
Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:637
Integration: LocalTuya integration (documentation, issues)
First occurred: 09:56:25 (8 occurrences)
Last logged: 09:56:26

    [706...03d] Connect to 192.168.31.243 failed
    [002...cda] Connect to 192.168.31.108 failed
    [505...1d2] Connect to 192.168.31.176 failed
    [237...d12] Connect to 192.168.31.162 failed
    [312...51b] Connect to 192.168.31.58 failed

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 139, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionResetError: [Errno 104] Connect call failed ('192.168.31.229', 6668)

## Environment

- Localtuya version: lasted 3.2.2
- Last working localtuya version (if known and relevant): I've been using it for a couple of months
- Home Assistant Core version: I observe this from 2021.9.0 - 2021.9.6, now the last one 2021.9.6
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [x] Are you using the Tuya App in parallel ? Smart Life, devices from which they are sent to Localtuya (I do not use it when working in the Home Assistant, I unload it from the smartphone's memory so as not to interfere with LocalTuya connections)

## Steps to reproduce

1. Restart Home Assistant
2. Goto Log
3. Got errors

## Configuration `configuration.yaml` or `config_flow`

```configuration.yaml 
        localtuya: !include includes/localtuya.yaml
 
  localtuya.yaml :
--->
      - host: 192.168.31.244
  device_id: bf4aead87a4578f2d6jgrv
  local_key: b23ca15c898b75bf
  friendly_name: Двойная розетка
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Малина
      id: 1
    - platform: switch
      friendly_name: Вытяжка
      id: 2
    - platform: sensor
      friendly_name: Ток Двойная розетка
      id: 18
      scaling: 0
      device_class: current
      unit_of_measurement: "mA"
    - platform: sensor
      friendly_name: Мощность Двойная розетка
      id: 19
      scaling: 0.1
      device_class: power
      unit_of_measurement: "W"   
    - platform: sensor
      friendly_name: Напряжение Двойная розетка
      id: 20
      scaling: 0.1
      device_class: voltage
      unit_of_measurement: "V"
    - platform: sensor
      friendly_name: Потребление Двойная розетка
      id: 22
      scaling: 0.1
      device_class: energy
      unit_of_measurement: "kWh"

- host: 192.168.31.243
  device_id: 70620251d8bfc0c6203d
  local_key: 55e3d0861a51aef4
  friendly_name: Тройник в туалете
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Питание биде
      id: 1
    - platform: switch
      friendly_name: Питание вентиляции
      id: 2
    - platform: switch
      friendly_name: Фен
      id: 3  
    - platform: switch
      friendly_name: Зарядка в туалете
      id: 7

- host: 192.168.31.176
  device_id: 5050346770039fcc91d2
  local_key: 511c5231bb7ec3cd
  friendly_name: Удлинитель в спальне
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Светильник в спальне
      id: 1
    - platform: switch
      friendly_name: Подзарядка в спальне
      id: 2
    - platform: switch
      friendly_name: Сокет в спальне
      id: 3
    - platform: switch
      friendly_name: Розетка в спальне
      id: 4 
    - platform: switch
      friendly_name: Зарядка в спальне
      id: 5 

- host: 192.168.31.252
  device_id: 6037521140f520f691c9
  local_key: 59ddcbea4aac6814
  friendly_name: Удлинитель в спальне 2
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Светильник в спальне 2
      id: 1
    - platform: switch
      friendly_name: Коверлок
      id: 2
    - platform: switch
      friendly_name: Швейная машинка
      id: 3
    - platform: switch
      friendly_name: Розетка в спальне 2
      id: 4
    - platform: switch
      friendly_name: Зарядка в спальне 2
      id: 5  

- host: 192.168.31.135
  device_id: 50134218c4dd571b3950
  local_key: a848c19bea1ebb29
  friendly_name: Удлинитель в детской
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Светильник
      id: 1
    - platform: switch
      friendly_name: Питание компьютера
      id: 2
    - platform: switch
      friendly_name: АВС в детской
      id: 3
    - platform: switch
      friendly_name: Зарядник
      id: 4
    - platform: switch
      friendly_name: Удлинитель в детской
      id: 38  
    - platform: switch
      friendly_name: Зарядка в детской
      id: 7  

- host: 192.168.31.108
  device_id: 00230822c82b96e0ecda
  local_key: 5699795832daa33c
  friendly_name: Удлинитель в студии
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Миксер
      id: 1
    - platform: switch
      friendly_name: Мультиварка
      id: 2
    - platform: switch
      friendly_name: Микроволновка
      id: 3
    - platform: switch
      friendly_name: Чайник
      id: 4
    - platform: switch
      friendly_name: Удлинитель в студии
      id: 38  
    - platform: switch
      friendly_name: Зарядка
      id: 7  
        
- host: 192.168.31.58
  device_id: 31215187c4dd5733651b
  local_key: 990a952c358613fb
  friendly_name: Двойная Блицвольф
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Подзарядка
      id: 1
    - platform: switch
      friendly_name: Комбайн
      id: 2
    - platform: sensor
      friendly_name: Ток Двойная Блицвольф
      id: 18
      scaling: 1
      device_class: current
      unit_of_measurement: "mA"
    - platform: sensor
      friendly_name: Мощность Двойная Блицвольф
      id: 19
      scaling: 0.1
      device_class: power
      unit_of_measurement: "W"   
    - platform: sensor
      friendly_name: Напряжение Двойная Блицвольф
      id: 20
      scaling: 0.1
      device_class: voltage
      unit_of_measurement: "V"
    - platform: sensor
      friendly_name: Потребление Двойная Блицвольф
      id: 22
      scaling: 0.001
      device_class: energy
      unit_of_measurement: "kWh"  

- host: 192.168.31.188
  device_id: bf6a9d7871db676a2esjnc
  local_key: bd020a30ce169163
  friendly_name: Питание камеры E1
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Питание камеры E1
      id: 1
    - platform: sensor
      friendly_name: Обратный отсчет E1 
      id: 9
    - platform: sensor
      friendly_name: Последнее состояние E1 
      id: 38
    - platform: binary_sensor
      friendly_name: Блокировка E1
      id: 40
      device_class: safety
      state_on: "false"
      state_off: "true"
 
- host: 192.168.31.174
  device_id: bfc6e1ab8c8dc2ef403dto
  local_key: 04513fffe51dcd5e
  friendly_name: Питание камеры E2
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Питание камеры E2
      id: 1
    - platform: sensor
      friendly_name: Обратный отсчет E2
      id: 9
    - platform: sensor
      friendly_name: Последнее состояние E2
      id: 38
    - platform: binary_sensor
      friendly_name: Блокировка E2
      id: 40
      device_class: safety
      state_on: "false"
      state_off: "true"

- host: 192.168.31.157
  device_id: bffd0336da97aaa4182lui
  local_key: cdc712454decae3c
  friendly_name: Вентилятор приставки
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Вентилятор приставки
      id: 1
    - platform: sensor
      friendly_name: Обратный отсчет вентилятор приставки
      id: 9
    - platform: sensor
      friendly_name: Последнее состояние вентилятор приставки
      id: 38
    - platform: binary_sensor
      friendly_name: Блокировка вентилятор приставки
      id: 40
      device_class: safety
      state_on: "false"
      state_off: "true"
      
- host: 192.168.31.78
  device_id: bfaf6aae165ea2cb62f0ew
  local_key: a8badbf6660416dd
  friendly_name: Вентилятор малины
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Вентилятор малины
      id: 1
    - platform: sensor
      friendly_name: Обратный отсчет вентилятор малины
      id: 9
    - platform: sensor
      friendly_name: Последнее состояние вентилятор малины
      id: 38
    - platform: binary_sensor
      friendly_name: Блокировка вентилятор малины
      id: 40
      device_class: safety
      state_on: "false"
      state_off: "true"      
      
- host: 192.168.31.186
  device_id: bfef1e2f1968ca22513yqa
  local_key: 02848709b3166538
  friendly_name: Розетка с двойной зарядкой
  protocol_version: "3.3"
  entities:
    - platform: switch
      friendly_name: Пылесос
      id: 1
    - platform: switch
      friendly_name: Двойная зарядка
      id: 7
    - platform: sensor
      friendly_name: Ток Розетка с двойной зарядкой
      id: 18
      scaling: 1
      device_class: current
      unit_of_measurement: "mA"
    - platform: sensor
      friendly_name: Мощность Розетка с двойной зарядкой
      id: 19
      scaling: 0.1
      device_class: power
      unit_of_measurement: "W"  
    - platform: sensor
      friendly_name: Напряжение Розетка с двойной зарядкой
      id: 20
      scaling: 0.1
      device_class: voltage
      unit_of_measurement: "V"
    - platform: sensor
      friendly_name: Потребление Розетка с двойной зарядкой
      id: 22
      scaling: 0.0001
      device_class: energy
      unit_of_measurement: "kWh"
    - platform: binary_sensor
      friendly_name: Блокировка Розетка с двойной зарядкой
      id: 40
      device_class: safety
      state_on: "true"
      state_off: "false"
      
- host: 192.168.31.229
  device_id: 23760081e8db84b7bfbf
  local_key: 69fe55299bc9985c
  friendly_name: Детектор в ванной
  protocol_version: "3.3"
  entities:
    - platform: sensor
      friendly_name: Углекислый газ
      id: 22
      device_class: carbon_dioxide
      unit_of_measurement: "ppm"
    - platform: sensor
      friendly_name: ЛОС
      id: 21
      scaling: 0.1
      device_class: volatile_organic_compounds
      unit_of_measurement: "ppm"
    - platform: sensor
      friendly_name: Влажность
      id: 19
      scaling: 0.1
      device_class: humidity
    - platform: sensor
      friendly_name: Температура
      id: 18
      scaling: 0.1
      device_class: temperature
    - platform: sensor
      friendly_name: Формальдегид
      id: 2
      scaling: 0.01
      device_class: volatile_organic_compounds
      
- host: 192.168.31.162
  device_id: 237600813c6105ec9d12
  local_key: 3a430061aa486df2
  friendly_name: Детектор в туалете
  protocol_version: "3.3"
  entities:
    - platform: sensor
      friendly_name: Углекислый газ
      id: 22
      device_class: carbon_dioxide
      unit_of_measurement: "ppm"
    - platform: sensor
      friendly_name: ЛОС
      id: 21
      scaling: 0.1
      device_class: volatile_organic_compounds
      unit_of_measurement: "ppm"
    - platform: sensor
      friendly_name: Влажность
      id: 19
      scaling: 0.1
      device_class: humidity
    - platform: sensor
      friendly_name: Температура
      id: 18
      scaling: 0.1
      device_class: temperature
    - platform: sensor
      friendly_name: Формальдегид
      id: 2
      scaling: 0.01
      device_class: volatile_organic_compounds    
<---

 


```

## DP dump

The problem occurs with different my devices

## Provide Home Assistant taceback/logs

```txt

```

**Comment by mlazzarotto** [comment]
I'm having the same issue on Local Tuya version 3.2.2 with a Novostella smart light bulb.
**Error**:
```
Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:637
Integration: LocalTuya integration (documentation, issues)
First occurred: 15:47:09 (1 occurrences)
Last logged: 15:47:09

[770...ce7] Connect to 192.168.1.73 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 139, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionResetError: [Errno 104] Connect call failed ('192.168.1.73', 6668)
```

**configuration.yaml**:
```
localtuya:
  - host: 192.168.1.73
    device_id: <REDACTED>
    local_key: <REDACTED>
    friendly_name: Tuya Device
    protocol_version: "3.3"
    entities:
      - platform: light
        friendly_name: Luce
        id: 1
```

**Comment by smarthousetips** [comment]
Same issue here

**Comment by Legromorph** [comment]
Same issue here with all of my Smartlife Smart wallplugs. :(
