### ISSUE TITLE
Toya products are shown as unavailable

### ISSUE THREAD

**Issue by tomerbirann** [rospogrigio/localtuya#563]
Toya products are shown as unavailable, Although in Toya's app they are connected and responding.
I use local tuya integration, and I have 26 toya devices at home and about 25 more devices.
I have a Xiaomi AX1800 system and the internet speed is good.
Usually a server reset returns the missing product, sometimes requiring more than one reset.

I would be happy to pass on logs or anything else you request to resolve the issue

Thanks in advance
Tomer Biran

**Comment by Ralph101** [comment]
Run into the same issue. I've added 5 door sensors and when I open the door it will show up in HA as open and after closing the door it show up as closed. But after 1 second the sensor become unavailable. Also I had some trouble with adding those devices I need to open the door. if the door is open I was able to add the sensor. I this all the door sensor should have the same issue.

**Comment by Ralph101** [comment]
``2021-11-11 07:56:28 ERROR (MainThread) [custom_components.localtuya.common] [bf5...mlq] Connect to 192.168.0.104 failed
Traceback (most recent call last):
File "/config/custom_components/localtuya/common.py", line 139, in _make_connection
self._interface = await pytuya.connect(
File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
_, protocol = await loop.create_connection(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
return await fut
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.104', 6668)``

**Comment by gofhk** [comment]
I got the same issue, it will become unavailable for sometimes
![IMG_20211208_141110](https://user-images.githubusercontent.com/61342314/145157676-2db41621-9fec-4418-bd44-3e69f5dfb1b6.jpg)

**Comment by Reinqusito** [comment]
HI,
same behavior, disconnections only in HA Local Tuya (never disconnected from wifi)
![LocalTuya-disconn](https://user-images.githubusercontent.com/82607551/160614712-66101eea-aa17-4dbe-9529-b5f61a5e67aa.jpg)
