### ISSUE TITLE
Can't setup LocalTuya

### ISSUE THREAD

**Issue by colindawson** [rospogrigio/localtuya#570]
New install of local tuya.  I select the dropdown with to find the device ID, and nothing is listed, even though I have three Tuya devices.

Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:240
Integration: LocalTuya integration (documentation, issues)
First occurred: 10:22:34 (4 occurrences)
Last logged: 10:22:56

[582...872] Failed to get status:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 451, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 240, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

## Environment
- Localtuya version: 3.2.2
- Last working localtuya version (if known and relevant):  n/a
- Home Assistant Core version:  core-2021.7.2
- [] Are you using the Home Assistant Tuya Cloud component ? no
- [X] Are you using the Tuya App in parallel ? TuyaSmart at the moment, but I plan on stopping once HA is up and running.

## Steps to reproduce

1. Add localTuya in hacs
2. Restart Home Assistant
3. Add localTuya integration. 

## Configuration `configuration.yaml` or `config_flow`
I don't have a configuration, it's not installed yet.

```yaml

```

## Provide Home Assistant taceback/logs

```txt

```

**Comment by rick044** [comment]
Exact same issue as above.

**Comment by theoneandonlyzako** [comment]
I keep getting an error when trying to submit a new device... first time.

**Comment by essarn** [comment]
Same thing with my installation.

**Comment by cwquek** [comment]
I have the same issue.

**Comment by com-xuonghuynh** [comment]
Same issue

**Comment by atjshop** [comment]
I had lot of timeout last night too. And I tried again later they worked well no issue.

**Comment by lockyt** [comment]
Same issue - worked the first time I tried (before realising I need the local key) but now jit ust shows an empty list.  If I hit submit with it empty (and after hitting the three dots) it lets me try enter it manually, but then I get 'An unknown error occurred, see log for details'.  In the log I get `Failed to get status `and `unknown exception` errors.

**Comment by colindawson** [comment]
Further update from me.    I rebuilt my Home Assistant install from scratch, and have more Tuya devices.   (6 sockets, and 2 lights)
When setting up my LocalTuya. Note I do not have the Tuya or V2 integrations and as this is a new build they've never been installed.

What I have found is that some devices install and work just fine, (4 sockets and 1 light).  Whilst others do not, they get a "An unknown error occurred. See log for details." in the dialog.

When I check the logs there's two entries....

Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:240
Integration: LocalTuya integration (documentation, issues)
First occurred: 13:21:12 (1 occurrences)
Last logged: 13:21:12

[582...872] Failed to get status:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 451, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 240, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

And

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:240
Integration: LocalTuya integration (documentation, issues)
First occurred: 13:21:12 (1 occurrences)
Last logged: 13:21:12

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 279, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 192, in validate_input
    detected_dps = await interface.detect_available_dps()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 451, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 240, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

This will happen consistently for some devices, whilst others appear to work just fine.

**Comment by purplephoenix76** [comment]
i had one switch which i had added successfully. After a few days, it starts showing unavailable. I've tried reload, restart and ultimate delete the integration. When i try to add it again, i've encountered the same as the rest. Using local tuya 3.2.3. I had no issues using the smart life app to access the switch and turn it on.

Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:240
Integration: LocalTuya integration (documentation, issues)
First occurred: 17:49:25 (11 occurrences)
Last logged: 18:00:20

[bf0...kq4] Failed to get status:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 451, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 240, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by DaKar00** [comment]
I have figured out cause for this problem, you are probably getting the device ID from the smart life app at the same time you are finnishing the integration of the device, just get the device ID of you device then close the smart life app before finnishing the integration in local tuya and it work every time =D

**Comment by duncan485** [comment]
> I have figured out cause for this problem, you are probably getting the device ID from the smart life app at the same time you are finnishing the integration of the device, just get the device ID of you device then close the smart life app before finnishing the integration in local tuya and it work every time =D

@DaKar00  Thanks, closing the app (Tuya in my case) on my phone actually worked =).

**Comment by crpgbogor** [comment]
> I have figured out cause for this problem, you are probably getting the device ID from the smart life app at the same time you are finnishing the integration of the device, just get the device ID of you device then close the smart life app before finnishing the integration in local tuya and it work every time =D

This is a good solution, thank you! Been trying for a few weeks until now....

**Comment by evenywchen** [comment]
> I have figured out cause for this problem, you are probably getting the device ID from the smart life app at the same time you are finnishing the integration of the device, just get the device ID of you device then close the smart life app before finnishing the integration in local tuya and it work every time =D

@DaKar00 Thanks, closing the "[Tuya Smart](https://play.google.com/store/apps/details?id=com.tuya.smart)" actually worked, too.

**Comment by williamrosswhite** [comment]
> I was having the same issue. In my case, I've had a Tuya v2 integration configured previously. Then, I disabled it and now Local Tuya is working.

what is tuya v2?  where is it?  how do i disabele it?

**Comment by besiktas97** [comment]
> > I was having the same issue. In my case, I've had a Tuya v2 integration configured previously. Then, I disabled it and now Local Tuya is working.
> 
> 
> 
> what is tuya v2?  where is it?  how do i disabele it?

Tuya v2 is a integration and you can delete it. V2 is the cloud version of all your tuya devices.

**Comment by williamrosswhite** [comment]
> > > I was having the same issue. In my case, I've had a Tuya v2 integration configured previously. Then, I disabled it and now Local Tuya is working.
> > 
> > 
> > what is tuya v2?  where is it?  how do i disabele it?
> 
> Tuya v2 is a integration and you can delete it. V2 is the cloud version of all your tuya devices.

Do you mean the existing cloud based tuya integration in home assistant?  I deleted that and tried again and got the same error.  It says check logs but where are the logs to check?

**Comment by webwolf3000** [comment]
This doesn't work; it's buggy as hell.

It was working great for 3 months, occasionally went offline but I just had to login to the app and send a command to the Blind motor to 'wake it up' then the tuya local button would work again. After hitting configure on the tuya local integration and changing one thing, it totally went offline (unavailable) - I've set it up 20 times and even restored a 3 month old HASS to a VM to test it and it's just unavailable.

Not sure what changed, but for some reason, this thing is totally not playing ball. It's very flaky and intermittent even when it's working so stability is an issue.

Can confirm if too many things are trying to connect to the Motor at the same time, it'll just balk and go offline. But I disabled and closed everything related to the motor and it just sat there, occasionally waking up just to go back to unavailable for no obvious reason. Actually think Tuya is the issue here, maybe flashing the device would be a better option...

**Comment by webwolf3000** [comment]
> Have you tried the new "get devices from cloud" function in the new localtuya app? 

I have not. I logged into the cloud in the local tuya app (did and didn't, reset the device deleted in the cloud and reconfigured etc).

Is there a new option other than logging into the cloud through the local tuya app?

**Comment by NothingSethual** [comment]
> I have figured out cause for this problem, you are probably getting the device ID from the smart life app at the same time you are finnishing the integration of the device, just get the device ID of you device then close the smart life app before finnishing the integration in local tuya and it work every time =D

Bless you
