### ISSUE TITLE
Since updating HA to V2021.10.4 local tuya is failing 

### ISSUE THREAD

**Issue by manjulapra** [rospogrigio/localtuya#588]
Since updating HA to V 2021.10.4 local tuya is not connecting. Here is the output from the log:

`Logger: homeassistant.config_entries
Source: components/tuya/__init__.py:71
First occurred: 8:22:35 PM (1 occurrences)
Last logged: 8:22:35 PM

Error setting up entry xxxxxxxxxx for tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 59, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 71, in _init_tuya_sdk
    auth_type = AuthType(entry.data[CONF_AUTH_TYPE])
KeyError: 'auth_type'
`

**Comment by manjulapra** [comment]
This issue is not related to local tuya and was added here by a mistake. Sincere apologies.
