### ISSUE TITLE
After a reboot HA, the multisocket switches are in a zombie state (not available)

### ISSUE THREAD

**Issue by VikeDragon** [rospogrigio/localtuya#600]
## The problem
After a reboot HA, the multisocket switches are in a zombie state (not available)

## Environment

- Localtuya version: v 3.2.3
- Last working localtuya version v 3.2.3: 
- Home Assistant Core version: 2021.10.6
- [] Are you using the Home Assistant Tuya Cloud component ?
- [x] Are you using the Tuya App in parallel ? SmartLife App to LocalTuya

## Steps to reproduce
Reboot HA

## Provide Home Assistant taceback/logs

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:240
Integration: LocalTuya integration (documentation, issues)
First occurred: 17:27:58 (158 occurrences)
Last logged: 18:47:59

[002...cda] Connect to x.x.x.108 failed
[706...03d] Connect to x.x.x.243 failed
[501...950] Connect to x.x.x.135 failed
[603...1c9] Connect to x.x.x.252 failed
[505...1d2] Connect to x.x.x.176 failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 149, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 451, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 240, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by lukmasipraba** [comment]
Same problem. Device SH-OP01 and tuya outdoor smart plug
