### ISSUE TITLE
Ledvance Smartplug throws unexcepted error

### ISSUE THREAD

**Issue by ChuckNorris9939** [rospogrigio/localtuya#629]
## The problem

I buyed this Smart Plug: https://templates.blakadder.com/ledvance_4058075522800.html and cant integrate it with local tuya.
I already got some ceiling lights that are working flawlesly with local tuya. (another Brand)
I used this Instruction to get my localkeys: https://community.home-assistant.io/t/ledvance-wifi-bulbs/301478/13 (I Used my Android phone Instead) for 2 plugs. 
The devices show up in the HA - localtuya Integration gui:
![image](https://user-images.githubusercontent.com/8191872/142440018-bc8d3e40-7312-40b2-b1bc-7665c63ef5ad.png)
But i get this Error when i click on the send button:
![image](https://user-images.githubusercontent.com/8191872/142442660-0c446b1d-fbce-4926-857d-c329be96cad0.png)

I used both protocol versions and double checked my input. Every Think seems fine so i dont know what is the problem.
Same Error on the second device.

## Environment

- Localtuya version:  1.17.2
- Last working localtuya version (if known and relevant): 1.17.2
- Home Assistant Core version:  core-2021.11.4
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Add New Devices over HA, select auto discovered device id.
2. Enter Local Key and click the send button.
2. Error occures on screen and in the HA log

## Configuration `configuration.yaml` or `config_flow`

```yaml

```

## Provide Home Assistant taceback/logs

```txt
2021-11-18 16:10:04 DEBUG (MainThread) [custom_components.localtuya.pytuya] [755...41b] Heartbeat failed due to timeout, disconnecting
2021-11-18 16:10:04 ERROR (MainThread) [custom_components.localtuya.pytuya] [755...41b] Failed to get status: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 451, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 240, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2021-11-18 16:10:04 DEBUG (MainThread) [custom_components.localtuya.pytuya] [755...41b] Closing connection
2021-11-18 16:10:04 ERROR (MainThread) [custom_components.localtuya.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 279, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 192, in validate_input
    detected_dps = await interface.detect_available_dps()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 451, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 240, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by BlackFireAlex** [comment]
Use the yaml, it only works with the config file for me

**Comment by ChuckNorris9939** [comment]
That worked. Thank you

**Comment by BlackFireAlex** [comment]
Also be sure to only add the switch not the sensors and all if you want to be able to see the power in attributes

**Comment by ChuckNorris9939** [comment]
I removed sensor and binary Sensor but i still cant see the power attributes
This is my config:
`  - host: 192.168.178.87
    device_id: --------------
    local_key: -------
    friendly_name: Plug WZ1
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: Plug WZ1
        id: 1
        current: 18 # Optional
        current_consumption: 19 # Optional
        voltage: 20 # Optional`

Wich power attributes do you even mean?
I already had Voltage but is it possible to show Ampeer too?. Without a binary sensor for mA?
How should the config look like?
