### ISSUE TITLE
Devices Unavailable

### ISSUE THREAD

**Issue by panthers16** [rospogrigio/localtuya#640]
I just moved house and had to setup all of my Tuya devices again on the new network, however only a few actually stay connected or connect at all. They all worked at the old house and I have replaced the local key with the new one. I have also tried removing all of the devices and the integration and starting over and still no luck. The most common error I'm receiving is:

This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:637
Integration: LocalTuya integration (documentation, issues)
First occurred: 18:47:25 (316 occurrences)
Last logged: 18:55:44

[660...f77] Connect to 10.0.0.92 failed
[660...954] Connect to 10.0.0.20 failed
[ebf...aov] Connect to 10.0.0.190 failed
[505...e30] Connect to 10.0.0.192 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 139, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('10.0.0.92', 6668)

**Comment by smithbill17** [comment]
Why did you close this issue? Have you found a 'fix'?

This appears to be the same issue as issue #624 and issue #631 which are not resolved as far as I understand.

This fault seems to be plaguing a lot of people using LocalTuya, which is extremely unfortunate as the only alternative, being the officially Tuya supported integration, is so bad & unreliable.
