### ISSUE TITLE
Migrate to new Home Assistant localTuya errors please help as i love this localTuya 

### ISSUE THREAD

**Issue by vjmaz** [rospogrigio/localtuya#669]
Hi Team 
   Can someone please let me know can i add my localTuya devices to 2 Home Assistant servers  please ... 
   I am trying to migrate from my thin client HA ( HAOS ) to my New more powerful laptop running very current HA ( HAOS ) .
The new laptop setup is due to Frigate needing more memory and CPU as I am running Coral USB and only 4 IP Security cams .
It now has a lot more grunt to run Frigate & all my automations too... I don't want to use a backup to migrate as i have got rid of many Zigbee devices and my last setup I used a lot for testing !!! ... So i rather a new fresh Install as i am only keeping my good solid wifi devices and also Broadlink pro RM devices ... 
Anyway as many of my lights & Switches are TUYA based and they all work really well with LocalTuya i was hoping i can some how migrate it ... 

I tried adding IP and local key & device ID but keep getting an error on the new setup !  
can someone who knows python please give me some guidance please .. 

1. do I need to remove the devices from the old Home Assistant Server 
2. or can I copy a file maybe from the old Home assistant server 

Please team I don't know what direction as I have a lot of automation tired in with many of these devices Thanx ( PS I don't mind creating new automations also just was hoping to migrate my LocalTuya devices would be awesome as i have many 8 gang switches & heaps of 4 gang switches ..

& yes they all work really well in my old Home Assistant .

here is the log error if it helps 

Logger: homeassistant
Source: components/shelly/__init__.py:327
First occurred: 5:41:39 PM (82 occurrences)
Last logged: 6:01:58 PM

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1029, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.9/site-packages/aioshelly/coap.py", line 124, in datagram_received
    self.subscriptions[msg.ip](msg)
  File "/usr/local/lib/python3.9/site-packages/aioshelly/block_device.py", line 144, in _coap_message_received
    self._update_s(msg.payload)
  File "/usr/local/lib/python3.9/site-packages/aioshelly/block_device.py", line 190, in _update_s
    self._update_listener(self)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_set_updated_data
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/shelly/__init__.py", line 327, in _async_device_updates_handler
    cfg_changed = block.cfgChanged
  File "/usr/local/lib/python3.9/site-packages/aioshelly/block_device.py", line 417, in __getattr__
    raise AttributeError(f"{self.type} block has no attribute '{attr}'")
AttributeError: device block has no attribute 'cfgChanged'

Thanx team 
Regards Maz

**Comment by vjmaz** [comment]
some of the earlier errors to 

This error originated from a custom integration.
Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:559
Integration: LocalTuya (documentation, issues)
First occurred: 5:58:05 PM (3 occurrences)
Last logged: 5:59:36 PM

[bfb...yht] Failed to get status: Expecting value: line 1 column 1 (char 0)
[bff...aea] Failed to get status: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 510, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 457, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 559, in _decode_payload
    return json.loads(payload)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by vjmaz** [comment]
I'm closing this Team .   I discovered jut remove from the old HA server and add it to the new one Thanx ... was hoping to migrate by file so I didn't have to struggle setting it all up in new environment but I'm glad i can still add to new one
