### ISSUE TITLE
Where does Local Tuya store configuration for devices setup through config flow?

### ISSUE THREAD

**Issue by mkaatman** [rospogrigio/localtuya#680]
## The problem
I'm having difficulty deleting or reconfiguring a tuya bulb. I'd like to manually configure the entry but I am not sure where the configuration is stored. I have several other identical bulbs that I added without configuring and they work but they are only on/off, no brightness of RGB. I'm trying to add those functions now.

## Environment
- Localtuya version: 3.2.4
- Last working localtuya version (if known and relevant): N/A
- Home Assistant Core version: 2021.12.x
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce
1. Here is my bulb information from iot.tuya.com: https://paste.debian.net/1224990/
2. I tried to configure it with local tuya but I must have it in an invalid state.
3. A lot of errors like this:
```
Exception in _update_handler when dispatching 'localtuya_eb0f3f8f6358e5982awkdk': ({'20': True, '26': 0, '23': 4, '21': 'colour'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 258, in _update_handler self.status_updated() File "/config/custom_components/localtuya/light.py", line 392, in status_updated if self.__is_color_rgb_encoded(): File "/config/custom_components/localtuya/light.py", line 272, in __is_color_rgb_encoded return len(self.dps_conf(CONF_COLOR)) > 12 TypeError: object of type 'int' has no len()
Exception in _update_handler when dispatching 'localtuya_eb0f3f8f6358e5982awkdk': ({'20': True},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 258, in _update_handler self.status_updated() File "/config/custom_components/localtuya/light.py", line 392, in status_updated if self.__is_color_rgb_encoded(): File "/config/custom_components/localtuya/light.py", line 272, in __is_color_rgb_encoded return len(self.dps_conf(CONF_COLOR)) > 12 TypeError: object of type 'bool' has no len()
```

## Configuration `configuration.yaml` or `config_flow`
`config flow`

## DP dump
DP Dump fails
```
INFO:localtuya:localtuya version 1.0.0
INFO:localtuya:Python 3.9.7 (default, Sep  9 2021, 11:03:41)
[GCC 10.3.1 20210424] on linux
INFO:localtuya:Using pytuya version '8.1.0'
INFO:localtuya:Detecting list of available DPS of device eb0f3f8f6358e5982awkdk [192.168.2.119], protocol 3.3.
DEBUG:localtuya.pytuya:Sending command status (device type: type_0a)
DEBUG:localtuya.pytuya:paylod=b'{"gwId":"eb0f3f8f6358e5982awkdk","devId":"eb0f3f8f6358e5982awkdk"}'
DEBUG:localtuya.pytuya:DATA RECEIVED!
DEBUG:localtuya.pytuya:decode payload=b'0W\x98\xd5\xd8b )O8r6\xdc\x81_L\x02\x0c\x0c\x9c\xa3\x9e\xden\xfd\xaa\xfa\xff\xbf0\xc6x'
DEBUG:localtuya.pytuya:'data unvalid' error detected: switching to dev_type 'type_0d'
DEBUG:localtuya.pytuya:Re-send status due to device type change (type_0a -> type_0d)
DEBUG:localtuya.pytuya:Sending command status (device type: type_0d)
DEBUG:localtuya.pytuya:paylod=b'{"devId":"eb0f3f8f6358e5982awkdk","uid":"eb0f3f8f6358e5982awkdk","t":"1640661518","dps":{"1":null,"2":null,"3":null,"4":null,"5":null,"6":null,"7":null,"8":null,"9":null,"10":null}}'
DEBUG:localtuya.pytuya:DATA RECEIVED!
DEBUG:localtuya.pytuya:READING AGAIN!
DEBUG:localtuya.pytuya:Failed to connect to 192.168.2.119. Raising Exception.
WARNING:localtuya.pytuya:Failed to get status: timed out
```

## Provide Home Assistant taceback/logs
```txt
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 9:23:41 PM (2 occurrences)
Last logged: 9:23:41 PM

Exception in _update_handler when dispatching 'localtuya_eb0f3f8f6358e5982awkdk': ({'20': False},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 258, in _update_handler self.status_updated() File "/config/custom_components/localtuya/light.py", line 392, in status_updated if self.__is_color_rgb_encoded(): File "/config/custom_components/localtuya/light.py", line 272, in __is_color_rgb_encoded return len(self.dps_conf(CONF_COLOR)) > 12 TypeError: object of type 'bool' has no len()
```
## Additional information
Wifi variant of this bulb: https://www.aliexpress.com/item/1005002760795498.html

Bulb that isn't working:
```
2021-12-27 21:23:40 DEBUG (MainThread) [custom_components.localtuya.light] [eb0...kdk] Adding light.tuya_bulb_2 with configuration: {'friendly_name': 'tuya bulb 2', 'brightness': 20, 'color_temp': 20, 'brightness_lower': 29, 'brightness_upper': 500, 'color_mode': 20, 'color': 20, 'color_temp_min_kelvin': 2700, 'color_temp_max_kelvin': 6500, 'music_mode': False, 'id': 20, 'platform': 'light'}
2021-12-27 21:23:40 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=light.tuya_bulb_2, old_state=None, new_state=<state light.tuya_bulb_2=unavailable; min_mireds=154, max_mireds=370, effect_list=[], supported_color_modes=['color_temp', 'hs'], friendly_name=tuya bulb 2, supported_features=23 @ 2021-12-27T21:23:40.019192-06:00>>
```

Bulb that's working:
```
2021-12-27 21:23:40 DEBUG (MainThread) [custom_components.localtuya.light] [eb8...qdl] Adding light.tuya_bulb_3 with configuration: {'id': 20, 'friendly_name': 'tuya bulb 3', 'brightness_lower': 29, 'brightness_upper': 1000, 'color_temp_min_kelvin': 2700, 'color_temp_max_kelvin': 6500, 'music_mode': False, 'platform': 'light'}
```

**Comment by mkaatman** [comment]
I may have found the answer to my question.

It looks like /config/.storage/core.config_entries has the device information and references /config/.storage/core.config_entries.

Carefully editing those values and restarting HA got me back to the point that the bulb was turning on/off. I'll now start trying to manage the DPs and see where I get.

**Comment by mkaatman** [comment]
I still can't seem to get these bulbs into color mode if anyone has any ideas.

**Comment by mkaatman** [comment]
If anyone stumbles upon this issue, here are the values I used for a generic RGB bulb.

ID: 20
Brightness: 22
Color Temp: 23
Color Mode: 21
Color: 24
Scene: 25

From: https://pypi.org/project/tinytuya/
