### ISSUE TITLE
My devices are not being recognized 

### ISSUE THREAD

**Issue by Liornat** [rospogrigio/localtuya#692]
## The problem
Hi,
I have installed the local tuya integration but I get an empty list and the integration doesn't detect any of my devices.
I have tried to add couple of my devices manually both using the configuration.yaml and using the GUI.
Using Yaml I "see" the devices but their status is always "Unknown".
Using the GUI leads to "An unknown error occurred. See log for details." 
Looking on the logs shows "imeoutError: [Errno 110] Connect call failed ..."
The official Tuya integration detects all my devices automatically.

## Environment

- Localtuya version:  
- Home Assistant Core version:  
- [X] Are you using the Home Assistant Tuya Cloud component ? 
- [X] Are you using the Tuya App in parallel ? 

## Steps to reproduce
1. Open iot account in tuya web
2. Open a project in the cloud
3. Add all the necessary authorizations 
4. Link smartlife app
5. Install hack
6. Download local tuya integration from hacks.
7. Install local tuya integration   

Yaml:
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

spotify:
  client_id: 
  client_secret: 

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem 
  
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shopping_list:
```

## Provide Home Assistant taceback/logs
```
2022-01-03 20:30:48 WARNING (SyncWorker_3) [homeassistant.components.sonos] Failed to connect to discovered player '192.168.68.136': HTTPConnectionPool(host='192.168.X.X', port=1400): Max retries exceeded with url: /xml/ZoneGroupTopology1.xml (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f95d8b0d0>, 'Connection to 192.168.X.X timed out. (connect timeout=10)'))
2022-01-03 20:31:14 ERROR (MainThread) [custom_components.localtuya.config_flow] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/localtuya/config_flow.py", line 283, in async_step_basic_info
self.dps_strings = await validate_input(self.hass, user_input)
File "/config/custom_components/localtuya/config_flow.py", line 189, in validate_input
interface = await pytuya.connect(
File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
_, protocol = await loop.create_connection(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
return await fut
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.X.**Z**', 6668)
2022-01-03 20:31:38 WARNING (SyncWorker_3) [homeassistant.components.sonos] Failed to connect to discovered player '192.168.68.136': HTTPConnectionPool(host='192.168.X.X', port=1400): Max retries exceeded with url: /xml/ZoneGroupTopology1.xml (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f95d8be50>, 'Connection to 192.168.68.136 timed out. (connect timeout=10)'))
```

**Comment by jeremysherriff** [comment]
The tuya devices can usually only support one network connection at a time. Make sure your smartlife app is closed and actively killed.

If you have access to a system that can run python, please attempt to get a DPs Dump following [these instructions](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump).  I suspect you will get `timeout` with the DPs Dump script as well, indicating that something else is connected to your tuya device and blocking new network connections.

**Comment by jeremysherriff** [comment]
PS the YAML config that you posted in the bug report does not include your localtuya configuration - you can edit your post and remove it if you don't want the world to see what else you have configured 👍

**Comment by Liornat** [comment]
@jeremysherriff , you were right, I got timeout.
C:\Users\liorn\Downloads\tuyadebug>py test.py 22230844e868e7828XXX 192.168.X.Z 2147e37c04d8eXXX
INFO:localtuya:localtuya version 1.0.0
INFO:localtuya:Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
INFO:localtuya:Using pytuya version '8.1.0'
INFO:localtuya:Detecting list of available DPS of device 22230844e868e78287f3 [192.168.68.102], protocol 3.3.
DEBUG:localtuya.pytuya:Sending command status (device type: type_0a)
DEBUG:localtuya.pytuya:paylod=b'{"gwId":"22230844e868e78287f3","devId":"22230844e868e78287f3"}'
WARNING:localtuya.pytuya:Failed to get status: timed out

I doubled check and my smartlife app is closed.
Maybe me tplink deco m5 holds the IPs ?
The internet setup that I have is as follow:
1. TP link router which acts only as bridge.
2. The router is connected via ethernet cable to one deco device which defines two different networks.
   1 (Home) which provides wifii in both 2.4 and 5Ghz 
   2 (Smart home)  which provides wifii  only in 2.4Ghz
   
Maybe something in this setup is not good/configured correctly ?
Also note that my home assistant is using static IP.
Tried to provide all the info I know :-)
Thanks for the help

**Comment by jeremysherriff** [comment]
Are the tuya devices set to have reserved addresses? I also use a Deco Mesh
(m9), no problems.

**Comment by Liornat** [comment]
No, they don't

בתאריך יום ג׳, 4 בינו׳ 2022, 00:38, מאת jeremysherriff ‏<
***@***.***>:

> Are the tuya devices set to have reserved addresses? I also use a Deco Mesh
> (m9), no problems.
>
>

**Comment by BuffBuffet** [comment]
Are you on a 5 Ghz connection? It worked when I changed to a 2.4 one.

**Comment by Liornat** [comment]
I Know that, all of my devices are connected to 2.4 Ghz.
The weird thing is how come the regular Tuya detect all of the decices and
the Local Tuya failed to find any of them.
Each attempt leads to time out.
If the I.P is blocked then by who?
I removed the Tuya integration, I closed the the smartlife app, I even
flashed a new hassio, nothing.
What else : -(


בתאריך יום ג׳, 4 בינו׳ 2022, 20:07, מאת BuffBuffet ‏<
***@***.***>:

**Comment by jeremysherriff** [comment]
The built-in Tuya integration uses the cloud-based data that the devices are sending to Tuya, not polling local data from the devices.

I do not see the expected device broadcasts in the logs you provided.  We should be seeing lines like this every few seconds:
```
[custom_components.localtuya.discovery] Discovered device: {'ip': '192.168.x.x', 'gwId': 'xxxxxxxxxxxxxxxxxxxxxx', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'kxxxxxxxxxxxxxxx', 'version': '3.3'}
```
Can you please capture the debug logs for longer, and provide more of the log?

It is most likely that the devices are being blocked locally because you have another system or app connecting to them.  The only other explanation I can think of is that Tuya has closed the local access on your devices, and I think this is very unlikely.

Is there another instance of the Tuya Smart or SmartLife apps installed anywhere? On another device perhaps?

**Comment by jeremysherriff** [comment]
Also check for the "OEM" manufacturer's app - often the devices are sold under a different brand, and a different app is provided with that branding on it. Those apps are also using the local tuya-specific network ports.
