### ISSUE TITLE
OSError: [Errno 113] Connect call failed - Combo-Smoke and Carbon Monoxide Alarm

### ISSUE THREAD

**Issue by Belcraig** [rospogrigio/localtuya#697]
## Environment

- Localtuya version: 3.3.0
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version: core-2021.11.5 
- [X] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce
 Integrations--> add integration --> localtuya integration --> select device from list _ or select manual addition_ --> enter details _local key from device details from IoT platform_
--> click submit

## Configuration `configuration.yaml` or `config_flow`

```yaml

```

## Provide Home Assistant taceback/logs

```txt

```

**Comment by dedepene** [comment]
I get the same error, only my devices are Ledvance lights with extracted local key. They work fine with the local tuya integration, this error starts appearing though when I take the device offline.

`2022-02-03 11:14:44 ERROR (MainThread) [custom_components.localtuya.common] [bf6...xry] Connect to 192.168.1.74 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 145, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.74', 6668)`

**Comment by Xitee1** [comment]
I also get that error. I have only one device set up with local tuya and I get this error every time when home assistant starts.
However the switch works normal. There is just this error in the logs.
