### ISSUE TITLE
Unplugged entities filling up logs with errors, how to disable?

### ISSUE THREAD

**Issue by binarydad** [rospogrigio/localtuya#701]
## The problem
I've unplugged 6 devices that were originally configured in configuration.yaml. I have also removed these 6 entries from that configuration file and have also disabled the entities in HA, but localtuya keeps scanning and saying it cannot connect to these same 6. The error is logged every 60 seconds, which is the scan interval. I didn't post the YAML since it's huge, and was working fine - the only change was commenting-out the 6 entries. I've also restarted HA a couple times, but the error keeps occurring. 

## Environment

- Localtuya version: 3.3.0
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version: Latest as of a couple days ago
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

The recurring log entries (every 60 seconds). I'm not sure why 5 are listed here, when 6 of these entries are logged in the raw log file:

```
Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya (documentation, issues)
First occurred: 10:22:24 AM (54 occurrences)
Last logged: 10:30:24 AM

    [444...29b] Connect to 192.168.1.188 failed
    [444...d4e] Connect to 192.168.1.184 failed
    [444...c00] Connect to 192.168.1.186 failed
    [eb6...9uc] Connect to 192.168.1.193 failed
    [444...2dc] Connect to 192.168.1.189 failed

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 145, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.187', 6668)
```

**Comment by binarydad** [comment]
Disregard. The issue was I only disabled the entities. Instead, I needed to disable the devices. Closing this issue.

**Comment by hiagocosta** [comment]
please, include a kind of toggle that deactivates these logs on home assistant, I have a lot of lights that is always off, and it consumes data just for logging
