### ISSUE TITLE
Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists.

### ISSUE THREAD

**Issue by Openwrtfunboy** [rospogrigio/localtuya#718]
I tried to add wifi door/window sensor, but can't because Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists.

**Comment by Openwrtfunboy** [comment]
i can give money to developer to buy this device from Aliexpress to make it work.

**Comment by hellad** [comment]
I've got the same error when tried to add Wired Moes ZigBee Gateway.
If I select Protocol Version 3.1 then the error message in HA log looks like :
		This error originated from a custom integration.
		
		Logger: custom_components.localtuya.config_flow
		Source: custom_components/localtuya/pytuya/__init__.py:583
		Integration: LocalTuya (documentation, issues)
		First occurred: 1:55:33 PM (1 occurrences)
		Last logged: 1:55:33 PM
		
		Unexpected exception
		Traceback (most recent call last):
		  File "/config/custom_components/localtuya/config_flow.py", line 283, in async_step_basic_info
		    self.dps_strings = await validate_input(self.hass, user_input)
		  File "/config/custom_components/localtuya/config_flow.py", line 196, in validate_input
		    detected_dps = await interface.detect_available_dps()
		  File "/config/custom_components/localtuya/pytuya/__init__.py", line 539, in detect_available_dps
		    data = await self.status()
		  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
		    status = await self.exchange(STATUS)
		  File "/config/custom_components/localtuya/pytuya/__init__.py", line 466, in exchange
		    payload = self._decode_payload(msg.payload)
		  File "/config/custom_components/localtuya/pytuya/__init__.py", line 583, in _decode_payload
		    raise Exception(f"Unexpected payload={payload}")
		Exception: Unexpected payload=b'*\xf9@z\x11\x88D\xf4^g\x8c\xd8[\\?\xa5&\xb2f\x16\n=2\x1dWZ\xacz}#\x86['

**Comment by neil2017** [comment]
![image](https://user-images.githubusercontent.com/23653387/163376785-9e9853ce-39cd-4ff5-bb49-148926261368.png)
也遇到这个问题了，楼主解决了吗？
