### ISSUE TITLE
Error while setting up localtuya platform for fan in new version

### ISSUE THREAD

**Issue by perezrojose** [rospogrigio/localtuya#724]
Error while setting up localtuya platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/localtuya/common.py", line 74, in async_setup_entry
    entity_class(
  File "/config/custom_components/localtuya/fan.py", line 74, in __init__
    self._ordered_list = self._config.get(CONF_FAN_ORDERED_LIST).split(",")
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by pplucky** [comment]
Same thing happened to me with [this](https://github.com/rospogrigio/localtuya/wiki/Known-working-and-non-working-devices#diffuser-as-fan-and-light), after I removed the integration and added it again, now it shows this error when add the integration:

`Exception in _update_handler when dispatching 'localtuya_417568858cce4edbdcf4': ({'1': False, '2': 'small', '3': 'cancel', '5': False, '6': 'colour', '8': '00000000000000'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 281, in _update_handler self.status_updated() File "/config/custom_components/localtuya/fan.py", line 235, in status_updated self._speed_range, int(current_speed) ValueError: invalid literal for int() with base 10: 'small'`

It seems the fan speed "values" are large or small (as per the device debugging), but HA is expecting to be an integer.

This is my fan entity configuration:
![image](https://user-images.githubusercontent.com/16407309/153214012-616c338f-cc68-460f-80cc-fa6fdd6a36c5.png)

Any ideas?

**Comment by dexsta** [comment]
> Same thing happened to me with this

I have setup that device within Home Assistant. I've used a combination of Config Flow and sending DP settings.
