### ISSUE TITLE
Cover with homekit doesn't work

### ISSUE THREAD

**Issue by thecampagnards** [rospogrigio/localtuya#733]
Hello,

## The problem

I have everything install on fresh env and I have the latest versions.
I have some trouble when I use it with HomeKit HAAS bridge the covers doesn't move and I have this error which spawn in the logs:

![image](https://user-images.githubusercontent.com/14922324/152650651-713471bf-c099-4a76-81e3-fd24bf94c381.png)

On the HA dashboard everything works well I manage to make them move.

I have this kind of cover wifi system:

![image](https://user-images.githubusercontent.com/14922324/152650701-2b0f8d06-7696-4582-90eb-439797fc367e.jpeg)

I configured then like that:

![image](https://user-images.githubusercontent.com/14922324/152650715-f01ee81d-34b1-4b49-9719-77fcb013d13a.png)

I don't know what to do to fix them. Where can I fix the conversation issue that I get ?

Thanks have a nice day !

**Comment by thecampagnards** [comment]
New update with the new release of HA (2022.3.0) I have another error (in addition to the previous) :

```log

Logger: homeassistant.util.logging
Source: util/logging.py:105 
First occurred: 22:07:17 (2 occurrences) 
Last logged: 22:07:42

Exception in _update_handler when dispatching 'localtuya_2736767470039f8d5294': ({'1': '3'},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 281, in _update_handler self.status_updated() File "/config/custom_components/localtuya/cover.py", line 217, in status_updated 100, max(0, self._current_cover_position + pos_diff) TypeError: can only concatenate str (not "int") to str

```

**Comment by notorioustubze** [comment]
I have the same issue blind can be controlled via HA fine but fail to do anything when exposed to HK.
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/localtuya/cover.py:126 
Integration: LocalTuya integration (documentation, issues) 
First occurred: 12:28:24 (1 occurrences) 
Last logged: 12:28:24

Error executing service: <ServiceCall cover.set_cover_position (c:552384a9af6ceb9eb6984a29272e73ee): entity_id=['cover.kitchen_blinds'], position=100>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1648, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/localtuya/cover.py", line 126, in async_set_cover_position
    posdiff = abs(newpos - currpos)
TypeError: unsupported operand type(s) for -: 'float' and 'str'

**Comment by thecampagnards** [comment]
I think this pr https://github.com/rospogrigio/localtuya/pull/706 is related to our issue
