### ISSUE TITLE
Devices becomes unavailable after changing ip address

### ISSUE THREAD

**Issue by junalmeida** [rospogrigio/localtuya#741]
## The problem

Localtuya integration does not update itself soon enough when ip address of device changes. Reloading localtuya also doesn't catch up. I often have to restart the HA core for it to come back online. I can access the devices on tuya app normally. 

I know this is a weird behavior and hard to track, please direct me of what logs I can provide you. 

## Environment

- Localtuya version:  3.4.0
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version:  2022.2.5

- [] Are you using the Home Assistant Tuya Cloud component ? 
- [x] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Force router to change device ip

## Configuration `configuration.yaml` or `config_flow`

```yaml

```

## Provide Home Assistant taceback/logs

```txt

```

**Comment by junalmeida** [comment]
```
This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:203
Integration: LocalTuya (documentation, issues)
First occurred: 4:41:51 PM (23 occurrences)
Last logged: 4:46:17 PM

[603...469] Connect to 10.0.0.124 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 155, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 466, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 573, in _decode_payload
    payload = self.cipher.decrypt(payload, False)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 203, in decrypt
    return self._unpad(decryptor.update(enc) + decryptor.finalize()).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 1: invalid start byte

```
