### ISSUE TITLE
Connection to device failed, exception not trapped

### ISSUE THREAD

**Issue by jpearce73** [rospogrigio/localtuya#767]
## The problem

Home Assistant logs show device connections unreliable and there are numerous posts on this and I would like to get deeper into debugging this. But the logs also show untapped exceptions. I don't understand why the exceptions are not caught. A typical entry looks like this

```
2022-03-05 15:58:35 ERROR (MainThread) [custom_components.localtuya.common] [553...41f] Connect to 192.168.50.77 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 145, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')

```
and I get lots of them that I wish to debug

```
> grep localtuya home-assistant.log | grep failed | cut -c 21- | sort | uniq -c 
    196 ERROR (MainThread) [custom_components.localtuya.common] [553...41f] Connect to 192.168.50.77 failed
      3 ERROR (MainThread) [custom_components.localtuya.common] [553...ce4] Connect to 192.168.50.56 failed
    196 ERROR (MainThread) [custom_components.localtuya.common] [843...9a7] Connect to 192.168.50.124 failed
      2 ERROR (MainThread) [custom_components.localtuya.common] [843...ae8] Connect to 192.168.50.98 failed
     10 ERROR (MainThread) [custom_components.localtuya.common] [843...cde] Connect to 192.168.50.116 failed
    220 ERROR (MainThread) [custom_components.localtuya.common] [bf3...4ci] Connect to 192.168.50.72 failed
      1 ERROR (MainThread) [custom_components.localtuya.common] [bf8...yw9] Connect to 192.168.50.23 failed
   1287 ERROR (MainThread) [custom_components.localtuya.common] [bfa...zob] Connect to 192.168.50.176 failed
   1287 ERROR (MainThread) [custom_components.localtuya.common] [bfc...feh] Connect to 192.168.50.235 failed

```
Perhaps this is my lack of Python knowledge, but the call from localtuya/common.py", line 145 is wrapped in a try except - Why doesn't the exception get trapped?
Shouldn't the broad-except catch this?
I even tried adding an explicit trap for the OSError (this is my local code) but it does not trigger my handler

```
       except Exception:  # pylint: disable=broad-except
            self.exception(f"Connect to {self._config_entry[CONF_HOST]} failed")
            if self._interface is not None:
                await self._interface.close()
                self._interface = None
        except OSError as err:
            self.debug("OSError Exception: %s",err)`

```
## Environment

- Localtuya version: 3.4.0 from HACS
- Last working localtuya version (if known and relevant):  N/A
- Home Assistant Core version:  2022.2.9
- [x] Are you using the Home Assistant Tuya Cloud component ?  Yes I have both in parallel due to one unsupported device in local.
- [] Are you using the Tuya App in parallel ?  Its configured but never used

## Steps to reproduce

1. A device that is unplugged will give this log behaviour
2. Also intermittently devices go unavailable and do this and that's what I want to debug

## Configuration `configuration.yaml` or `config_flow`

Using Config Flow

**Comment by CloCkWeRX** [comment]
So https://github.com/rospogrigio/localtuya/blob/master/custom_components/localtuya/common.py#L183 is trapping the exception.
What you are actually seeing is the call to log the exception with full details:
```self.exception(f"Connect to {self._config_entry[CONF_HOST]} failed")```
https://docs.python.org/3/library/logging.html#logging.Logger.exception

And while that is very noisy; it can be useful for debugging why something is happening.

A more nuanced version would be to explicitly catch OSError as you suggest and just logging as self.error(message); and leave the more global handler for all other broad exceptions.

It's probably worth a PR
