### ISSUE TITLE
Cannot add door sensor in home assistant

### ISSUE THREAD

**Issue by Davecl** [rospogrigio/localtuya#770]
I have added a loft heater and a door sensor in the tuya iot and got their id's and localkeys
the loft heater shows up automatically in the hass integration and adds succesfully to local tuya
the door sensor however does not show up  and when i try to add it manually i get 

**An unknown error occurred. See log for details**.

here is my log

This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya integration (documentation, issues)
First occurred: 14:08:54 (8 occurrences)
Last logged: 16:48:01

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 283, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 189, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.4.43', 6668)

**Comment by ardiankr** [comment]
I have a similar issue with my motion sensor and door sensor. Apparently, it's because the sensor wireless module immediately goes into sleep after reporting the sensor state change to conserve battery power. Try sending pings to your sensor at regular intervals while changing its state to understand its behavior.

**Comment by Davecl** [comment]
Thanks.. I'll try pinging it

**Comment by nprez83** [comment]
I have a motion sensor integrated with the newest localtuya version 4.0.0, which changed the updating scheme to push from poll. The issue with the pairing is the fact that these types of battery-operated WiFi sensors (i.e., door contact sensors, motion sensors) only connect to the WiFi briefly for about 10 seconds once activity is detected and then fall off to preserve battery. They may also wake up intermittently to check in with the Tuya cloud so it knows they're still online, although I'm not sure about this. 

So to install it, you'll want to trigger the sensor and immediately start the config flow with localtuya. You'll want to continue to trigger the sensor so it stays connected while you're finalizing the config flow as a binary_sensor (code for true is "pir", code for false is "none"). It may take a couple of tries but it works pretty well imo. 

The main problem I'm encountering is with usage. Unlike when you visualize the device in the SmartLife app, the device in localtuya actually sits unavailable most of the time until it detects motion (makes sense given that I said above), at which point it wakes up, connects to the WiFi and reports the state. All my IoT devices have static IPs btw, so in theory the reconnection process should be pretty fast. In the SmartLife app, the device takes about 1-3 secs to respond, which is very good for a WiFi device imo. Unfortunately in localtuya it takes more like 5-6 secs, which is a bit more annoying. Basically, by the time the stairs light comes on in response to the sensor I've already gotten half way down it in the dark, which is not ideal. In theory I would hope for the sensor to update even faster with localtuya then via the cloud, which is the case for my other light and switch devices, so not sure why this is the case. Hopefully it'll get fixed in future updates. I use mostly ZigBee motion sensors now, but I do have a few WiFi ones that would be nice to use if possible.
