### ISSUE TITLE
LocalTuya Not Connecting - Post 2022.4 Upgrade

### ISSUE THREAD

**Issue by rcblackwell** [rospogrigio/localtuya#790]
## System Health

version | core-2022.4.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | aarch64
timezone | America/Toronto

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4927
Installed Version | 1.24.3
Stage | running
Available Repositories | 1008
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 22, 2022, 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 113.9 GB
disk_used | 8.9 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (10.1.1), Node-RED (11.1.1), Home Assistant Google Drive Backup (0.106.2), Samba share (9.5.1), Check Home Assistant configuration (3.10.0), Network UPS Tools (0.10.0), Studio Code Server (4.2.0), Z-Wave JS (0.1.55), SQLite Web (3.3.0), ESPHome (2022.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 3
views | 29
mode | storage

</details>

## Configuration `configuration.yaml` or `config_flow`

Config Flow was used to add devices. Devices added in Nov 2021, Have worked fine until todays update of HA.

## Home Assistant taceback/logs
```
Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 8:06:32 PM (3 occurrences)
Last logged: 8:06:32 PM

[833...c53] Connect to 192.168.86.102 failed
[280...c01] Connect to 192.168.86.106 failed
[082...788] Connect to 192.168.86.108 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 145, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionResetError: [Errno 104] Connect call failed ('192.168.86.102', 6668)
```

**Comment by JeffersM1** [comment]
I have a similar error message:
2022-04-07 10:18:29 ERROR (MainThread) [custom_components.localtuya.common] [265...631] Connect to 192.168.0.152 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 151, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 472, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 457, in exchange
    payload = self._decode_payload(msg.payload)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 559, in _decode_payload
    return json.loads(payload)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by TomK** [comment]
could you try re-connecting the devices?

**Comment by JeffersM1** [comment]
> what version of LocalTuya are you running?
Here is what I have:
home_assistant: 

installation_type: Home Assistant Container, version: 2022.3.8,
   
python_version: 3.9.9,
    
timezone: Europe/Lisbon,

os_name: Linux,   os_version: 5.15.32-v8+,
 
config_editor:  version: 4.1,
   
localtuya: version: 3.2.1,

hacs:  version: 1.24.3,

**Comment by TomK** [comment]
@JeffersM1 I'd recommend trying LocalTuya 3.2.4 as the first port of call, even though there doesn't seem to be any fix since 3.2.1 that appears to be related to a connection issue

**Comment by JeffersM1** [comment]
> @JeffersM1 I'd recommend trying LocalTuya 3.2.4 as the first port of call, even though there doesn't seem to be any fix since 3.2.1 that appears to be related to a connection issue

I installed LocalTuya through the HACS integration which chose the 3.2.1 version.  How can I get HACS to point to the newer version, or do I need to use another installation method?

**Comment by TomK** [comment]
![image](https://user-images.githubusercontent.com/299656/162255209-df6b6b4d-98a4-41a1-9d86-0715585f77b9.png)
Select "Redownload" - the latest versions will hopefully be listed

**Comment by TomK** [comment]
is `192.168.0.152` still the correct ip for that device ?  i'm not sure how localtuya resolves the ip addresses or how it maintains it if the device ip is leased by DHCP

**Comment by JeffersM1** [comment]
> is `192.168.0.152` still the correct ip for that device ? i'm not sure how localtuya resolves the ip addresses or how it maintains it if the device ip is leased by DHCP

Yes, `192.168.0.152` still the correct ip.  I rescanned the network and checked that the MAC address is the same as what I saw earlier.

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 6.4.7.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Arial"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>


João Lopes Vincente
--



</body>

</html>

**Comment by JeffersM1** [comment]
When I use the add integration button to add entities to the device, the device is detected, or at least listed by the wizard.  Then when I go though the list of entities to add in the wizard, it has values listed, but the values are not showing up in the cards.
![image](https://user-images.githubusercontent.com/97175692/162271154-b5a36afa-8ce7-4c74-b19a-252122767935.png)
![image](https://user-images.githubusercontent.com/97175692/162271342-f549d486-bd7f-496c-b434-20adf107e9d3.png)
![image](https://user-images.githubusercontent.com/97175692/162271542-75fd9643-7322-4a72-b555-68857d02c15b.png)

**Comment by smarthomefamilyverrips** [comment]
I have same problem with randomly tuya devices, bulbs and switches...  any solution for this? 

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:247
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 20:09:11 (2 occurrences)
Last logged: 20:09:11

[132...557] Connect to 192.168.0.44 failed
[132...ccb] Connect to 192.168.0.47 failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 155, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by JeffersM1** [comment]
> I have same problem with randomly tuya devices, bulbs and switches... any solution for this?
> 
> Logger: custom_components.localtuya.common Source: custom_components/localtuya/pytuya/**init**.py:247 Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues)) First occurred: 20:09:11 (2 occurrences) Last logged: 20:09:11
> 
> [132...557] Connect to 192.168.0.44 failed [132...ccb] Connect to 192.168.0.47 failed Traceback (most recent call last): File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire await fut asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for fut.result() asyncio.exceptions.CancelledError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 155, in _make_connection status = await self._interface.status() File "/config/custom_components/localtuya/pytuya/**init**.py", line 481, in status status = await self.exchange(STATUS) File "/config/custom_components/localtuya/pytuya/**init**.py", line 460, in exchange msg = await self.dispatcher.wait_for(seqno) File "/config/custom_components/localtuya/pytuya/**init**.py", line 247, in wait_for await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout) File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for raise exceptions.TimeoutError() from exc asyncio.exceptions.TimeoutError

Are you having this problem with WiFi, ZigBee or some other communication type devices?  If they are ZigBee, you can use the ZigBee Home Assistant (ZHA) integration instead of Local Tuya.  ZHA is included in the HA repository.  I have started using ZHA and find that it seems to better support my ZigBee devices.  To use ZHA, you will need a USB to ZigBee adapter (not sure of the correct name here).

**Comment by smarthomefamilyverrips** [comment]
> > I have same problem with randomly tuya devices, bulbs and switches... any solution for this?
> > Logger: custom_components.localtuya.common Source: custom_components/localtuya/pytuya/**init**.py:247 Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues)) First occurred: 20:09:11 (2 occurrences) Last logged: 20:09:11
> > [132...557] Connect to 192.168.0.44 failed [132...ccb] Connect to 192.168.0.47 failed Traceback (most recent call last): File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire await fut asyncio.exceptions.CancelledError
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for fut.result() asyncio.exceptions.CancelledError
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 155, in _make_connection status = await self._interface.status() File "/config/custom_components/localtuya/pytuya/**init**.py", line 481, in status status = await self.exchange(STATUS) File "/config/custom_components/localtuya/pytuya/**init**.py", line 460, in exchange msg = await self.dispatcher.wait_for(seqno) File "/config/custom_components/localtuya/pytuya/**init**.py", line 247, in wait_for await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout) File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for raise exceptions.TimeoutError() from exc asyncio.exceptions.TimeoutError
> 
> Are you having this problem with WiFi, ZigBee or some other communication type devices? If they are ZigBee, you can use the ZigBee Home Assistant (ZHA) integration instead of Local Tuya. ZHA is included in the HA repository. I have started using ZHA and find that it seems to better support my ZigBee devices. To use ZHA, you will need a USB to ZigBee adapter (not sure of the correct name here).

I have only Tuya compatible WIFi devices, so unfortunately ZHA is no option for me

**Comment by StopDragon** [comment]
I am also experiencing the same symptoms. 
tuya device is well connected to wifi. 
Also, the connection to the tuya server is good. 
But I keep losing connection with local tuya.

`이 오류는 사용자 통합 구성요소에서 발생했습니다.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:637 
Integration: LocalTuya integration (documentation, issues) 
First occurred: 08:03:09 (1 occurrences) 
Last logged: 08:03:09

[ebf...vsd] Connect to 192.168.0.106 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 141, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.0.106', 6668)
`

**Comment by JeffersM1** [comment]
StopDragon, my Bituo PG-01 was working a few weeks ago, but suddenly stopped, I believe it was after some updates.  Was your meter working in the past?  Which meter are you using?

**Comment by smarthomefamilyverrips** [comment]
> StopDragon, my Bituo PG-01 was working a few weeks ago, but suddenly stopped, I believe it was after some updates. Was your meter working in the past? Which meter are you using?

This behavior is not only related to meter devices, as I shared before I am only using WIFI bulbs and sockets

**Comment by JeffersM1** [comment]
If problems you are having is with ZigBee devices, you may want to look at the ZigBee Home Assistant integration page:  https://www.home-assistant.io/integrations/zha/
There they have a section titled "BEST PRACTICES TO AVOID PAIRING/CONNECTION DIFFICULTIES".  I will be giving that a try with some of my smart sockets once I find out how to manually reset the devices to their factory default settings.

**Comment by nortuzar** [comment]
> If problems you are having is with ZigBee devices, you may want to look at the ZigBee Home Assistant integration page: https://www.home-assistant.io/integrations/zha/ There they have a section titled "BEST PRACTICES TO AVOID PAIRING/CONNECTION DIFFICULTIES". I will be giving that a try with some of my smart sockets once I find out how to manually reset the devices to their factory default settings.

Thanks for the reply, but I´m using wifi devices

**Comment by apozuelo** [comment]
I'm also having this issue with two of my tree kind of devices. Any new?

**Comment by nortuzar** [comment]
> 

Dont know if this could help you, but I was running HA under VM on proxmox. Was using adguard addon on home assistant and today I migrate adguard to its own LXC. After that, I'm not seeing any disconnection, looking good until now. Don't know is this is just coincidence or there is something that help moving adguard outside of home assistant

**Comment by mkaatman** [comment]
TYWES3S is ESP. If you wanted you could potentially open it up and flash esphome or tasmota on it. I don't think anyone has done it yet though.

tuya-convert might even work to get tasmota on it. I'm not sure how complicated it would be to make it function after that.

**Comment by pecheveHA** [comment]
I have the same problem. 
Running under Raspberry Pi 3B+

   Home Assistant Core 2022.6.0
   Home Assistant Supervisor 2022.05.3
   Home Assistant OS 8.1

   HACS v1.25.5
   Local Tuya v3.5.0 (installed through HACS)

Devices: 2 Candle Bulbs MIOBULB006 4.9W
Both work fine with Tuya Smart Life, 
Device IDs and Local keys obtained with Tuya IoT Platform
WIFI Connected, MACs & IP Addresses OK. I can see them with LAN tools

When I use the add integration button to add entities to the device, the device is detected, or at least listed by the wizard, the Device IDs are listed with the rigth IP Adresses

When I selected any (even ... to add manually a device) and I fill the form (Name, Local Key, protocol version 3.1 / 3.3) the response is:  **_An unknown error occurred. See log for details_**

Log content

_Este error se originó a partir de una integración personalizada._

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:247
Integration: LocalTuya integration (documentation, issues)
First occurred: 19:21:54 (1 occurrences)
Last logged: 19:21:54

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 417, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 283, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 196, in validate_input
    detected_dps = await interface.detect_available_dps()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 539, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError_


Any Help?

**Comment by bradphillips921** [comment]
I'm having the same problem, It's near impossible to add devices. I'm trying to add lights, I was able to add 3 lights, but that took about 20 tries.

Here is my log, same as the others.

```
This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:247
Integration: LocalTuya (documentation, issues)
First occurred: 10:24:37 PM (1 occurrences)
Last logged: 10:24:37 PM

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 417, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 283, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 196, in validate_input
    detected_dps = await interface.detect_available_dps()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 539, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```


Is there a fix to this yet?

**Comment by rfam13** [comment]
Same problem.  I have 3 devices connected using local tuya that are always available and works great.  I also have 3 other devices that go unavailable every minute, then come online for a minute, then unavailable again. 

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:247
Integration: LocalTuya (documentation, issues)
First occurred: 9:33:23 AM (66 occurrences)
Last logged: 10:26:17 AM

Traceback (most recent call last): File "/usr/local/lib/python3.9/asyncio/locks.py", line 417, in acquire await fut asyncio.exceptions.CancelledError During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for return fut.result() asyncio.exceptions.CancelledError The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 155, in _make_connection status = await self._interface.status() File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status status = await self.exchange(STATUS) File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange msg = await self.dispatcher.wait_for(seqno) File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout) File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for raise exceptions.TimeoutError() from exc asyncio.exceptions.TimeoutError

**Comment by mkile** [comment]
Same problem with Tuya 1-gang relay switch, get TimeoutError. Cloud version of Tuya HA extension and Smartlife app works without problems.

**Comment by laithsaid** [comment]
Same problem here. I have 11 smart plugs, 2 are running firmware version 3.1, and the rest are running firmware version 3.3
The 2 with version 3.1 are working fine. All the ones with version 3.3 are having this issue.
All of them are Smart Power Plugs with wifi. 
All have been working until HA community became very active and started to do new releases every few days, then they stopped working.
