### ISSUE TITLE
Setup failed for custom integration localtuya after Hassio Update 2022.04

### ISSUE THREAD

**Issue by Chaosflori25** [rospogrigio/localtuya#792]
## The problem
 I updated Hassio to 2022.04. Before everything was just fine.

## Environment
Hassio Supervised in Lunix Docker Container
- Localtuya version:3.2.4  
- Last working localtuya version (if known and relevant): 3.2.4
- Home Assistant Core version: 2022.04  
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Update Hassio
2. Message in Infobar
3. Logs

## Configuration `configuration.yaml` or `config_flow`

```yaml
Did everything via the Ui, so here are no real usefull information
Protocol:3.3
2 Entities
2 Gang Lightswitch
```

## DP dump
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 15:51:02 (1 occurrences)
Last logged: 15:51:02

Setup failed for custom integration localtuya: Unable to import component: cannot import name 'SPEED_HIGH' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)

## Provide Home Assistant taceback/logs

```txt
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 15:51:02 (1 occurrences)
Last logged: 15:51:02

Setup failed for custom integration localtuya: Unable to import component: cannot import name 'SPEED_HIGH' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)
```
## Additional information

After the update Hassio did not want to accept Speed High as name for homeassistant.components.fan so I can't use the custom component anymore

**Comment by Dualin2** [comment]
I have the same problemas since I have updated to 2022.04 version

**Comment by night-crawler5252** [comment]
same problem here

**Comment by CloCkWeRX** [comment]
This is now fixed by upgrading to 3.5.0; if you haven't already swapped to master.
You may need to view the localtuya repository and "update information" to make sure your HACS knows about the latest releases.

Please give it a go and close this when working :)

**Comment by fire943** [comment]
I have 3.5.0.  and get a the follow

This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya (documentation, issues)
First occurred: 11:21:53 AM (1 occurrences)
Last logged: 11:21:53 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 283, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 189, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.**.**', ****)

**Comment by taylormia** [comment]
I'm on HA 2022.4.7 and localtuya 3.5.0 and am getting this error:


Logger: homeassistant.components.fan
Source: custom_components/localtuya/fan.py:74
Integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 4:22:15 PM (2 occurrences)
Last logged: 4:22:15 PM

Error while setting up localtuya platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/localtuya/common.py", line 74, in async_setup_entry
    entity_class(
  File "/config/custom_components/localtuya/fan.py", line 74, in __init__
    self._ordered_list = self._config.get(CONF_FAN_ORDERED_LIST).split(",")
AttributeError: 'NoneType' object has no attribute 'split'`
