### ISSUE TITLE
LocalTuya fails starting after update HA 2022-04 : Invalid config The following integrations and platforms could not be set up:  localtuya 

### ISSUE THREAD

**Issue by bentouspam** [rospogrigio/localtuya#793]
Hello,
After running 2022-04  upgrade, all my LocalTuya devices disapears.
LocalTuya is still there in the http://homeassistant:8123/config/integrations, but the devices are tagged : "unloaded"
the device configuration is correct, vith the name, the IP and local_key, but <Submit> send a (!) Unknown error occured.
this is the same problem for all my 7 LocalTuya devices.
What a pitty, it was working so well !!!

Here are the logs:

Cette erreur provient d'une intégration personnalisée

Logger: aiohttp.server
Source: custom_components/localtuya/fan.py:6
Integration: LocalTuya integration (documentation, issues)
First occurred: 16:38:06 (2 occurrences)
Last logged: 16:39:33

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 267, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 407, in async_step_init
    return await self.async_step_entity()
  File "/config/custom_components/localtuya/config_flow.py", line 438, in async_step_entity
    schema = platform_schema(
  File "/config/custom_components/localtuya/config_flow.py", line 139, in platform_schema
    return vol.Schema(schema).extend(flow_schema(platform, dps_strings))
  File "/config/custom_components/localtuya/config_flow.py", line 145, in flow_schema
    return import_module("." + platform, integration_module).flow_schema(dps_strings)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/localtuya/__init__.py", line 90, in <module>
    CONFIG_SCHEMA = config_schema()
  File "/config/custom_components/localtuya/config_flow.py", line 161, in config_schema
    entity_schemas = [
  File "/config/custom_components/localtuya/config_flow.py", line 162, in <listcomp>
    platform_schema(platform, range(1, 256), yaml=True) for platform in PLATFORMS
  File "/config/custom_components/localtuya/config_flow.py", line 139, in platform_schema
    return vol.Schema(schema).extend(flow_schema(platform, dps_strings))
  File "/config/custom_components/localtuya/config_flow.py", line 145, in flow_schema
    return import_module("." + platform, integration_module).flow_schema(dps_strings)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/localtuya/fan.py", line 6, in <module>
    from homeassistant.components.fan import (
ImportError: cannot import name 'SPEED_HIGH' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)

Locally yours,
Benoit.

**Comment by bentouspam** [comment]
System Configuration:

System Health

version: core-2022.4.0
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.9
os_name: Linux
os_version: 5.10.103-v8
arch: aarch64
timezone: Europe/Paris


GitHub API: ok
GitHub Content: ok
GitHub Web: ok
GitHub API Calls Remaining: 4977
Installed Version: 1.24.3
Stage: running
Available Repositories: 1080
Downloaded Repositories: 3


logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok


host_os: Home Assistant OS 7.6
update_channel: stable
supervisor_version: supervisor-2022.03.5
docker_version: 20.10.9
disk_total: 237.7 GB
disk_used: 9.5 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok
installed_addons: Mosquitto broker (6.0.1), Samba share (9.5.1), Zigbee2mqtt (1.25.0-1), Home Assistant Google Drive Backup (0.106.2), Terminal & SSH (9.3.0), Node-RED (11.1.1), Studio Code Server (4.2.0), Log Viewer (0.13.0), eWeLink Smart Home (1.2.4)


dashboards: 2
resources: 1
views: 7
mode: storage

**Comment by bentouspam** [comment]
I modified custom_components/localtuya/const.py line 49 with
PLATFORMS = ["binary_sensor", "cover", "light", "sensor", "switch"]
and it works well.
I close it, but feel free to ask me some additional informations.

Thanks for this job, my Tuya devices are much more responsive with LocalTuya !!!

**Comment by drsmarsden** [comment]
Logger: homeassistant.setup
Source: setup.py:162 
First occurred: 19:21:31 (1 occurrences) 
Last logged: 19:21:31

Setup failed for custom integration localtuya: Unable to import component: cannot import name 'SPEED_HIGH' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)

**Comment by drsmarsden** [comment]
My const.py is correct as per last post

**Comment by CloCkWeRX** [comment]
@bentouspam and @drsmarsden see #780 around SPEED_HIGH - you'll want to swap to `master` branch to get the latest.
