### ISSUE TITLE
Mini smart switch tuya - add error

### ISSUE THREAD

**Issue by alespaghetti** [rospogrigio/localtuya#814]
Hello
i have installed HA on raspberry 0. HA works fine.
On HA I have installed local tuya which recognizes most of my tuya devices and I can manage them in lan.
Local tuya, however, is unable to install mini smart switches like the ones in the picture.
The switches are recognized on the network by the wizard but when I have to add the device, I get back the message "An unknown error occurred. See log for details.".
Thanks for your kind support

## Environment

- Localtuya version: 3.5.0
- Home Assistant Core version: 2022.4.7
- [x] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Add new local tuya device
2. recognize smart switch ip and id, add it (insert key and name)
3. error
![IMG_20220405_121701](https://user-images.githubusercontent.com/51400636/165458838-1a208bfb-7cd5-4238-b478-91b76e5da8a2.jpg)

**Comment by alespaghetti** [comment]
from log:

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 13:34:26 (5 occurrences)
Last logged: 13:39:59
Unexpected exception

Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 283, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 189, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.175', 6668)

**Comment by 85hui** [comment]
Same problem here.Have you found an answer for this?

**Comment by alespaghetti** [comment]
> Same problem here.Have you found an answer for this?

Yes I solved.
Just turn off 5ghz wifi on router or give a different name for 2,4 and 5ghz essid.
I don't know why but it works.
