### ISSUE TITLE
Fiber light, Kingmaled LED engine fails to connect

### ISSUE THREAD

**Issue by fribse** [rospogrigio/localtuya#819]
## The problem

The device appears in Smart Life as a light strip, and shows a RGBW light.
When I try to add it to Home Assistant, no matter if it's on a seperate Wifi, or directly on LAN, it gives me a timeout.

## Environment

- Localtuya version: 3.5.0
- Last working localtuya version (if known and relevant): N/A
- Home Assistant Core version:  Core 2022.5.3
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1. Add the device to the Smart Life App
2. Link a developer account to the Smart Life App
3. Add the device in Home Assistant with the IP, ID, and local key, it fails.

## Configuration `configuration.yaml` or `config_flow`

```yaml

```

## DP dump

INFO:localtuya:localtuya version 1.0.0
INFO:localtuya:Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
INFO:localtuya:Using pytuya version '8.1.0'
INFO:localtuya:Detecting list of available DPS of device 5416402184f3eb52d127 [10.11.12.71], protocol 3.3.
DEBUG:localtuya.pytuya:Sending command status (device type: type_0a)
DEBUG:localtuya.pytuya:paylod=b'{"gwId":"5416402184f3eb52d127","devId":"5416402184f3eb52d127"}'
DEBUG:localtuya.pytuya:DATA RECEIVED!
DEBUG:localtuya.pytuya:decode payload=b"l\xc1h\x86Y\xaei\xaff\xd0\xbb\x97T\xb7\xb9c@\xf8q\xdc_#\xacW\xd4\xf4\x9e\xbdV\r\xd2\x03\xe8\xe8J\xbe\xf6\x9c\xe3\x90\x19\xa5u\x9a\x06u3L\xac%\xec0\r*3\xcf\xdf\xcat\x04t\xf0a\xd4\x0f_\xf2\r\xd8pWZ\xc0\xfb\xa3\xae{4f\xb8X8XH\xd9\xfc\xccT\x8a\x0f\xec\\xk\x84\xea\xb7L\xe0\x17\xd1\xc2p`o5\xed\xaa,\xa3\xc6~\xf0\x1e\xe8\x01\xfe^\xae\xd8n\x1c,\xe6j\xde\x9a\xc2\xc1lrq;U\xdd\x94\x83\x16#/\xe02)L\xdaF>\xf6q\xcb\x7f\xc6@\\k\n\xa3\xeep\x82\xf4\xacs\x0f\xf8#\xfd;\xa32I\x9a\xc6Q\x15Z\x94d;\x1d\xff\xc5U\xfc\xaai\x1e\x81'p\xb3^.\xb9\xfc\x8e\x04\xfc\xf7\xceK\xb2\x91\x94\x0c~,\x88\x028@t\xb03S2\x8b\xe0Cs\x8f\x0f\x8e5\xe8\xc0\x8b!.\x03o\xed\x19\xfcGO\x1d\x8d#\xaf\x81\xd6 O\x1f\x1e[\xf0\xc9J\xf3\x01'o\rz\x91\xa1e\xf5\t\x92\xc9\x85\x1d\x92\xa9\xe9\xfe\x02\xfdm"
DEBUG:localtuya.pytuya:decrypted result='{"devId":"5416402184f3eb52d127","dps":{"1":true,"2":"white","3":255,"5":"1900000000ff19","6":"00ff0000000000","7":"ffff500100ff00","8":"ffff8003ff000000ff000000ff000000000000000000","9":"ffff5001ff0000","10":"ffff0505ff000000ff00ffff00ff00ff0000ff000000"}}'
AVAILABLE DPS ARE [{'1': True, '2': 'white', '3': 255, '5': '1900000000ff19', '6': '00ff0000000000', '7': 'ffff500100ff00', '8': 'ffff8003ff000000ff000000ff000000000000000000', '9': 'ffff5001ff0000', '10': 'ffff0505ff000000ff00ffff00ff00ff0000ff000000'}]
INFO:localtuya:COMPLETE response from device 5416402184f3eb52d127 [10.11.12.71].

**** deviceInfo returned OK ****

TuyaDebug (Tuya DPs dump) [1.0.0]

Device 5416402184f3eb52d127 at 10.11.12.71 key 302239c7b2d6d8f2 protocol 3.3 dev_type type_0a:
    DPS [1] VALUE [True]
    DPS [2] VALUE [white]
    DPS [3] VALUE [255]
    DPS [5] VALUE [1900000000ff19]
    DPS [6] VALUE [00ff0000000000]
    DPS [7] VALUE [ffff500100ff00]
    DPS [8] VALUE [ffff8003ff000000ff000000ff000000000000000000]
    DPS [9] VALUE [ffff5001ff0000]
    DPS [10] VALUE [ffff0505ff000000ff00ffff00ff00ff0000ff000000]
## Provide Home Assistant taceback/logs

```txt
Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:247
Integration: LocalTuya integration (documentation, issues)
First occurred: 16.43.07 (6 occurrences)
Last logged: 17.32.28

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 413, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 283, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 196, in validate_input
    detected_dps = await interface.detect_available_dps()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 539, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

```

**Comment by fribse** [comment]
Now I got it connected fine, not sure what went wrong. Now I just need to get it working by selecting the right fields.
