### ISSUE TITLE
Error while adding device after update

### ISSUE THREAD

**Issue by prbtt** [rospogrigio/localtuya#846]
This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya (documentation, issues)
First occurred: 12:38:20 AM (2 occurrences)
Last logged: 12:38:28 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 283, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 189, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('10.0.0.136', 6668)

**Comment by felipeduba** [comment]
Same problem here...

**Comment by alkaldt** [comment]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 280, in async_setup_entry
    await async_remove_orphan_entities(hass, entry)
  File "/config/custom_components/localtuya/__init__.py", line 316, in async_remove_orphan_entities
    ent_reg = await er.async_get(hass)
**TypeError: object EntityRegistry can't be used in 'await' expression**

**Comment by prbtt** [comment]
After resetting the device a couple times, I was able to successfully add it to HA
