### ISSUE TITLE
ValueError: Config entry has already been setup!

### ISSUE THREAD

**Issue by pergolafabio** [rospogrigio/localtuya#865]
## The problem
Hi, after the new update today, all my 3 local tuya devices were now migarted into 1 config entry instead of 3
I removed my yaml config also, but on every restart now i always have error below:

## Environment
- Localtuya version: 4.0.0
- Last working localtuya version (if known and relevant):  3.x 
- Home Assistant Core version: 2002.6.5

## Configuration `configuration.yaml` or `config_flow`

```
No yaml config anymore its removed
```

```
2022-06-14 20:46:47 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localtuya for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 597, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 157, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

**Comment by homecb** [comment]
Getting a similar error, but for switch.

**Comment by JackTalisker** [comment]
Duplicate issue. See #857

**Comment by smarthomefamilyverrips** [comment]
After adjusting init.py with the latest commited changes:

https://github.com/rospogrigio/localtuya/commit/dd565379a3049bfe8e94e949a3ab779371dc9737

at me this error is not showing up anymore after restart and all works as before. Thank you @rospogrigio !!!
