### ISSUE TITLE
Error for dehumidifier

### ISSUE THREAD

**Issue by pickonedev** [rospogrigio/localtuya#889]
Hi!

I get all kind of errors about my tuya dehumidifier...

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:157
First occurred: 22:51:25 (8 occurrences)
Last logged: 22:51:29

    Error setting up entry localtuya for select
    Error setting up entry localtuya for number
    Error setting up entry localtuya for switch
    Error setting up entry localtuya for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 60, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 157, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

Sometimes I get more than 3 different errors... Any idea why?
I configured the device in a proper way....

**Comment by pickonedev** [comment]
Another error. In fact, this is a warning

```
Logger: custom_components.localtuya.switch
Source: custom_components/localtuya/pytuya/__init__.py:139
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 23:19:36 (1 occurrences)
Last logged: 23:19:36
[016...f78] Entity switch.dressing_notifier_switch is requesting unknown DPS index 104
```

**Comment by pickonedev** [comment]
This is an error

```
 Logger: homeassistant.util.logging
Source: util/logging.py:116
First occurred: 23:19:36 (1 occurrences)
Last logged: 23:19:36
Exception in _update_handler when dispatching 'localtuya_016455803c3122b1f78': ({'105': 285, '106': 49},) Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 327, in _update_handler self.status_updated() File "/config/custom_components/localtuya/select.py", line 96, in status_updated self._state_friendly = self._display_options[self._valid_options.index(state)] ValueError: None is not in list 
```

**Comment by pickonedev** [comment]
And another one. I put them all in a specific comment, to be easy to follow

```
Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:247
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 23:19:41 (1 occurrences)
Last logged: 23:19:41
[016...f78] Connect to 192.168.0.79 failed

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 417, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 170, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```
