### ISSUE TITLE
[bf1...gfa] Entity light.hallway_lightning is requesting unknown DPS index 24

### ISSUE THREAD

**Issue by nikrays** [rospogrigio/localtuya#894]
## The problem

I purchased the "WT5 Tuya Smart RGBCCT Controller", did everything according to the instructions, for integration via localtuya, everything worked out, everything worked for a while, after which the electricity turned off in the house for 20 minutes, after which it turned on, and I decided to check how the backlight works, as it turned out, I lost the ability to change the color, there were such errors in the log as "[bf1...gfa] Entity light.hallway_lightning is requesting unknown DPS index 24" and "[547563857568] object of type 'NoneType' has no len( )" further that I just did not try, reinstalled the integration, rebooted from the outlet, deleted and added again, but everything was empty ..
After that, I decided to try my controller and ribbon in principle? Again I decided to download the "Tuya Smart" application to my smartphone, after which I switched the color from white (it was originally) to red, and a miracle happened, the color changed! This is not the first time this problem has happened, as if by changing the color through the application, I am laying a certain route for localtuya integration through the API, and it all works for a while ..
Guys, who faced similar? Help me please.

upd: Наткнулся на форум Reddit, где у пользователя другого осветительного прибора подобная проблема [https://www.reddit.com/r/homeassistant/comments/k3jaqx/localtuya_powercycle/](url)

## Environment

- Localtuya version:  v4.0.0
- Last working localtuya version (if known and relevant): v4.0.0
- Home Assistant Core version:  2022.6.6
- [] Are you using the Home Assistant Tuya Cloud component ? no
- [] Are you using the Tuya App in parallel ? no

## Provide Home Assistant taceback/logs
________________________________________________________________________
[bf1...gfa] Entity light.hallway_lightning is requesting unknown DPS index 24

Logger: custom_components.localtuya.light
Source: custom_components/localtuya/pytuya/__init__.py:139
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 19:55:00 (43 occurrences)
Last logged: 20:27:05

[bf1...gfa] Entity light.hallway_lightning is requesting unknown DPS index 24
[bf1...gfa] Entity light.hallway_lightning is requesting unknown DPS index 25
____________________________________________________________________
[547563857568] object of type 'NoneType' has no len()

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/localtuya/light.py:285
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 19:56:34 (31 occurrences)
Last logged: 20:27:03

[547563857568] object of type 'NoneType' has no len()
[547439386144] object of type 'NoneType' has no len()
[547563933808] object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/localtuya/light.py", line 358, in async_turn_on
    if self.__is_color_rgb_encoded():
  File "/config/custom_components/localtuya/light.py", line 285, in __is_color_rgb_encoded
    return len(self.dps_conf(CONF_COLOR)) > 12
TypeError: object of type 'NoneType' has no len()

**Comment by Sherhankot** [comment]
Have the same issue
