### ISSUE TITLE
An unknown error occurred. See log for details.

### ISSUE THREAD

**Issue by CC91300** [rospogrigio/localtuya#907]
Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 14:13:57 (9 occurrences)
Last logged: 14:21:32

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 533, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 235, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.2.12', 6668)

**Comment by prbtt** [comment]
There are a lot of people repoting this same issue here. Hopefully we'll get an answear soon...

**Comment by suka233** [comment]
me too

**Comment by TUISTERa** [comment]
My solution - remove the component and reinstall

**Comment by CloCkWeRX** [comment]
Duplicate of #897
