### ISSUE TITLE
Issue adding climat device MOES BHT-002

### ISSUE THREAD

**Issue by phenixar** [rospogrigio/localtuya#910]
Hi,

I try to add my device BHT-002 from moes manufacturor in Home Assistant, but failed.

I try many local tuya project, some other let me add it, but the main project, this one, I can't add it from many month.
Could you please make it possible, I can help if you need test.

![image](https://user-images.githubusercontent.com/26787364/175258949-6fcb0c39-dcda-440b-b70e-47ad497ca903.png)
![image](https://user-images.githubusercontent.com/26787364/175259307-235426a0-53e5-421b-b394-14b6911f555b.png)
![image](https://user-images.githubusercontent.com/26787364/175259480-def547a5-2ed5-410d-a5ef-e273ec4b9aee.png)

==============================================
Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:247
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 10:47:22 (1 occurrences)
Last logged: 10:47:22

[306...9dc] Failed to get status:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 417, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 539, in detect_available_dps
    data = await self.status()
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/home/homeassistant/homeassistant/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by prbtt** [comment]
This integration seems to be broken after HA updated to 2022.6
