### ISSUE TITLE
LocalTuya (custom integration) - message first occurred at June 23, 2022, 12:33:20 and shows up 9954 times

### ISSUE THREAD

**Issue by Axydas** [rospogrigio/localtuya#913]
I am getting the below error many times. In order to fix it i have to restart HA but after some hours i get the same error. Here is what i get in the log:

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: June 23, 2022, 12:33:20 (9954 occurrences)
Last logged: 09:00:45

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 160, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionResetError: [Errno 104] Connect call failed ('192.168.0.158', 6668)

**Comment by NzKyle** [comment]
is the device with IP 192.168.0.158 online?

**Comment by rlangtind** [comment]
Im seeing the same on one of my switches:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 160, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.213', 6668)

The device works fine through the Smart Home app, so it is online.

I only started seeing problems since upgrading to v4

**Comment by Axydas** [comment]
> is the device with IP 192.168.0.158 online?

Hi all devices are up. All devices are working properly through Smart Home app

Before the last update I never had any issue with the LocalTuya. From the day I proceed with the update I have this issue FOR ALL DEVICES

Are up after restart but after some time I get the error I put and All devices become unavailable

**Comment by Axydas** [comment]
> Im seeing the same on one of my switches:
> 
> Traceback (most recent call last): File "/config/custom_components/localtuya/common.py", line 160, in _make_connection self._interface = await pytuya.connect( File "/config/custom_components/localtuya/pytuya/**init**.py", line 669, in connect _, protocol = await loop.create_connection( File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection raise exceptions[0] File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection sock = await self._connect_sock( File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock await self.sock_connect(sock, address) File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect return await fut File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb raise OSError(err, f'Connect call failed {address}') OSError: [Errno 113] Connect call failed ('192.168.0.213', 6668)
> 
> The device works fine through the Smart Home app, so it is online.
> 
> I only started seeing problems since upgrading to v4

You are lucky if you have this issue for one device. I have the issue for All devixes

**Comment by Axydas** [comment]
Any way to downgrade the I tegration?

New version is totally useless for me

**Comment by StopDragon** [comment]
same issue to me

`이 오류는 사용자 통합구성요소에서 발생했습니다.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:669 
Integration: LocalTuya integration (documentation, issues) 
First occurred: 00:54:00 (167 occurrences) 
Last logged: 09:47:10

[eb5...uit] Connect to 192.168.1.202 failed
[eb8...azg] Connect to 192.168.1.201 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 160, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.202', 6668)

`

**Comment by prbtt** [comment]
> Any way to downgrade the I tegration?
> 
> New version is totally useless for me

You can change the version in HACS when installing the integration. Though I think it's more of an issue with HA and how it communicates. V3 also doesn't work anymore for me.
