### ISSUE TITLE
Can't change any config through the UI after v4.0.0 -> v4.0.1

### ISSUE THREAD

**Issue by dkarzon** [rospogrigio/localtuya#921]
## The problem
After updating from v4.0.0 to v4.0.1 I can no longer edit a device through the configuration. When I check the "Edit a device" option and click submit I get this error message in the UI
![image](https://user-images.githubusercontent.com/214449/176325104-28d36710-8a70-462f-b107-132c1f0bc0c1.png)

Is there a way to get the yaml config back and setup my devices there because the UI config flow has been giving me issues the entire time.

## Environment
- Localtuya version: v4.0.1
- Last working localtuya version (if known and relevant): v4.0.0 I could edit devices but not remove devices. Pre-v4 worked better though.
- Home Assistant Core version: 2022.6.7
- [] Are you using the Home Assistant Tuya Cloud component ? No
- [] Are you using the Tuya App in parallel ? No

## Steps to reproduce
1. In HA settings under integrations click configure on the Local Tuya integration
2. Check "Edit a device"
3. Click submit
4. Error message appears and does not let you edit the device

## Configuration `configuration.yaml` or `config_flow`
```yaml
config_flow
```

## Provide Home Assistant taceback/logs
I have these errors in the Home Assistant logs which might be related.
```
2022-06-29 10:10:35 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 242, in async_setup_entry
    region = entry.data[CONF_REGION]
KeyError: 'region'
```
```
2022-06-29 10:11:18 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 266, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 370, in async_step_init
    return await self.async_step_edit_device()
  File "/config/custom_components/localtuya/config_flow.py", line 485, in async_step_edit_device
    for dev_id, configured_dev in self.config_entry.data[CONF_DEVICES].items():
KeyError: 'devices'
```

**Comment by Stooovie** [comment]
My devices go unavailable on 4.0.1 (HA restart required), fine in 4.0.0. No time to actually file a report atm, just adding that you're not alone with this.

**Comment by dkarzon** [comment]
I got this working again by deleting the integration and reconfiguring all the devices again. Maybe this is an issue with the migration path of the entities?

**Comment by roja45** [comment]
@Stooovie Is there a process for rolling back to a previous version, or do you have to uninstall it, install the earlier version, and then add all the devices again?

I am experiencing the same issue with all the devices going Unavailable.  A reboot brought them back, but again sometime yesterday they went unavailable again.  This has only been happening since I updated to the latest version on HACS.

Thanks

**Comment by Stooovie** [comment]
I just did the "Redownload" thing in HACS, it offers various versions.

**Comment by roja45** [comment]
Cheers bud, downgraded, nothing exploded.

**Comment by rmvangun** [comment]
Downgrade didn't work for me. I will add that no longer having an approach to adding devices via YAML and requiring the config flow route makes disaster recovery a real headache for folks who have a large number of devices, and for whom auto-discovery doesn't work.

**Comment by timnolte** [comment]
I am able to get through to "Edit a device" but I can no longer add additional DPs to my device. I had only gotten 1 DP configured and it's been working but wanted to test out getting some of the other DPs setup as entities so that I could have more control over my device.

**Comment by roja45** [comment]
I also can't delete any of the devices from this screen:
2022-07-27 11:03:57 ERROR (MainThread) [custom_components.localtuya.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 533, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 237, in validate_input
    data[CONF_DEVICE_ID],
KeyError: 'device_id'

**Comment by timnolte** [comment]
I saw there was a new release today and hoped from what I saw that there was some fix for the broken/missing editing feature for DPs but alas this is still broken. Can we ever expect to be able to change the types of DPs again without having to blow away the entire device and start over from scratch?
