### ISSUE TITLE
Tuya Doorbell recognised by LocalTuya integration but can't be added

### ISSUE THREAD

**Issue by Tompi89** [rospogrigio/localtuya#924]
Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya integration (documentation, issues)
First occurred: 18:46:16 (2 occurrences)
Last logged: 19:06:22

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 533, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 235, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.0.126', 6668)

**Comment by sacredprey005** [comment]
+1 on this please

**Comment by CloCkWeRX** [comment]
Duplicate of #897
