### ISSUE TITLE
Connect to 192.x.x.x failed

### ISSUE THREAD

**Issue by Axydas** [rospogrigio/localtuya#925]
After the integration of version 4 and the configuration i done i am getting the below error for ALL devices i have, meaning that all devices are unavailable

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:247
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 12:58:00 (118 occurrences)
Last logged: 13:10:24

[566...53c] Connect to 192.x.x.x failed

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 417, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 170, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 476, in exchange
    return await self.exchange(command, dps)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by hmnd** [comment]
Did you ever solve this issue? Have been dealing with this on and off for a while...
