### ISSUE TITLE
How to unselect/reset a DP field?

### ISSUE THREAD

**Issue by mendoncart** [rospogrigio/localtuya#926]
Hello!

I just want to know how to empty a selection made for an DP.
I selected one DP for the field light color, but it was wrong, the field I should have filled was color temperature.
Now I can't empty the field I've wrongly filled, there is only option to select another value for it.

Is the only solution deleting the device and configure it again?

**Comment by KaportsevIA** [comment]
i can't delete DP's too. Error:

> Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:237
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 15:04:42 (1 occurrences)
Last logged: 15:04:42

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 533, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 237, in validate_input
    data[CONF_DEVICE_ID],
KeyError: 'device_id'
![Снимок экрана 2022-07-01 150455](https://user-images.githubusercontent.com/98884453/176891229-94523b72-7e90-4cf7-9b33-81f98ffe8129.png)

**Comment by mendoncart** [comment]
Well, this wasn't actually what I was saying, my problem is that, once I've selected one dp for, let's say, brightness, I can't clear the selection made for brightness, only change the dp. If I made a mistake, and my light don't have brightness control, I can't edit and remove the brightness...

But, I'm also having the same problem as you. I can't delete a entity, or only one device, the work arroun is to delete the whole integration, and loose all other devices you have.

**Comment by CloCkWeRX** [comment]
Duplicate of #897
