### ISSUE TITLE
All devices fail migration with Exception in callback _SelectorDatagramTransport._read_ready()

### ISSUE THREAD

**Issue by paulearley** [rospogrigio/localtuya#930]
I have tried migrating from 3.5 (working great) to 4.0 and 4.01. Each time I have the same error, on all devices: 
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/localtuya/common.py:117
Integration: LocalTuya (documentation, issues)
First occurred: 5:56:41 PM (286 occurrences)
Last logged: 5:59:11 PM

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1026, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
    self.device_found(decoded)
  File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
    self._callback(device)
  File "/config/custom_components/localtuya/__init__.py", line 105, in _device_discovered
    entry = async_config_entry_by_device_id(hass, device_id)
  File "/config/custom_components/localtuya/common.py", line 117, in async_config_entry_by_device_id
    if device_id in entry.data[CONF_DEVICES]:
KeyError: 'devices'

What are next steps in fixing this?
paulearley

**Comment by Couta7** [comment]
Same error here!

**Comment by Axydas** [comment]
same

**Comment by ff4500** [comment]
Ditto. Just installed on a 2022.7 HA and getting the same error.

**Comment by LintHart** [comment]
+1 2022.6.5. 
Running 4.01

**Comment by CloCkWeRX** [comment]
Duplicate of #887

**Comment by findel** [comment]
Looks to me like this is a duplicate of #869

So are #1095 and #887

I suggest everyone else who is experiencing this error also uses #869
