### ISSUE TITLE
Help on configuration

### ISSUE THREAD

**Issue by Axydas** [rospogrigio/localtuya#950]
After the last update, my LocalTuya was useless. I don't want to use Tuya integration so I lost all Tuya devices.

I had an error on all devices and all them was unavailable. I decides to delete the integration with all devices and recreate them again. But I still have many issues

1. All my devices have more than one entities. One device may have sensors, light, binary sensor, switch etc. But the integration ask for the type of the device only the first time. So. If I want to declare one switch and one sensor the system does not allow me. If I choose the first entity as switch then the integration setup the sensor as switch 🙄🙄🙄🤐🤐🤐
2. If I delete one device in order to recreate it, the time I am going to create the device the system gives me an error and the only way to add it is to restart the whole system. 😴😴
3. After I submit on device the system does not allow me to add another entity for this device.... 🙄🙄🙄
4. All devices are becoming periodically unavailable for a long long time making again the integration useless.😔😔

Anyone with same issues? Anyone who solve some of them?

I cannot find any amswer

**Comment by besiktas97** [comment]
Inam having since today a lot of problems with local tuya. Cloud based they are all online, but with local tuya they are going offline and coming back online again (not all of them).
I am getting this error and have doubts that have to do with the latest core update with python:

This error originated from a custom integration.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:247 
Integration: LocalTuya (documentation, issues) 
First occurred: 00:30:32 (55 occurrences) 
Last logged: 00:41:15

[bf5...hpt] Connect to 192.168.2.31 failed
[bf7...faq] Connect to 192.168.2.22 failed
[237...fd1] Connect to 192.168.2.32 failed
[262...90d] Failed to set DPs {3: 45, 2: 'white', 4: 0}
[bf7...uah] Connect to 192.168.2.28 failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 170, in _make_connection
    status = await self._interface.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by timnolte** [comment]
I am finding now that with my existing device that was working I can no longer add additional entities to the existing device. With all of the reports it seems like this overhaul of the integration didn't work out so well. :-(

**Comment by raytedjaja** [comment]
same problem with me, when i try to configure (via config flow) my switch/outlet with voltage current sensor it won't work stable anymore. 
when i check logs it output some error like `custom_components.localtuya.number::LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.`
