### ISSUE TITLE
Can't add Tuya plug to local tuya

### ISSUE THREAD

**Issue by pjmsheff** [rospogrigio/localtuya#953]
Hi 

I keep having an Unknown error when I try to add new device 

This is the log

Thanks very much

This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:247 
Integration: LocalTuya integration (documentation, issues) 
First occurred: 17:39:50 (2 occurrences) 
Last logged: 17:40:13

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 533, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    detected_dps = await interface.detect_available_dps()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 539, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by Kelesis** [comment]
Hello,

     Same error in the log for me => timeout while waiting for DPS.
     It was ok in 3.5.0. (Haven't tried in 4.0.0)
     (No internet connection for the device and no other app)

     Now if I try to turn on (or off) the plug just before adding it, then there is no timeout, but only the first DPS is being detected. (When selecting "switch" the interface propose the same DPS (1) for switch, current, consumed current, and voltage.
     If I accept, I can indeed turn on and off the plug, but I'm of course not having any information about energy. Hope it helps.

Have a nice day

**Comment by pjmsheff** [comment]
Thanks very much. I’ll give it a try.

**Comment by CloCkWeRX** [comment]
Duplicate of #897

**Comment by OldShaterhan** [comment]
Same for me: https://github.com/rospogrigio/localtuya/issues/973
