### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by CloCkWeRX** [rospogrigio/localtuya#967]
## The problem

Sporadically, I see errors for my PC287HA switch.
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/localtuya/__init__.py", line 282, in setup_entities
    hass.data[DOMAIN][TUYA_DEVICES][dev_id].async_connect()
KeyError: 'bf*********enb9'
```
Unclear of the specific reproduce steps

## Environment

- Localtuya version: master, https://github.com/CloCkWeRX/localtuya-experimental/commit/ac680abcb33c2acbb5464b2a9d194c6c5ce13541
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version:  
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

TBA

## Configuration `configuration.yaml` or `config_flow`

```yaml

```

## Provide Home Assistant taceback/logs

```txt

```

**Comment by creeve4** [comment]
Also seeing this in my logs.

```
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/localtuya/switch.py", line 58, in extra_state_attributes
    self.dps(self._config[CONF_CURRENT_CONSUMPTION]) / 10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by CloCkWeRX** [comment]
@creeve4 - yours has similar symptoms, but from the backtrace I'd say is slightly different. Maybe worth moving your comment to https://github.com/rospogrigio/localtuya/issues/798 which seems to be identical?
