### ISSUE TITLE
Exception in callback _SelectorDatagramTransport._read_ready() - KeyError: (specific key)

### ISSUE THREAD

**Issue by CloCkWeRX** [rospogrigio/localtuya#968]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/localtuya/__init__.py:142
Integration: LocalTuya (documentation, issues)
First occurred: 1:58:56 PM (1 occurrences)
Last logged: 1:58:56 PM
```
Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 70, in datagram_received
    self.device_found(decoded)
  File "/config/custom_components/localtuya/discovery.py", line 79, in device_found
    self._callback(device)
  File "/config/custom_components/localtuya/__init__.py", line 142, in _device_discovered
    device = hass.data[DOMAIN][TUYA_DEVICES][device_id]
KeyError: 'bf****'
```

## Environment

- Localtuya version:  
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version:  
- [] Are you using the Home Assistant Tuya Cloud component ? 
- [] Are you using the Tuya App in parallel ? 

## Steps to reproduce

1.
2. 
3.

## Configuration `configuration.yaml` or `config_flow`

```yaml

```

## Provide Home Assistant taceback/logs

```txt

```

**Comment by palfrey** [comment]
For reference, I got my device that had this error working with https://github.com/make-all/tuya-local
