### ISSUE TITLE
The latest version of Homeassistant and OS cannot connect to the device

### ISSUE THREAD

**Issue by MeowRay** [rospogrigio/localtuya#974]
## Environment
Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4

I confirmed that the device IP is correct and online, everything worked fine before the update
![image](https://user-images.githubusercontent.com/29674595/181432156-1e9fef73-c528-4bdb-9eb8-997edb5c49eb.png)
![image](https://user-images.githubusercontent.com/29674595/181432179-189f2dc5-de92-45ea-b943-58ec9fa6eb8d.png)

## Steps to reproduce

1. Update Homeassistant and OS to the latest version

## Provide Home Assistant taceback/logs

```
2022-07-28 13:50:18 ERROR (MainThread) [custom_components.localtuya.common] [6cf...dcu] Connect to 10.4.1.104 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 160, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('10.4.1.104', 6668)
2022-07-28 13:50:20 INFO (MainThread) [custom_components.xiaomi_miot.sensor] Get xiaomi message for 2670995101 failed: {'code': 0, 'message': 'ok', 'result': {'messages': None}}
2022-07-28 13:50:20 ERROR (MainThread) [custom_components.localtuya.common] [6cd...hle] Connect to 10.4.1.102 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 160, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
```

**Comment by sanjay900** [comment]
I can confirm the same thing has happened to me

**Comment by sanjay900** [comment]
Downgrading home assistant core did not get it working again, so i suspect its a problem with haos

**Comment by johngianni** [comment]
Please help... all my switches are unavailable. I'm in the dark... alone ;)

**Comment by sanjay900** [comment]
Ive also tried restarting home assistant OS in its entirety and that didnt get me back my lights :(

**Comment by snigehere** [comment]
I have had the same issue however it was not directly related to the upgrade.  I upgraded yesterday and all the local stuff worked fine (lights turned on via automations a few hours ago .... this evening all local integrations went off line as described above.  I tried restarting HA but that did not solve it .. I run in vbox under windows 10 so I shutdown the vbox completely and restarted and everything came back online again.

**Comment by sanjay900** [comment]
that is exactly what i tried and it didnt work :(

**Comment by Saentist** [comment]
all problems come from incompatibility with "asyncio" library in haos, 
with is way newer then localtuya is written to work for.
Any reported error after 4.x.x is connected to "asyncio"

**Comment by i-am-shodan** [comment]
Similar problems here with the hass container image

**Comment by snigehere** [comment]
As 4.x was a long time ago does that mean localtuya no longer being maintained and the problems will only get worse as time goes on or is the issue being actively worked on? I ask because I have not used the integration for very long do not want to invest the time if its going to fail completely in the not to distant future.

**Comment by timnolte** [comment]
Yeah, my device keeps going unavailable then will eventually come back. Fortunately, I still have it setup in the Tuya app so I can still control it. The bad part of that I don't get notifications when it turns off. This is a coffee maker so my coffee ends up going cold. 😖

**Comment by snigehere** [comment]
> 

I just set up an automation to send an alert when key devices go unavailable which, I hope, will allow me to restart ha.  So far I have only had one issue since the last syst update but I use local to auto turn on various lights based on movement. If it starts to give more issues I may need to switch to from local to cloud

**Comment by sanjay900** [comment]
What i thought was interesting is i switched to the cloud tuya integration and it had even more issues so i switched back to localtuya, and now its been rather stable ever since i switched back.

**Comment by timnolte** [comment]
I'm thinking that these HA updates have affected a lot of integrations. I'm having more disconnect issues with the MerossLAN integration as well.

**Comment by sanjay900** [comment]
i ended up flashing an alternate firmware to my light bulbs because this annoyed me enough haha

**Comment by jaymier** [comment]
I encountered the same problem, but it returned to normal after I restarted my NAS

**Comment by very-old-guy** [comment]
I am very new to HA - just starting.  It appears to run ok on HAOS 8.2 but if I try to install it on HAOS 8.4 it does not even show up.  An upgrade from 8.2 to 8.4 results in the system failing.  This is in a VM running on a Synology NAS.   

I do not appear to have the same problem with a Raspberry P4.  It installs localTuya with no problems.  I have not tried to install  lights and switches yet.

**Comment by kinkate** [comment]
since I've installed the localtuya integration I can't add devices. I've only hav 4 small switches but always I get "Unknown Error! Read the logs!" And the logs always say:
`2022-08-05 15:40:12.402 ERROR (MainThread) [custom_components.localtuya.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
**asyncio.exceptions.CancelledError**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 533, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    detected_dps = await interface.detect_available_dps()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 539, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
**asyncio.exceptions.TimeoutError**`´
What's going wrong in this case? I tried a new project at Tuya IoT, I verified the local keys, I removed and rediscoverd the devices in my tuya-app, I switched off the App.....Nothing helped!
Does anybody has an idea what I can do, to add my 4(!) tuya-switches?
Thanks! 
Olaf

**Comment by vaderag** [comment]
Looks like I'm in the same boat

I'm new to Home Assistant so not ruling out the fact that I am doing something wrong, but I have successfully connected to my Tuya IOT account and have the devices working locally via other means (e.g. Octoprint) - when I try and actually add the device I get the following in my logs

```
Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:247
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 15:09:28 (5 occurrences)
Last logged: 15:12:45

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 533, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    detected_dps = await interface.detect_available_dps()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 539, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 476, in exchange
    return await self.exchange(command, dps)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by snigehere** [comment]
So I had a similar issue trying to add devices however it was not all devices so there is something odd about this issue.

I installed 3 new rgbw lights and added them to the Tuya app on my phone.  I went through the process to get my local keys and successfully added the first two to the HA localtuya integration without any problem but when I went to add the last one it keeps failing with an error.  I tried a few times, I restarted the integration and it still failed, I restarted HA and it still failed.  .. I can't see what might be different - they are all the same product (YX-ZNLD9-15mA).  Each time it failed it seemed to stop the integration as well as all the other lights went unavailable.  In the end I deleted the failing device from my Tuya app and then recreated it.  I got the new local ID and this time it added to the local integration without any error. 

`Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:259
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 14:01:58 (3 occurrences)
Last logged: 14:15:52

[070...ce5] Failed to set DP 1 to False
[bfb...jzs] Failed to set DP 1 to False
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 316, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 553, in set_dp
    return await self.exchange(SET, {str(dp_index): value})
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 486, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 259, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError`

**Comment by laithsaid** [comment]
Any one got a fix for this issue?
I have the same issue with smart life  smart plugs. They have been working perfectly. After update HA, they stopped working and I started to get the error message in the log.
The smart plugs are working fine with the smart life app, so it is not connectivity issue.

**Comment by dvelayos** [comment]
it's weird, but at leats on the case of the WiFi Smart PIR Motion sensor the device is reachable... at intervals; e.g:

From 192.168.1.141 icmp_seq=3242 Destination Host Unreachable
From 192.168.1.141 icmp_seq=3243 Destination Host Unreachable
From 192.168.1.141 icmp_seq=3247 Destination Host Unreachable
From 192.168.1.141 icmp_seq=3248 Destination Host Unreachable
From 192.168.1.141 icmp_seq=3249 Destination Host Unreachable
From 192.168.1.141 icmp_seq=3250 Destination Host Unreachable
From 192.168.1.141 icmp_seq=3251 Destination Host Unreachable
64 bytes from 192.168.1.81: icmp_seq=3254 ttl=255 time=743 ms
64 bytes from 192.168.1.81: icmp_seq=3255 ttl=255 time=49.5 ms
64 bytes from 192.168.1.81: icmp_seq=3256 ttl=255 time=22.5 ms
64 bytes from 192.168.1.81: icmp_seq=3257 ttl=255 time=94.2 ms
64 bytes from 192.168.1.81: icmp_seq=3258 ttl=255 time=121 ms
64 bytes from 192.168.1.81: icmp_seq=3259 ttl=255 time=149 ms
64 bytes from 192.168.1.81: icmp_seq=3260 ttl=255 time=62.5 ms
64 bytes from 192.168.1.81: icmp_seq=3261 ttl=255 time=82.6 ms
64 bytes from 192.168.1.81: icmp_seq=3263 ttl=255 time=11.1 ms
From 192.168.1.141 icmp_seq=3308 Destination Host Unreachable
From 192.168.1.141 icmp_seq=3309 Destination Host Unreachable
From 192.168.1.141 icmp_seq=3310 Destination Host Unreachable
From 192.168.1.141 icmp_seq=3311 Destination Host Unreachable
From 192.168.1.141 icmp_seq=3312 Destination Host Unreachable

it seems that the device is disabling the local ip port most of the time (battery saving?) but at intervals (or when the PIR detects movement) the sensor raises again the 6668 port and it's reachable.

i've checked this adding the new sensor only when the ping works, and i've managed to configure it. most of the time the PIR sensor appears as "not available" untila  movement is detected, and the problem with this is that the movement event is delayed by 3-6 seconds, so it's unusable for lilghts (when the light is finally on, you don't need the light :-)

**Comment by Heisenberg2980** [comment]
Just found this issue while trying to find out why I couldn´t setup my device in localtuya as the setup was always failing with the error "Connect call failed", does this mean localtuya is dead and local control for tuya devices is no longer available? Is this happening with all devices or just with new ones? (not sure if it is related but the documentation in the repo mentions protocol 3.4 is not supported)

**Comment by HSB-collab** [comment]
Same issue as @snigehere - 3 smart bulbs but one won't connect using localtuya (so I have to use the Tuya cloud integration) and the other 2 work but keep dropping off.
How do I downgrade the localtuya integration to 4.0.2 which I saw somewhere is the last version that worked? Do I have to remove it and then manually install the older version?

**Comment by laithsaid** [comment]
I stopped using localtuya and started to use the cloud one.

**Comment by dpgh947** [comment]
After having had the "official" tuya integration working perfectly for absolutely ages (everything responding and updating instantly), it has started doing what it last did to me a year or more back - when you switch a device in HA, the physical device responds instantly, but the status confirmation back to HA seems to take about 5 seconds, so you turn a plug on in HA, the physical plug turns on, then the switch in HA moves back to off, then 4-5 seconds later it moves to on again. And sometimes it doesn't move back to on at all, so then the status in HA is out of step with the device. Is anyone else seeing this behaviour start recently?

I have been experimenting with localtuya (I didn't realise you could happily run both), and it seems good, although I do have 2 old plugs (out of my 18 smart life devices) which I had to add as "3.1" protocol devices, and which then don't work. If I switch them elsewhere (IE: physically or in the official tuya), the localtuya switch in HA is instantly updated, but if I operate the localtuya switch, the plug doesn't respond.

**Comment by dukeofnukem815** [comment]
had a perfectly working nous A1 which I accidentally reset. Adding it to my tuya cloud again and extracting the localkey was a bit of a hassle but now I am stuck in this boat as well. Running around 20-odd tuya devices and so far avoiding the official cloud integration I am now tiptoeing around my plugs ;-)

Has anyone made any progress or found a workaround for the problem?

**Comment by HSB-collab** [comment]
> had a perfectly working nous A1 which I accidentally reset. Adding it to my tuya cloud again and extracting the localkey was a bit of a hassle but now I am stuck in this boat as well. Running around 20-odd tuya devices and so far avoiding the official cloud integration I am now tiptoeing around my plugs ;-)
> 
> Has anyone made any progress or found a workaround for the problem?

In my case I found it was because of problems with my 2.4GHz WiFi. In an urban environment there is a lot of interference in the 2.4GHz band so I carefully chose my bands and the problem seems to have gone away.

**Comment by dukeofnukem815** [comment]
> In my case I found it was because of problems with my 2.4GHz WiFi. In an urban environment there is a lot of interference in the 2.4GHz band so I carefully chose my bands and the problem seems to have gone away.

That's somewhat odd - for my part I have no problem controlling the plug from the smart life app (despite it being forbidden to communicate outside the LAN, including forcing local DNS on the Firewall). OTOH I keep getting the described errors with matching log entries when trying to add the plug to the localtuya integration.

Thanks for the input!

**Comment by dukeofnukem815** [comment]
Just because it hasn't been mentioned here (although I am sure the author is aware of it) - upon restarting HA it complains in the logs about localtuya:

`2022-12-06 00:58:18.925 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-06 00:58:22.181 WARNING (MainThread) [homeassistant.components.number] custom_components.localtuya.number::LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2022-12-06 00:58:22.383 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom integration author for localtuya using this method at custom_components/localtuya/__init__.py, line 315: ent_reg = await er.async_get_registry(hass)`

**Comment by rospogrigio** [comment]
> `2022-12-06 00:58:22.383 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom integration author for localtuya using this method at custom_components/localtuya/__init__.py, line 315: ent_reg = await er.async_get_registry(hass)`

This was fixed. Are you using the most recent release? Or at least 4.0.2? It was fixed in that version.

**Comment by dukeofnukem815** [comment]
@rospogrigio : Thanks for the hint, I had to completely delete my custom_components/localtuya folder and replace it with the current git pull. Now I'm down to

`2022-12-07 13:07:07.240 ERROR (MainThread) [custom_components.localtuya.pytuya] [025...147] Failed to get status:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
await fut
asyncio.exceptions.CancelledError`

**Comment by ladykira2022** [comment]
Hello!
I have a similar issue and cannot figure out what is the root cause.
I cannot add any local Tuya devices, I get this in the logs.
Home Assistant 2022.12.6
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.0 - latest

//Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 580, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 245, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 704, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('10.0.1.51', 6668)

**Comment by Saentist** [comment]
@ladykira2022 
set tuya devices in your dhcp to get always same ip

**Comment by ladykira2022** [comment]
> 

I've done that, it does not help. Probably something happen during some updates because it used to work.

**Comment by kzaoaai** [comment]
Yea, static DHCP doesn't help. For me, it's the same 3 devices that suffer from this. All other Tuya wifi devices are not affected.

**Comment by Saentist** [comment]
> > 
> 
> I've done that, it does not help. Probably something happen during some updates because it used to work.

Is this devices are on battery and connect when some value is changed?

**Comment by ladykira2022** [comment]
> > I've done that, it does not help. Probably something happen during some updates because it used to work.
> 
> Is this devices are on battery and connect when some value is changed?
 
The devices are wifi plugs connected to the power all the time.
I was able to get them by doing these steps:
-disable the Tuya cloud integration in HA
-the phone was in flight mode, no wifi connection so it does not connect to tuya cloud
-assigned static dhcp allocation (my network is based on unifi devices- was done via the unifi controller)
-after assigning the static dhcp i had to renew the dhcp lease (reconnect the device)
-reload local tuya integration
After doing these steps i can add the devices in local tuya.
Hope it helps someone . Thank you to all who contributed.
CC

**Comment by kconfesor** [comment]
Thanks @ladykira2022 I can confirm that works. I was able to make it work with the mapping static IP Address to devices on router + reconnect (renew lease), after devices reconnected i was able to add them on HA, btw i do not have Tuya Cloud Integration installed.

**Comment by Heisenberg2980** [comment]
@ladykira2022 I can´t believe it but your steps made the trick, IT WORKS!! I have been able to add all devices that I couldn´t add before to Local Tuya. 

I have some devices and scenes that need Tuya Cloud, so after following your steps and adding the devices to Local Tuya I have enabled Tuya Cloud integration and it seems everything is working, and I can control the devices added to Local Tuya from both Local Tuya and Tuya Cloud

**Comment by Heisenberg2980** [comment]
Replying to my last message, I'm not sure what happened (maybe I needed to restart HA after the devices became unavailable in Local Tuya?) but I just found out all the devices I added to Local Tuya are now working completely fine and I can control them from both Local Tuya and Tuya Cloud, so unless they stop working at some point, the solution from @ladykira2022 works as a charm!!

**Comment by Wergilius** [comment]
@ladykira2022, thanks it works for me as well.
I had no problem add devices from the tuya app and deltaco app but deltaco device SH-LE27CCTC did not work.
Gave (new) static IP but HA did not detect the new IP (reboot might had helped) but I changed it manually and it added the devices.

**Comment by Saentist** [comment]
> @ladykira2022, thanks it works for me as well. I had no problem add devices from the tuya app and deltaco app but deltaco device SH-LE27CCTC did not work. Gave (new) static IP but HA did not detect the new IP (reboot might had helped) but I changed it manually and it added the devices.

Reduce dhcp leasing time  to 10min.

**Comment by bositman** [comment]
Getting the same error as OP every couple of hours or so. It's a heat radiator, in the same room as the router, with a static IP.
My concern is not the couple of seconds I lose connection with the device, but it seems to cause the NIC of the raspberry pi to stop responding while this happens...so I get network disconnections each time this occurs. No idea how/why this happens but it seems this integration is what is causing this (running a ping script and pings fail at the ~3 seconds this error comes up)
Any ideas?

**Comment by joeinaustin** [comment]
Same issue.  Cannot add.  Logs below..
```
This error originated from a custom integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:1163
Integration: LocalTuya (documentation, issues)
First occurred: 11:11:39 AM (1 occurrences)
Last logged: 11:11:39 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 581, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 240, in validate_input
    interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1163, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.123', 6668)
```
