### ISSUE TITLE
Home Assisant  2022.8.0 breaks local tuya

### ISSUE THREAD

**Issue by jjvandenberg** [rospogrigio/localtuya#980]
right after upgrading to  HA 2022.8.0 , the local tuya integration is broken.

log reports:

Logger: homeassistant.config_entries
Source: custom_components/localtuya/__init__.py:242
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 20:37:02 (2 occurrences)
Last logged: 20:41:46

Error setting up entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 242, in async_setup_entry
    region = entry.data[CONF_REGION]
KeyError: 'region'

Deze fout is ontstaan door een aangepaste integratie.

local tuya version probably 4.0.1, cannnot find a version number  in HA ....

**Comment by jjvandenberg** [comment]
Seems to be fixed in HA 2022.8.1

**Comment by jjvandenberg** [comment]
not longer relevant

**Comment by drew-hill** [comment]
Getting this now with latest HA (HA 2023.2.5, Supervisor 2023.01.01, OS 9.5). Were there any work arounds for when this was discovered back in August?

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/localtuya/__init__.py:242 
Integration: LocalTuya (documentation, issues) 
First occurred: 11:00:36 AM (1 occurrences) 
Last logged: 11:00:36 AM

Error setting up entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 242, in async_setup_entry
    region = entry.data[CONF_REGION]
KeyError: 'region'
`

**Comment by ettiennegous** [comment]
I just got the same thing

```
2023-03-06 22:02:32.641 DEBUG (MainThread) [custom_components.localtuya.discovery] Listening to broadcasts on UDP port 6666 and 6667
2023-03-06 22:02:32.664 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 242, in async_setup_entry
    region = entry.data[CONF_REGION]
KeyError: 'region'
```

**Comment by noob4722019** [comment]
Still relevant. Mine broke after deleting a device, and then attempting to re-add it. It seemed to successfully add, but then didn't appear as a device, tried it again, and it didn't occur again.

Ended up restarting Home Assistant then localtuya filed to load with.

```
2023-03-11 19:48:12.770 INFO (MainThread) [homeassistant.setup] Setup of domain application_credentials took 0.4 seconds
2023-03-11 19:48:12.770 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 242, in async_setup_entry
    region = entry.data[CONF_REGION]
KeyError: 'region'

```
Oddly, my last 2 months worth of backups were also corrupt, so I was forced to use an old backup to get Localtuya working again. This happened on 4.1.0. I tried downgrading to 4.0.0, but it didn't solve the problem.

**Comment by DeltaTangoLima** [comment]
Chiming in to say I've just had an identical experience to @noob4722019 - deleted a device that was playing up, went to re-add it. Interface gave no indication it was either added or had a problem, and got the following logs when restarting HA:

```
Error setting up entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 242, in async_setup_entry
    region = entry.data[CONF_REGION]
KeyError: 'region'

```

Restored from this morning's daily backup and I'm back to where I started. The Tuya device in question is no longer misbehaving, so I'll leave well enough alone while I await some clarity on this thread.
