### ISSUE TITLE
Tuya Local down???

### ISSUE THREAD

**Issue by ggdijkstra** [rospogrigio/localtuya#992]
Question is it true that there are more problems Tuya Local after the update of 2022.8.5 or did I overlook something? My devices lose the connection with HA and in just Tuya-app they work...
As I can see it now it is an api - problem between HA and Tuya?

**Comment by Xitro01** [comment]
Same issue here, broke down after the 2022.8.5 update.

`Logger: homeassistant.config_entries
Source: config_entries.py:605
First occurred: 16:16:49 (1 occurrences)
Last logged: 16:16:49

Error unloading entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 496, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 308, in async_unload_entry
    hass.data[DOMAIN][entry.entry_id][UNSUB_LISTENER]()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 605, in <lambda>
    return lambda: self.update_listeners.remove(weak_listener)
ValueError: list.remove(x): x not in list`

**Comment by DuPunk** [comment]
I'm experiencing this problem as well have reloaded intergration multiple times and restarted home assistant repeatedly. It will work for a little while but eventually devices become unavailable again

**Comment by dantetekanem** [comment]
I don't know if there's a connection, but I was seeing this problem after updating to `2022.8.4`, and for the past 2 days none of my devices went disconnected. What I did was rebooting my main Router (I use a MESH system) and HA. I can still see those errors in the log, but the devices are kept connected.

**Comment by CloCkWeRX** [comment]
I'm noticing this as well.

I feel like:
```
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 605, in <lambda>
    return lambda: self.update_listeners.remove(weak_listener)
ValueError: list.remove(x): x not in list
```
Is a bit of a bug in home assistant, shoudn't it check before trying to change a list?
