### ISSUE TITLE
An unknown error occurred. See log for details.

### ISSUE THREAD

**Issue by 1mseba** [rospogrigio/localtuya#994]
When trying to connect, I get an error as in the title.
I fill in all the fields correctly.

I have 2 errors in my logs:

1) This error is from non-standard integration.

Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:247
Integration: LocalTuya integration (documentation, issues)
First occurred: 21:14:33 (1 occurrences)
Last logged: 21:14:33

[bfb...ryp] Failed to get status:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 539, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

2) This error is from non-standard integration.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/pytuya/__init__.py:247
Integration: LocalTuya integration (documentation, issues)
First occurred: 21:14:33 (1 occurrences)
Last logged: 21:14:33

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 533, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    detected_dps = await interface.detect_available_dps()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 539, in detect_available_dps
    data = await self.status()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 481, in status
    status = await self.exchange(STATUS)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 460, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 247, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

Please suggest to me.

**Comment by Merril-r** [comment]
I am having the same issues when trying to add any new devices

**Comment by lukonin** [comment]
Same for me, but not for all Tuya devices. For example, I cannot add Tuya Smart Lamp Holders, but I have successfully added two new Hiper IoT LED lamps throught Tuya Smart and then to HA through Tuya Local.

**Comment by besiktas97** [comment]
Wondering if local_tuya will be still maintenanced. Didnt hear anything of the creator of this integration for a while

**Comment by 1mseba** [comment]
Mine is a new device socket plug with a current meter.
I've been waiting for 3 days and it looks like this integration is no longer supported.

**Comment by Merril-r** [comment]
That will suck big time if it is no longer supported. 

I am trying to add lights. I know they work with this integration as I have ones that have already working.

**Comment by rospogrigio** [comment]
> Wondering if local_tuya will be still maintenanced. Didnt hear anything of the creator of this integration for a while

I was on vacation. But I don't own these devices so you need to wait for some developer who owns them to provide a PR that I can merge, sorry.

**Comment by Merril-r** [comment]
> > Wondering if local_tuya will be still maintenanced. Didnt hear anything of the creator of this integration for a while
> 
> I was on vacation. But I don't own these devices so you need to wait for some developer who owns them to provide a PR that I can merge, sorry.

Hi @rospogrigio 

I get the same error on a light bulb. I have a couple of these bulbs that were added to local tuya prior to version 4.0. So in my case it is not a "new" piece of hardware that I am trying to add for the first time

**Comment by rospogrigio** [comment]
Looks like you are having connection problems... have you tried putting the bulb closer to the router?

**Comment by Merril-r** [comment]
The bulb is about 2m away from the router. 

I have shutdown everything and started up as well as shutting down the mains and back on. Still cannot add it.

**Comment by rospogrigio** [comment]
Really don't know how to help, I'm sorry...

**Comment by Merril-r** [comment]
> Really don't know how to help, I'm sorry...

I guess that the end of local tuya for me then. 

Thanks anyway

**Comment by 1mseba** [comment]
new version solved the issue,
thank you @rospogrigio
